-- Generated by script/extract-doc-sql.js from doc/src/sgml/advanced.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- advanced.sgml:47
CREATE VIEW myview AS
    SELECT name, temp_lo, temp_hi, prcp, date, location
        FROM weather, cities
        WHERE city = name;

-- advanced.sgml:47
SELECT * FROM myview;

-- advanced.sgml:102
CREATE TABLE cities (
        name     varchar(80) PRIMARY KEY,
        location point
);

-- advanced.sgml:102
CREATE TABLE weather (
        city      varchar(80) REFERENCES cities (name),
        temp_lo   int,
        temp_hi   int,
        prcp      real,
        date      date
);

-- advanced.sgml:119
INSERT INTO weather VALUES ('Berkeley', 45, 53, 0.0, '1994-11-28');

-- advanced.sgml:163
UPDATE accounts SET balance = balance - 100.00
    WHERE name = 'Alice';

-- advanced.sgml:163
UPDATE branches SET balance = balance - 100.00
    WHERE name = (SELECT branch_name FROM accounts WHERE name = 'Alice');

-- advanced.sgml:163
UPDATE accounts SET balance = balance + 100.00
    WHERE name = 'Bob';

-- advanced.sgml:163
UPDATE branches SET balance = balance + 100.00
    WHERE name = (SELECT branch_name FROM accounts WHERE name = 'Bob');

-- advanced.sgml:225
BEGIN;

-- advanced.sgml:225
COMMIT;

-- advanced.sgml:305
SAVEPOINT my_savepoint;

-- advanced.sgml:305
ROLLBACK TO my_savepoint;

-- advanced.sgml:305
UPDATE accounts SET balance = balance + 100.00
    WHERE name = 'Wally';

-- advanced.sgml:354
SELECT depname, empno, salary, avg(salary) OVER (PARTITION BY depname) FROM empsalary;

-- advanced.sgml:402
SELECT depname, empno, salary,
       row_number() OVER (PARTITION BY depname ORDER BY salary DESC)
FROM empsalary;

-- advanced.sgml:470
SELECT salary, sum(salary) OVER () FROM empsalary;

-- advanced.sgml:499
SELECT salary, sum(salary) OVER (ORDER BY salary) FROM empsalary;

-- advanced.sgml:540
SELECT depname, empno, salary, enroll_date
FROM
  (SELECT depname, empno, salary, enroll_date,
     row_number() OVER (PARTITION BY depname ORDER BY salary DESC, empno) AS pos
     FROM empsalary
  ) AS ss
WHERE pos < 3;

-- advanced.sgml:563
SELECT sum(salary) OVER w, avg(salary) OVER w
  FROM empsalary
  WINDOW w AS (PARTITION BY depname ORDER BY salary DESC);

-- advanced.sgml:599
CREATE TABLE capitals (
  name       text,
  population real,
  elevation  int,    -- (in ft)
  state      char(2)
);

-- advanced.sgml:599
CREATE TABLE non_capitals (
  name       text,
  population real,
  elevation  int     -- (in ft)
);

-- advanced.sgml:599
CREATE VIEW cities AS
  SELECT name, population, elevation FROM capitals
    UNION
  SELECT name, population, elevation FROM non_capitals;

-- advanced.sgml:626
CREATE TABLE cities (
  name       text,
  population real,
  elevation  int     -- (in ft)
);

-- advanced.sgml:626
CREATE TABLE capitals (
  state      char(2) UNIQUE NOT NULL
) INHERITS (cities);

-- advanced.sgml:659
SELECT name, elevation
  FROM cities
  WHERE elevation > 500;

-- advanced.sgml:682
SELECT name, elevation
    FROM ONLY cities
    WHERE elevation > 500;
