-- Generated by script/extract-doc-sql.js from doc/src/sgml/array.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- array.sgml:27
CREATE TABLE sal_emp (
    name            text,
    pay_by_quarter  integer[],
    schedule        text[][]
);

-- array.sgml:50
CREATE TABLE tictactoe (
    squares   integer[3][3]
);

-- array.sgml:139
INSERT INTO sal_emp
    VALUES ('Bill',
    '{10000, 10000, 10000, 10000}',
    '{{"meeting", "lunch"}, {"training", "presentation"}}');

-- array.sgml:139
INSERT INTO sal_emp
    VALUES ('Carol',
    '{20000, 25000, 25000, 25000}',
    '{{"breakfast", "consulting"}, {"meeting", "lunch"}}');

-- array.sgml:155
SELECT * FROM sal_emp;

-- array.sgml:169
INSERT INTO sal_emp
    VALUES ('Bill',
    '{10000, 10000, 10000, 10000}',
    '{{"meeting", "lunch"}, {"meeting"}}');

-- array.sgml:181
INSERT INTO sal_emp
    VALUES ('Bill',
    ARRAY[10000, 10000, 10000, 10000],
    ARRAY[['meeting', 'lunch'], ['training', 'presentation']]);

-- array.sgml:181
INSERT INTO sal_emp
    VALUES ('Carol',
    ARRAY[20000, 25000, 25000, 25000],
    ARRAY[['breakfast', 'consulting'], ['meeting', 'lunch']]);

-- array.sgml:214
SELECT name FROM sal_emp WHERE pay_by_quarter[1] <> pay_by_quarter[2];

-- array.sgml:233
SELECT pay_by_quarter[3] FROM sal_emp;

-- array.sgml:251
SELECT schedule[1:2][1:1] FROM sal_emp WHERE name = 'Bill';

-- array.sgml:266
SELECT schedule[1:2][2] FROM sal_emp WHERE name = 'Bill';

-- array.sgml:285
SELECT schedule[:2][2:] FROM sal_emp WHERE name = 'Bill';

-- array.sgml:285
SELECT schedule[:][1:1] FROM sal_emp WHERE name = 'Bill';

-- array.sgml:328
SELECT array_dims(schedule) FROM sal_emp WHERE name = 'Carol';

-- array.sgml:344
SELECT array_upper(schedule, 1) FROM sal_emp WHERE name = 'Carol';

-- array.sgml:356
SELECT array_length(schedule, 1) FROM sal_emp WHERE name = 'Carol';

-- array.sgml:369
SELECT cardinality(schedule) FROM sal_emp WHERE name = 'Carol';

-- array.sgml:391
UPDATE sal_emp SET pay_by_quarter = '{25000,25000,27000,27000}'
    WHERE name = 'Carol';

-- array.sgml:398
UPDATE sal_emp SET pay_by_quarter = ARRAY[25000,25000,27000,27000]
    WHERE name = 'Carol';

-- array.sgml:405
UPDATE sal_emp SET pay_by_quarter[4] = 15000
    WHERE name = 'Bill';

-- array.sgml:412
UPDATE sal_emp SET pay_by_quarter[1:2] = '{27000,27000}'
    WHERE name = 'Carol';

-- array.sgml:443
SELECT ARRAY[1,2] || ARRAY[3,4];

-- array.sgml:443
SELECT ARRAY[5,6] || ARRAY[[1,2],[3,4]];

-- array.sgml:469
SELECT array_dims(1 || '[0:1]={2,3}'::int[]);

-- array.sgml:469
SELECT array_dims(ARRAY[1,2] || 3);

-- array.sgml:489
SELECT array_dims(ARRAY[1,2] || ARRAY[3,4,5]);

-- array.sgml:489
SELECT array_dims(ARRAY[[1,2],[3,4]] || ARRAY[[5,6],[7,8],[9,0]]);

-- array.sgml:510
SELECT array_dims(ARRAY[1,2] || ARRAY[[3,4],[5,6]]);

-- array.sgml:526
SELECT array_prepend(1, ARRAY[2,3]);

-- array.sgml:526
SELECT array_append(ARRAY[1,2], 3);

-- array.sgml:526
SELECT array_cat(ARRAY[1,2], ARRAY[3,4]);

-- array.sgml:526
SELECT array_cat(ARRAY[[1,2],[3,4]], ARRAY[5,6]);

-- array.sgml:526
SELECT array_cat(ARRAY[5,6], ARRAY[[1,2],[3,4]]);

-- array.sgml:565
SELECT ARRAY[1, 2] || '{3, 4}';  -- the untyped literal is taken as an array

-- array.sgml:565
SELECT ARRAY[1, 2] || '7';                 -- so is this one

-- array.sgml:565
SELECT ARRAY[1, 2] || NULL;                -- so is an undecorated NULL

-- array.sgml:565
SELECT array_append(ARRAY[1, 2], NULL);    -- this might have been meant

-- array.sgml:611
SELECT * FROM sal_emp WHERE pay_by_quarter[1] = 10000 OR
                            pay_by_quarter[2] = 10000 OR
                            pay_by_quarter[3] = 10000 OR
                            pay_by_quarter[4] = 10000;

-- array.sgml:623
SELECT * FROM sal_emp WHERE 10000 = ANY (pay_by_quarter);

-- array.sgml:630
SELECT * FROM sal_emp WHERE 10000 = ALL (pay_by_quarter);

-- array.sgml:640
SELECT * FROM
   (SELECT pay_by_quarter,
           generate_subscripts(pay_by_quarter, 1) AS s
      FROM sal_emp) AS foo
 WHERE pay_by_quarter[s] = 10000;

-- array.sgml:656
SELECT * FROM sal_emp WHERE pay_by_quarter && ARRAY[10000];

-- array.sgml:671
SELECT array_position(ARRAY['sun','mon','tue','wed','thu','fri','sat'], 'mon');

-- array.sgml:671
SELECT array_positions(ARRAY[1, 4, 3, 1, 3, 4, 2, 1], 1);

-- array.sgml:742
SELECT f1[1][-2][3] AS e1, f1[1][-1][5] AS e2
 FROM (SELECT '[1:1][-2:-1][3:5]={{{1,2,3},{4,5,6}}}'::int[] AS f1) AS ss;
