-- Generated by script/extract-doc-sql.js from doc/src/sgml/auto-explain.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- auto-explain.sgml:22
LOAD 'auto_explain';

-- auto-explain.sgml:365
SET auto_explain.log_min_duration = 0;

-- auto-explain.sgml:365
SET auto_explain.log_analyze = true;

-- auto-explain.sgml:365
SELECT count(*)
           FROM pg_class, pg_index
           WHERE oid = indrelid AND indisunique;
