-- Generated by script/extract-doc-sql.js from doc/src/sgml/backup.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- backup.sgml:976
SELECT pg_backup_start(label => 'label', fast => false);

-- backup.sgml:1014
SELECT * FROM pg_backup_stop(wait_for_archive => true);
