-- Generated by script/extract-doc-sql.js from doc/src/sgml/bloom.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- bloom.sgml:83
CREATE INDEX bloomidx ON tbloom USING bloom (i1,i2,i3)
       WITH (length=80, col1=2, col2=2, col3=4);

-- bloom.sgml:101
CREATE TABLE tbloom AS
   SELECT
     (random() * 1000000)::int AS i1,
     (random() * 1000000)::int AS i2,
     (random() * 1000000)::int AS i3,
     (random() * 1000000)::int AS i4,
     (random() * 1000000)::int AS i5,
     (random() * 1000000)::int AS i6
   FROM
  generate_series(1,10000000);

-- bloom.sgml:238
CREATE OPERATOR CLASS text_ops
DEFAULT FOR TYPE text USING bloom AS
    OPERATOR    1   =(text, text),
    FUNCTION    1   hashtext(text);
