-- Generated by script/extract-doc-sql.js from doc/src/sgml/btree-gin.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- btree-gin.sgml:44
CREATE TABLE test (a int4);

-- btree-gin.sgml:44
CREATE INDEX testidx ON test USING GIN (a);

-- btree-gin.sgml:44
SELECT * FROM test WHERE a < 10;
