-- Generated by script/extract-doc-sql.js from doc/src/sgml/btree-gist.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- btree-gist.sgml:75
CREATE INDEX testidx ON test USING GIST (a);

-- btree-gist.sgml:75
SELECT *, a <-> 42 AS dist FROM test ORDER BY a <-> 42 LIMIT 10;

-- btree-gist.sgml:91
CREATE TABLE zoo (
  cage   INTEGER,
  animal TEXT,
  EXCLUDE USING GIST (cage WITH =, animal WITH <>)
);

-- btree-gist.sgml:91
INSERT INTO zoo VALUES(123, 'zebra');

-- btree-gist.sgml:91
INSERT INTO zoo VALUES(123, 'lion');

-- btree-gist.sgml:136
CREATE TABLE mytable (addr inet);

-- btree-gist.sgml:136
CREATE INDEX dubious_index ON mytable USING GIST (addr gist_inet_ops);

-- btree-gist.sgml:150
CREATE INDEX good_index ON mytable USING GIST (addr inet_ops);

-- btree-gist.sgml:150
DROP INDEX bad_index;
