-- Generated by script/extract-doc-sql.js from doc/src/sgml/charset.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- charset.sgml:463
CREATE COLLATION mycollation1 (provider = icu, locale = 'ja-JP');

-- charset.sgml:463
CREATE COLLATION mycollation2 (provider = icu, locale = 'fr');

-- charset.sgml:477
CREATE COLLATION mycollation3 (provider = icu, locale = 'en-US-u-kn-true');

-- charset.sgml:508
CREATE COLLATION nonsense (provider = icu, locale = 'nonsense');

-- charset.sgml:571
CREATE COLLATION mycollation5 (provider = icu, deterministic = false, locale = 'en-US-u-kn-ks-level2');

-- charset.sgml:571
SELECT 'aB' = 'Ab' COLLATE mycollation5 AS result;

-- charset.sgml:571
SELECT 'N-45' < 'N-123' COLLATE mycollation5 AS result;

-- charset.sgml:758
SELECT a < 'foo' FROM test1;

-- charset.sgml:764
SELECT a < ('foo' COLLATE "fr_FR") FROM test1;

-- charset.sgml:770
SELECT a < b FROM test1;

-- charset.sgml:779
SELECT a < b COLLATE "de_DE" FROM test1;

-- charset.sgml:783
SELECT a COLLATE "de_DE" < b FROM test1;

-- charset.sgml:787
SELECT a || b FROM test1;

-- charset.sgml:800
SELECT * FROM test1 ORDER BY a || 'foo';

-- charset.sgml:805
SELECT * FROM test1 ORDER BY a || b;

-- charset.sgml:812
SELECT * FROM test1 ORDER BY a || b COLLATE "fr_FR";

-- charset.sgml:1033
SELECT a COLLATE "C" < b COLLATE "POSIX" FROM test1;

-- charset.sgml:1123
CREATE COLLATION german (provider = libc, locale = 'de_DE');

-- charset.sgml:1148
CREATE COLLATION german (provider = icu, locale = 'de-DE');

-- charset.sgml:1172
CREATE COLLATION german FROM "de_DE";

-- charset.sgml:1172
CREATE COLLATION french FROM "fr-x-icu";

-- charset.sgml:1202
CREATE COLLATION ndcoll (provider = icu, locale = 'und', deterministic = false);

-- charset.sgml:1210
CREATE COLLATION case_insensitive (provider = icu, locale = 'und-u-ks-level2', deterministic = false);

-- charset.sgml:1210
CREATE COLLATION ignore_accents (provider = icu, locale = 'und-u-ks-level1-kc-true', deterministic = false);

-- charset.sgml:1250
CREATE COLLATION ignore_accent_case (provider = icu, deterministic = false, locale = 'und-u-ks-level1');

-- charset.sgml:1250
SELECT 'Å' = 'A' COLLATE ignore_accent_case; -- true

-- charset.sgml:1250
SELECT 'z' = 'Z' COLLATE ignore_accent_case; -- true

-- charset.sgml:1250
CREATE COLLATION upper_first (provider = icu, locale = 'und-u-kf-upper');

-- charset.sgml:1250
SELECT 'B' < 'b' COLLATE upper_first; -- true

-- charset.sgml:1250
CREATE COLLATION num_ignore_punct (provider = icu, deterministic = false, locale = 'und-u-ka-shifted-kn');

-- charset.sgml:1250
SELECT 'id-45' < 'id-123' COLLATE num_ignore_punct; -- true

-- charset.sgml:1250
SELECT 'w;x*y-z' = 'wxyz' COLLATE num_ignore_punct; -- true

-- charset.sgml:1386
CREATE COLLATION level3 (provider = icu, deterministic = false, locale = 'und-u-ka-shifted-ks-level3');

-- charset.sgml:1386
CREATE COLLATION level4 (provider = icu, deterministic = false, locale = 'und-u-ka-shifted-ks-level4');

-- charset.sgml:1386
CREATE COLLATION identic (provider = icu, deterministic = false, locale = 'und-u-ka-shifted-ks-identic');

-- charset.sgml:1386
SELECT 'ab' = U&'a\2063b' COLLATE level4; -- true

-- charset.sgml:1386
SELECT 'ab' = U&'a\2063b' COLLATE identic; -- false

-- charset.sgml:1386
SELECT 'x-y' = 'x_y' COLLATE level3; -- true

-- charset.sgml:1386
SELECT 'x-y' = 'x_y' COLLATE level4; -- false

-- charset.sgml:2251
CREATE DATABASE korean WITH ENCODING 'EUC_KR' LC_COLLATE='ko_KR.euckr' LC_CTYPE='ko_KR.euckr' TEMPLATE=template0;

-- charset.sgml:2363
SHOW client_encoding;

-- charset.sgml:2369
RESET client_encoding;
