-- Generated by script/extract-doc-sql.js from doc/src/sgml/config.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- config.sgml:310
SET configuration_parameter TO DEFAULT;

-- config.sgml:314
UPDATE pg_settings SET setting = reset_val WHERE name = 'configuration_parameter';

-- config.sgml:4898
SELECT DISTINCT plugin FROM pg_replication_slots WHERE plugin IS NOT NULL;

-- config.sgml:6813
CREATE TABLE child1000(CHECK (key BETWEEN 1000 AND 1999)) INHERITS(parent);

-- config.sgml:6813
CREATE TABLE child2000(CHECK (key BETWEEN 2000 AND 2999)) INHERITS(parent);

-- config.sgml:6813
SELECT * FROM parent WHERE key = 2400;

-- config.sgml:8383
SELECT to_hex(trunc(EXTRACT(EPOCH FROM backend_start))::integer) || '.' ||
       to_hex(pid)
FROM pg_stat_activity;

-- config.sgml:8700
CREATE TABLE postgres_log
(
  log_time timestamp(3) with time zone,
  user_name text,
  database_name text,
  process_id integer,
  connection_from text,
  session_id text,
  session_line_num bigint,
  command_tag text,
  session_start_time timestamp with time zone,
  virtual_transaction_id text,
  transaction_id bigint,
  error_severity text,
  sql_state_code text,
  message text,
  detail text,
  hint text,
  internal_query text,
  internal_query_pos integer,
  context text,
  query text,
  query_pos integer,
  location text,
  application_name text,
  backend_type text,
  leader_pid integer,
  query_id bigint,
  PRIMARY KEY (session_id, session_line_num)
);

-- config.sgml:8738
COPY postgres_log FROM '/full/path/to/logfile.csv' WITH csv;
