-- Generated by script/extract-doc-sql.js from doc/src/sgml/cube.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- cube.sgml:251
SELECT c FROM test ORDER BY c <-> cube(ARRAY[0.5, 0.5, 0.5]) LIMIT 1;

-- cube.sgml:261
SELECT c FROM test ORDER BY c ~> 1 LIMIT 5;

-- cube.sgml:266
SELECT c FROM test ORDER BY c ~> 3 DESC LIMIT 5;

-- cube.sgml:542
SELECT cube_union('(0,5,2),(2,3,1)', '0');

-- cube.sgml:554
SELECT cube_inter('(0,-1),(1,1)', '(-2),(2)');

-- cube.sgml:581
SELECT cube_contains('(0,0),(1,1)', '0.5,0.5');
