-- Generated by script/extract-doc-sql.js from doc/src/sgml/datatype.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- datatype.sgml:717
SELECT x,
  round(x::numeric) AS num_round,
  round(x::double precision) AS dbl_round
FROM generate_series(-3.5, 3.5, 1) AS x;

-- datatype.sgml:1096
SELECT '12.34'::float8::numeric::money;

-- datatype.sgml:1107
SELECT '52093.89'::money::numeric::float8;

-- datatype.sgml:1502
SET bytea_output = 'hex';

-- datatype.sgml:1502
SELECT '\xDEADBEEF'::bytea;

-- datatype.sgml:1637
SET bytea_output = 'escape';

-- datatype.sgml:1637
SELECT 'abc \153\154\155 \052\251\124'::bytea;

-- datatype.sgml:2895
SELECT '2 years 15 months 100 weeks 99 hours 123456789 milliseconds'::interval;

-- datatype.sgml:3153
CREATE TABLE test1 (a boolean, b text);

-- datatype.sgml:3153
INSERT INTO test1 VALUES (TRUE, 'sic est');

-- datatype.sgml:3153
INSERT INTO test1 VALUES (FALSE, 'non est');

-- datatype.sgml:3153
SELECT * FROM test1;

-- datatype.sgml:3153
SELECT * FROM test1 WHERE a;

-- datatype.sgml:3221
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

-- datatype.sgml:3227
CREATE TABLE person (
    name text,
    current_mood mood
);

-- datatype.sgml:3227
INSERT INTO person VALUES ('Moe', 'happy');

-- datatype.sgml:3227
SELECT * FROM person WHERE current_mood = 'happy';

-- datatype.sgml:3252
INSERT INTO person VALUES ('Larry', 'sad');

-- datatype.sgml:3252
INSERT INTO person VALUES ('Curly', 'ok');

-- datatype.sgml:3252
SELECT * FROM person WHERE current_mood > 'sad';

-- datatype.sgml:3252
SELECT * FROM person WHERE current_mood > 'sad' ORDER BY current_mood;

-- datatype.sgml:3252
SELECT name
FROM person
WHERE current_mood = (SELECT MIN(current_mood) FROM person);

-- datatype.sgml:3287
CREATE TYPE happiness AS ENUM ('happy', 'very happy', 'ecstatic');

-- datatype.sgml:3287
CREATE TABLE holidays (
    num_weeks integer,
    happiness happiness
);

-- datatype.sgml:3287
INSERT INTO holidays(num_weeks,happiness) VALUES (4, 'happy');

-- datatype.sgml:3287
INSERT INTO holidays(num_weeks,happiness) VALUES (6, 'very happy');

-- datatype.sgml:3287
INSERT INTO holidays(num_weeks,happiness) VALUES (8, 'ecstatic');

-- datatype.sgml:3287
INSERT INTO holidays(num_weeks,happiness) VALUES (2, 'sad');

-- datatype.sgml:3308
SELECT person.name, holidays.num_weeks FROM person, holidays
  WHERE person.current_mood::text = holidays.happiness::text;

-- datatype.sgml:4183
SELECT 'a fat cat sat on a mat and ate a fat rat'::tsvector;

-- datatype.sgml:4193
SELECT $$the lexeme '    ' contains spaces$$::tsvector;

-- datatype.sgml:4204
SELECT $$the lexeme 'Joe''s' contains a quote$$::tsvector;

-- datatype.sgml:4234
SELECT 'a:1A fat:2B,4C cat:5D'::tsvector;

-- datatype.sgml:4253
SELECT 'The Fat Rats'::tsvector;

-- datatype.sgml:4266
SELECT to_tsvector('english', 'The Fat Rats');

-- datatype.sgml:4308
SELECT 'fat & rat'::tsquery;

-- datatype.sgml:4308
SELECT 'fat & (rat | cat)'::tsquery;

-- datatype.sgml:4308
SELECT 'fat & rat & ! cat'::tsquery;

-- datatype.sgml:4331
SELECT 'fat:ab & cat'::tsquery;

-- datatype.sgml:4342
SELECT 'super:*'::tsquery;

-- datatype.sgml:4359
SELECT to_tsquery('Fat:ab & Cats');

-- datatype.sgml:4369
SELECT to_tsvector( 'postgraduate' ) @@ to_tsquery( 'postgres:*' );

-- datatype.sgml:4376
SELECT to_tsvector( 'postgraduate' ), to_tsquery( 'postgres:*' );

-- datatype.sgml:4700
CREATE DOMAIN posint AS integer CHECK (VALUE > 0);

-- datatype.sgml:4700
CREATE TABLE mytable (id posint);

-- datatype.sgml:4700
INSERT INTO mytable VALUES(1);   -- works

-- datatype.sgml:4700
INSERT INTO mytable VALUES(-1);  -- fails

-- datatype.sgml:4848
SELECT * FROM pg_attribute WHERE attrelid = 'mytable'::regclass;

-- datatype.sgml:4852
SELECT * FROM pg_attribute
  WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'mytable');
