-- Generated by script/extract-doc-sql.js from doc/src/sgml/datetime.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- datetime.sgml:196
SELECT '2018-03-11 02:30'::timestamptz;

-- datetime.sgml:212
SELECT '2018-11-04 01:30'::timestamptz;

-- datetime.sgml:225
SELECT '2018-11-04 01:30 EDT'::timestamptz;

-- datetime.sgml:944
SELECT extract(julian FROM '2021-06-23 7:00:00-04'::timestamptz AT TIME ZONE 'UTC+12');

-- datetime.sgml:944
SELECT extract(julian FROM '2021-06-23 8:00:00-04'::timestamptz AT TIME ZONE 'UTC+12');

-- datetime.sgml:944
SELECT extract(julian FROM date '2021-06-23');
