-- Generated by script/extract-doc-sql.js from doc/src/sgml/dblink.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- dblink.sgml:186
SELECT dblink_connect('dbname=postgres options=-csearch_path=');

-- dblink.sgml:186
SELECT dblink_connect('myconn', 'dbname=postgres options=-csearch_path=');

-- dblink.sgml:186
CREATE SERVER fdtest FOREIGN DATA WRAPPER dblink_fdw OPTIONS (hostaddr '127.0.0.1', dbname 'contrib_regression');

-- dblink.sgml:186
CREATE USER regress_dblink_user WITH PASSWORD 'secret';

-- dblink.sgml:186
CREATE USER MAPPING FOR regress_dblink_user SERVER fdtest OPTIONS (user 'regress_dblink_user', password 'secret');

-- dblink.sgml:186
GRANT USAGE ON FOREIGN SERVER fdtest TO regress_dblink_user;

-- dblink.sgml:186
GRANT SELECT ON TABLE foo TO regress_dblink_user;

-- dblink.sgml:186
SELECT dblink_connect('myconn', 'fdtest');

-- dblink.sgml:186
SELECT * FROM dblink('myconn', 'SELECT * FROM foo') AS t(a int, b text, c text[]);

-- dblink.sgml:186
REVOKE USAGE ON FOREIGN SERVER fdtest FROM regress_dblink_user;

-- dblink.sgml:186
REVOKE SELECT ON TABLE foo FROM regress_dblink_user;

-- dblink.sgml:186
DROP USER MAPPING FOR regress_dblink_user SERVER fdtest;

-- dblink.sgml:186
DROP USER regress_dblink_user;

-- dblink.sgml:186
DROP SERVER fdtest;

-- dblink.sgml:364
SELECT dblink_disconnect();

-- dblink.sgml:364
SELECT dblink_disconnect('myconn');

-- dblink.sgml:480
SELECT *
    FROM dblink('dbname=mydb options=-csearch_path=',
                'SELECT proname, prosrc FROM pg_proc')
      AS t1(proname name, prosrc text)
    WHERE proname LIKE 'bytea%';

-- dblink.sgml:514
CREATE VIEW myremote_pg_proc AS
  SELECT *
    FROM dblink('dbname=postgres options=-csearch_path=',
                'SELECT proname, prosrc FROM pg_proc')
    AS t1(proname name, prosrc text);

-- dblink.sgml:514
SELECT * FROM myremote_pg_proc WHERE proname LIKE 'bytea%';

-- dblink.sgml:528
SELECT * FROM dblink('dbname=postgres options=-csearch_path=',
                     'SELECT proname, prosrc FROM pg_proc')
  AS t1(proname name, prosrc text) WHERE proname LIKE 'bytea%';

-- dblink.sgml:528
SELECT * FROM dblink('SELECT proname, prosrc FROM pg_proc')
  AS t1(proname name, prosrc text) WHERE proname LIKE 'bytea%';

-- dblink.sgml:528
SELECT dblink_connect('myconn', 'dbname=regression options=-csearch_path=');

-- dblink.sgml:528
SELECT * FROM dblink('myconn', 'SELECT proname, prosrc FROM pg_proc')
  AS t1(proname name, prosrc text) WHERE proname LIKE 'bytea%';

-- dblink.sgml:701
SELECT dblink_connect('dbname=dblink_test_standby');

-- dblink.sgml:701
SELECT dblink_exec('insert into foo values(21, ''z'', ''{"a0","b0","c0"}'');');

-- dblink.sgml:701
SELECT dblink_connect('myconn', 'dbname=regression');

-- dblink.sgml:701
SELECT dblink_exec('myconn', 'insert into foo values(21, ''z'', ''{"a0","b0","c0"}'');');

-- dblink.sgml:701
SELECT dblink_exec('myconn', 'insert into pg_class values (''foo'')',false);

-- dblink.sgml:846
SELECT dblink_open('foo', 'SELECT proname, prosrc FROM pg_proc');

-- dblink.sgml:967
SELECT dblink_open('foo', 'SELECT proname, prosrc FROM pg_proc WHERE proname LIKE ''bytea%''');

-- dblink.sgml:967
SELECT * FROM dblink_fetch('foo', 5) AS (funcname name, source text);

-- dblink.sgml:1104
SELECT dblink_close('foo');

-- dblink.sgml:1165
SELECT dblink_get_connections();

-- dblink.sgml:1242
SELECT dblink_error_message('dtest1');

-- dblink.sgml:1324
SELECT dblink_send_query('dtest1', 'SELECT * FROM foo WHERE f1 < 3');

-- dblink.sgml:1387
SELECT dblink_is_busy('dtest1');

-- dblink.sgml:1451
SELECT dblink_exec('LISTEN virtual');

-- dblink.sgml:1451
SELECT * FROM dblink_get_notify();

-- dblink.sgml:1451
NOTIFY virtual;

-- dblink.sgml:1580
SELECT dblink_connect('dtest1', 'dbname=contrib_regression');

-- dblink.sgml:1580
SELECT * FROM
dblink_send_query('dtest1', 'SELECT * FROM foo WHERE f1 < 3') AS t1;

-- dblink.sgml:1580
SELECT * FROM dblink_get_result('dtest1') AS t1(f1 int, f2 text, f3 text[]);

-- dblink.sgml:1580
SELECT * FROM
dblink_send_query('dtest1', 'SELECT * FROM foo WHERE f1 < 3; SELECT * FROM foo WHERE f1 > 6') AS t1;

-- dblink.sgml:1701
SELECT dblink_cancel_query('dtest1');

-- dblink.sgml:1766
CREATE TYPE dblink_pkey_results AS (position int, colname text);

-- dblink.sgml:1779
CREATE TABLE foobar (
    f1 int,
    f2 int,
    f3 int,
    PRIMARY KEY (f1, f2, f3)
);

-- dblink.sgml:1779
SELECT * FROM dblink_get_pkey('foobar');

-- dblink.sgml:1924
SELECT dblink_build_sql_insert('foo', '1 2', 2, '{"1", "a"}', '{"1", "b''a"}');

-- dblink.sgml:2042
SELECT dblink_build_sql_delete('"MyFoo"', '1 2', 2, '{"1", "b"}');

-- dblink.sgml:2179
SELECT dblink_build_sql_update('foo', '1 2', 2, '{"1", "a"}', '{"1", "b"}');
