-- Generated by script/extract-doc-sql.js from doc/src/sgml/ddl.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ddl.sgml:86
CREATE TABLE my_first_table (
    first_column text,
    second_column integer
);

-- ddl.sgml:108
CREATE TABLE products (
    product_no integer,
    name text,
    price numeric
);

-- ddl.sgml:144
DROP TABLE my_first_table;

-- ddl.sgml:144
DROP TABLE products;

-- ddl.sgml:273
INSERT INTO people (name, address) VALUES ('A', 'foo');

-- ddl.sgml:273
INSERT INTO people (name, address) VALUES ('B', 'bar');

-- ddl.sgml:682
CREATE TABLE products (
    product_no integer,
    name text,
    price numeric,
    CHECK (price > 0),
    discounted_price numeric,
    CHECK (discounted_price > 0),
    CHECK (price > discounted_price)
);

-- ddl.sgml:694
CREATE TABLE products (
    product_no integer,
    name text,
    price numeric CHECK (price > 0),
    discounted_price numeric,
    CHECK (discounted_price > 0 AND price > discounted_price)
);

-- ddl.sgml:849
CREATE TABLE products (
    product_no integer NOT NULL,
    name text NOT NULL,
    price numeric NOT NULL CHECK (price > 0)
);

-- ddl.sgml:875
CREATE TABLE products (
    product_no integer NULL,
    name text NULL,
    price numeric NULL
);

-- ddl.sgml:1019
CREATE TABLE products (
    product_no integer UNIQUE NOT NULL,
    name text,
    price numeric
);

-- ddl.sgml:1103
CREATE TABLE products (
    product_no integer PRIMARY KEY,
    name text,
    price numeric
);

-- ddl.sgml:1198
CREATE TABLE order_items (
    product_no integer REFERENCES products,
    order_id integer REFERENCES orders,
    quantity integer,
    PRIMARY KEY (product_no, order_id)
);

-- ddl.sgml:1429
CREATE TABLE circles (
    c circle,
    EXCLUDE USING gist (c WITH &&)
);

-- ddl.sgml:1788
CREATE TABLE variants (
  id         integer,
  product_no integer,
  name       text,
  valid_at   daterange,
  PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)
);

-- ddl.sgml:1956
ALTER TABLE products ADD COLUMN description text;

-- ddl.sgml:1987
ALTER TABLE products ADD COLUMN description text CHECK (description <> '');

-- ddl.sgml:2010
ALTER TABLE products DROP COLUMN description;

-- ddl.sgml:2019
ALTER TABLE products DROP COLUMN description CASCADE;

-- ddl.sgml:2037
ALTER TABLE products ADD CHECK (name <> '');

-- ddl.sgml:2037
ALTER TABLE products ADD CONSTRAINT some_name UNIQUE (product_no);

-- ddl.sgml:2037
ALTER TABLE products ADD FOREIGN KEY (product_group_id) REFERENCES product_groups;

-- ddl.sgml:2047
ALTER TABLE products ALTER COLUMN product_no SET NOT NULL;

-- ddl.sgml:2076
ALTER TABLE products DROP CONSTRAINT some_name;

-- ddl.sgml:2090
ALTER TABLE products ALTER COLUMN product_no DROP NOT NULL;

-- ddl.sgml:2111
ALTER TABLE products ALTER COLUMN price SET DEFAULT 7.77;

-- ddl.sgml:2120
ALTER TABLE products ALTER COLUMN price DROP DEFAULT;

-- ddl.sgml:2140
ALTER TABLE products ALTER COLUMN price TYPE numeric(10,2);

-- ddl.sgml:2169
ALTER TABLE products RENAME COLUMN product_no TO product_number;

-- ddl.sgml:2185
ALTER TABLE products RENAME TO items;

-- ddl.sgml:2273
GRANT UPDATE ON accounts TO joe;

-- ddl.sgml:2291
REVOKE ALL ON accounts FROM PUBLIC;

-- ddl.sgml:2854
GRANT SELECT ON mytable TO PUBLIC;

-- ddl.sgml:2854
GRANT SELECT, UPDATE, INSERT ON mytable TO admin;

-- ddl.sgml:2854
GRANT SELECT (col1), UPDATE (col1) ON mytable TO miriam_rw;

-- ddl.sgml:3013
CREATE TABLE accounts (manager text, company text, contact_email text);

-- ddl.sgml:3013
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;

-- ddl.sgml:3013
CREATE POLICY account_managers ON accounts TO managers
    USING (manager = current_user);

-- ddl.sgml:3040
CREATE POLICY user_policy ON users
    USING (user_name = current_user);

-- ddl.sgml:3056
CREATE POLICY user_sel_policy ON users
    FOR SELECT
    USING (true);

-- ddl.sgml:3056
CREATE POLICY user_mod_policy ON users
    USING (user_name = current_user);

-- ddl.sgml:3085
CREATE TABLE passwd (
  user_name             text UNIQUE NOT NULL,
  pwhash                text,
  uid                   int  PRIMARY KEY,
  gid                   int  NOT NULL,
  real_name             text NOT NULL,
  home_phone            text,
  extra_info            text,
  home_dir              text NOT NULL,
  shell                 text NOT NULL
);

-- ddl.sgml:3085
CREATE ROLE admin;  -- Administrator

-- ddl.sgml:3085
CREATE ROLE bob;    -- Normal user

-- ddl.sgml:3085
CREATE ROLE alice;  -- Normal user

-- ddl.sgml:3085
INSERT INTO passwd VALUES
  ('admin','xxx',0,0,'Admin','111-222-3333',null,'/root','/bin/dash');

-- ddl.sgml:3085
INSERT INTO passwd VALUES
  ('bob','xxx',1,1,'Bob','123-456-7890',null,'/home/bob','/bin/zsh');

-- ddl.sgml:3085
INSERT INTO passwd VALUES
  ('alice','xxx',2,1,'Alice','098-765-4321',null,'/home/alice','/bin/zsh');

-- ddl.sgml:3085
ALTER TABLE passwd ENABLE ROW LEVEL SECURITY;

-- ddl.sgml:3085
CREATE POLICY admin_all ON passwd TO admin USING (true) WITH CHECK (true);

-- ddl.sgml:3085
CREATE POLICY all_view ON passwd FOR SELECT USING (true);

-- ddl.sgml:3085
CREATE POLICY user_mod ON passwd FOR UPDATE
  USING (current_user = user_name)
  WITH CHECK (
    current_user = user_name AND
    shell IN ('/bin/bash','/bin/sh','/bin/dash','/bin/zsh','/bin/tcsh')
  );

-- ddl.sgml:3085
GRANT SELECT, INSERT, UPDATE, DELETE ON passwd TO admin;

-- ddl.sgml:3085
GRANT SELECT
  (user_name, uid, gid, real_name, home_phone, extra_info, home_dir, shell)
  ON passwd TO public;

-- ddl.sgml:3085
GRANT UPDATE
  (pwhash, real_name, home_phone, extra_info, shell)
  ON passwd TO public;

-- ddl.sgml:3146
SET ROLE admin;

-- ddl.sgml:3146
TABLE passwd;

-- ddl.sgml:3146
SET ROLE alice;

-- ddl.sgml:3146
UPDATE passwd SET user_name = 'joe';

-- ddl.sgml:3201
CREATE POLICY admin_local_only ON passwd AS RESTRICTIVE TO admin
    USING (pg_catalog.inet_client_addr() IS NULL);

-- ddl.sgml:3211
SELECT current_user;

-- ddl.sgml:3211
SELECT inet_client_addr();

-- ddl.sgml:3211
UPDATE passwd SET pwhash = NULL;

-- ddl.sgml:3265
CREATE TABLE groups (group_id int PRIMARY KEY,
                     group_name text NOT NULL);

-- ddl.sgml:3265
INSERT INTO groups VALUES
  (1, 'low'),
  (2, 'medium'),
  (5, 'high');

-- ddl.sgml:3265
GRANT ALL ON groups TO alice;  -- alice is the administrator

-- ddl.sgml:3265
GRANT SELECT ON groups TO public;

-- ddl.sgml:3265
CREATE TABLE users (user_name text PRIMARY KEY,
                    group_id int NOT NULL REFERENCES groups);

-- ddl.sgml:3265
INSERT INTO users VALUES
  ('alice', 5),
  ('bob', 2),
  ('mallory', 2);

-- ddl.sgml:3265
GRANT ALL ON users TO alice;

-- ddl.sgml:3265
GRANT SELECT ON users TO public;

-- ddl.sgml:3265
CREATE TABLE information (info text,
                          group_id int NOT NULL REFERENCES groups);

-- ddl.sgml:3265
INSERT INTO information VALUES
  ('barely secret', 1),
  ('slightly secret', 2),
  ('very secret', 5);

-- ddl.sgml:3265
ALTER TABLE information ENABLE ROW LEVEL SECURITY;

-- ddl.sgml:3265
CREATE POLICY fp_s ON information FOR SELECT
  USING (group_id <= (SELECT group_id FROM users WHERE user_name = current_user));

-- ddl.sgml:3265
CREATE POLICY fp_u ON information FOR UPDATE
  USING (group_id <= (SELECT group_id FROM users WHERE user_name = current_user));

-- ddl.sgml:3265
GRANT ALL ON information TO public;

-- ddl.sgml:3318
UPDATE users SET group_id = 1 WHERE user_name = 'mallory';

-- ddl.sgml:3318
UPDATE information SET info = 'secret from mallory' WHERE group_id = 2;

-- ddl.sgml:3330
SELECT * FROM information WHERE group_id = 2 FOR UPDATE;

-- ddl.sgml:3458
CREATE SCHEMA myschema;

-- ddl.sgml:3513
DROP SCHEMA myschema;

-- ddl.sgml:3517
DROP SCHEMA myschema CASCADE;

-- ddl.sgml:3625
SHOW search_path;

-- ddl.sgml:3653
SET search_path TO myschema,public;

-- ddl.sgml:3659
DROP TABLE mytable;

-- ddl.sgml:3668
SET search_path TO myschema;

-- ddl.sgml:3691
SELECT 3 OPERATOR(pg_catalog.+) 4;

-- ddl.sgml:3724
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- ddl.sgml:3922
CREATE TABLE cities (
    name            text,
    population      float,
    elevation       int     -- in feet
);

-- ddl.sgml:3922
CREATE TABLE capitals (
    state           char(2)
) INHERITS (cities);

-- ddl.sgml:3949
SELECT name, elevation
    FROM cities
    WHERE elevation > 500;

-- ddl.sgml:3997
SELECT name, elevation
    FROM cities*
    WHERE elevation > 500;

-- ddl.sgml:4014
SELECT c.tableoid, c.name, c.elevation
FROM cities c
WHERE c.elevation > 500;

-- ddl.sgml:4034
SELECT p.relname, c.name, c.elevation
FROM cities c, pg_class p
WHERE c.elevation > 500 AND c.tableoid = p.oid;

-- ddl.sgml:4055
SELECT c.tableoid::regclass, c.name, c.elevation
FROM cities c
WHERE c.elevation > 500;

-- ddl.sgml:4067
INSERT INTO cities (name, population, elevation, state)
VALUES ('Albany', NULL, NULL, 'NY');

-- ddl.sgml:4453
CREATE TABLE measurement (
    city_id         int not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
);

-- ddl.sgml:4482
CREATE TABLE measurement (
    city_id         int not null,
    logdate         date not null,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (logdate);

-- ddl.sgml:4514
CREATE TABLE measurement_y2006m02 PARTITION OF measurement
    FOR VALUES FROM ('2006-02-01') TO ('2006-03-01');

-- ddl.sgml:4514
CREATE TABLE measurement_y2006m03 PARTITION OF measurement
    FOR VALUES FROM ('2006-03-01') TO ('2006-04-01');

-- ddl.sgml:4514
CREATE TABLE measurement_y2007m11 PARTITION OF measurement
    FOR VALUES FROM ('2007-11-01') TO ('2007-12-01');

-- ddl.sgml:4514
CREATE TABLE measurement_y2007m12 PARTITION OF measurement
    FOR VALUES FROM ('2007-12-01') TO ('2008-01-01')
    TABLESPACE fasttablespace;

-- ddl.sgml:4514
CREATE TABLE measurement_y2008m01 PARTITION OF measurement
    FOR VALUES FROM ('2008-01-01') TO ('2008-02-01')
    WITH (parallel_workers = 4)
    TABLESPACE fasttablespace;

-- ddl.sgml:4544
CREATE TABLE measurement_y2006m02 PARTITION OF measurement
    FOR VALUES FROM ('2006-02-01') TO ('2006-03-01')
    PARTITION BY RANGE (peaktemp);

-- ddl.sgml:4590
CREATE INDEX ON measurement (logdate);

-- ddl.sgml:4629
DROP TABLE measurement_y2006m02;

-- ddl.sgml:4643
ALTER TABLE measurement DETACH PARTITION measurement_y2006m02;

-- ddl.sgml:4643
ALTER TABLE measurement DETACH PARTITION measurement_y2006m02 CONCURRENTLY;

-- ddl.sgml:4667
CREATE TABLE measurement_y2008m02 PARTITION OF measurement
    FOR VALUES FROM ('2008-02-01') TO ('2008-03-01')
    TABLESPACE fasttablespace;

-- ddl.sgml:4688
CREATE TABLE measurement_y2008m02
  (LIKE measurement INCLUDING DEFAULTS INCLUDING CONSTRAINTS)
  TABLESPACE fasttablespace;

-- ddl.sgml:4688
ALTER TABLE measurement_y2008m02 ADD CONSTRAINT y2008m02
   CHECK ( logdate >= DATE '2008-02-01' AND logdate < DATE '2008-03-01' );

-- ddl.sgml:4688
ALTER TABLE measurement ATTACH PARTITION measurement_y2008m02
    FOR VALUES FROM ('2008-02-01') TO ('2008-03-01' );

-- ddl.sgml:4749
CREATE INDEX measurement_usls_idx ON ONLY measurement (unitsales);

-- ddl.sgml:4749
CREATE INDEX CONCURRENTLY measurement_usls_200602_idx
    ON measurement_y2006m02 (unitsales);

-- ddl.sgml:4749
ALTER INDEX measurement_usls_idx
    ATTACH PARTITION measurement_usls_200602_idx;

-- ddl.sgml:4762
ALTER TABLE ONLY measurement ADD UNIQUE (city_id, logdate);

-- ddl.sgml:4762
ALTER TABLE measurement_y2006m02 ADD UNIQUE (city_id, logdate);

-- ddl.sgml:4762
ALTER INDEX measurement_city_id_logdate_key
    ATTACH PARTITION measurement_y2006m02_city_id_logdate_key;

-- ddl.sgml:4966
CREATE TABLE measurement_y2006m02 () INHERITS (measurement);

-- ddl.sgml:4966
CREATE TABLE measurement_y2006m03 () INHERITS (measurement);

-- ddl.sgml:4966
CREATE TABLE measurement_y2007m11 () INHERITS (measurement);

-- ddl.sgml:4966
CREATE TABLE measurement_y2007m12 () INHERITS (measurement);

-- ddl.sgml:4966
CREATE TABLE measurement_y2008m01 () INHERITS (measurement);

-- ddl.sgml:5001
CREATE TABLE measurement_y2006m02 (
    CHECK ( logdate >= DATE '2006-02-01' AND logdate < DATE '2006-03-01' )
) INHERITS (measurement);

-- ddl.sgml:5001
CREATE TABLE measurement_y2006m03 (
    CHECK ( logdate >= DATE '2006-03-01' AND logdate < DATE '2006-04-01' )
) INHERITS (measurement);

-- ddl.sgml:5001
CREATE TABLE measurement_y2007m11 (
    CHECK ( logdate >= DATE '2007-11-01' AND logdate < DATE '2007-12-01' )
) INHERITS (measurement);

-- ddl.sgml:5001
CREATE TABLE measurement_y2007m12 (
    CHECK ( logdate >= DATE '2007-12-01' AND logdate < DATE '2008-01-01' )
) INHERITS (measurement);

-- ddl.sgml:5001
CREATE TABLE measurement_y2008m01 (
    CHECK ( logdate >= DATE '2008-01-01' AND logdate < DATE '2008-02-01' )
) INHERITS (measurement);

-- ddl.sgml:5030
CREATE INDEX measurement_y2006m02_logdate ON measurement_y2006m02 (logdate);

-- ddl.sgml:5030
CREATE INDEX measurement_y2006m03_logdate ON measurement_y2006m03 (logdate);

-- ddl.sgml:5030
CREATE INDEX measurement_y2007m11_logdate ON measurement_y2007m11 (logdate);

-- ddl.sgml:5030
CREATE INDEX measurement_y2007m12_logdate ON measurement_y2007m12 (logdate);

-- ddl.sgml:5030
CREATE INDEX measurement_y2008m01_logdate ON measurement_y2008m01 (logdate);

-- ddl.sgml:5049
CREATE OR REPLACE FUNCTION measurement_insert_trigger()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO measurement_y2008m01 VALUES (NEW.*);
    RETURN NULL;
END;
$$
LANGUAGE plpgsql;

-- ddl.sgml:5065
CREATE TRIGGER insert_measurement_trigger
    BEFORE INSERT ON measurement
    FOR EACH ROW EXECUTE FUNCTION measurement_insert_trigger();

-- ddl.sgml:5129
CREATE RULE measurement_insert_y2006m02 AS
ON INSERT TO measurement WHERE
    ( logdate >= DATE '2006-02-01' AND logdate < DATE '2006-03-01' )
DO INSTEAD
    INSERT INTO measurement_y2006m02 VALUES (NEW.*);

-- ddl.sgml:5129
CREATE RULE measurement_insert_y2008m01 AS
ON INSERT TO measurement WHERE
    ( logdate >= DATE '2008-01-01' AND logdate < DATE '2008-02-01' )
DO INSTEAD
    INSERT INTO measurement_y2008m01 VALUES (NEW.*);

-- ddl.sgml:5197
ALTER TABLE measurement_y2006m02 NO INHERIT measurement;

-- ddl.sgml:5206
CREATE TABLE measurement_y2008m02 (
    CHECK ( logdate >= DATE '2008-02-01' AND logdate < DATE '2008-03-01' )
) INHERITS (measurement);

-- ddl.sgml:5217
CREATE TABLE measurement_y2008m02
  (LIKE measurement INCLUDING DEFAULTS INCLUDING CONSTRAINTS);

-- ddl.sgml:5217
ALTER TABLE measurement_y2008m02 INHERIT measurement;

-- ddl.sgml:5272
ANALYZE ONLY measurement;

-- ddl.sgml:5314
SET enable_partition_pruning = on;                 -- the default

-- ddl.sgml:5314
SELECT count(*) FROM measurement WHERE logdate >= DATE '2008-01-01';

-- ddl.sgml:5758
DROP TABLE products CASCADE;

-- ddl.sgml:5807
CREATE TYPE rainbow AS ENUM ('red', 'orange', 'yellow',
                             'green', 'blue', 'purple');

-- ddl.sgml:5807
CREATE TABLE my_colors (color rainbow, note text);

-- ddl.sgml:5807
CREATE FUNCTION get_color_note (rainbow) RETURNS text AS
  'SELECT note FROM my_colors WHERE color = $1'
  LANGUAGE SQL;

-- ddl.sgml:5837
CREATE FUNCTION get_color_note (rainbow) RETURNS text
BEGIN ATOMIC
  SELECT note FROM my_colors WHERE color = $1;
END;
