-- Generated by script/extract-doc-sql.js from doc/src/sgml/dict-int.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- dict-int.sgml:93
ALTER TEXT SEARCH CONFIGURATION english
    ALTER MAPPING FOR int, uint WITH intdict;
