-- Generated by script/extract-doc-sql.js from doc/src/sgml/dict-xsyn.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- dict-xsyn.sgml:106
SELECT ts_lexize('xsyn', 'word');

-- dict-xsyn.sgml:106
SELECT ts_lexize('xsyn', 'syn1');

-- dict-xsyn.sgml:141
ALTER TEXT SEARCH CONFIGURATION english
    ALTER MAPPING FOR word, asciiword WITH xsyn, english_stem;
