-- Generated by script/extract-doc-sql.js from doc/src/sgml/dml.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- dml.sgml:48
INSERT INTO products VALUES (1, 'Cheese', 9.99);

-- dml.sgml:61
INSERT INTO products (product_no, name, price) VALUES (1, 'Cheese', 9.99);

-- dml.sgml:61
INSERT INTO products (name, price, product_no) VALUES ('Cheese', 9.99, 1);

-- dml.sgml:73
INSERT INTO products (product_no, name) VALUES (1, 'Cheese');

-- dml.sgml:73
INSERT INTO products VALUES (1, 'Cheese');

-- dml.sgml:85
INSERT INTO products (product_no, name, price) VALUES (1, 'Cheese', DEFAULT);

-- dml.sgml:85
INSERT INTO products DEFAULT VALUES;

-- dml.sgml:93
INSERT INTO products (product_no, name, price) VALUES
    (1, 'Cheese', 9.99),
    (2, 'Bread', 1.99),
    (3, 'Milk', 2.99);

-- dml.sgml:104
INSERT INTO products (product_no, name, price)
  SELECT product_no, name, price FROM new_products
    WHERE release_date = 'today';

-- dml.sgml:177
UPDATE products SET price = 10 WHERE price = 5;

-- dml.sgml:193
UPDATE products SET price = price * 1.10;

-- dml.sgml:214
UPDATE mytable SET a = 5, b = 3, c = 1 WHERE a > 0;

-- dml.sgml:250
DELETE FROM products WHERE price = 10;

-- dml.sgml:257
DELETE FROM products;

-- dml.sgml:319
CREATE TABLE users (firstname text, lastname text, id serial PRIMARY KEY);

-- dml.sgml:319
INSERT INTO users (firstname, lastname) VALUES ('Joe', 'Cool') RETURNING id;

-- dml.sgml:332
UPDATE products SET price = price * 1.10
  WHERE price <= 99.99
  RETURNING name, price AS new_price;

-- dml.sgml:343
DELETE FROM products
  WHERE obsoletion_date = 'today'
  RETURNING *;

-- dml.sgml:358
MERGE INTO products p USING new_products n ON p.product_no = n.product_no
  WHEN NOT MATCHED THEN INSERT VALUES (n.product_no, n.name, n.price)
  WHEN MATCHED THEN UPDATE SET name = n.name, price = n.price
  RETURNING p.*;

-- dml.sgml:369
UPDATE products SET price = price * 1.10
  WHERE price <= 99.99
  RETURNING name, old.price AS old_price, new.price AS new_price,
            new.price - old.price AS price_change;
