-- Generated by script/extract-doc-sql.js from doc/src/sgml/ecpg.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ecpg.sgml:530
SELECT number, ascii FROM foo
    ORDER BY ascii;

-- ecpg.sgml:1591
CREATE TABLE t3 (
    ii integer[]
);

-- ecpg.sgml:1591
SELECT * FROM t3;

-- ecpg.sgml:1701
CREATE TYPE comp_t AS (intval integer, textval varchar(32));

-- ecpg.sgml:1701
CREATE TABLE t4 (compval comp_t);

-- ecpg.sgml:1701
INSERT INTO t4 VALUES ( (256, 'PostgreSQL') );

-- ecpg.sgml:1869
CREATE FUNCTION create_complex(r double, i double) RETURNS complex
LANGUAGE SQL
IMMUTABLE
AS $$ SELECT $1 * complex '(1,0')' + $2 * complex '(0,1)' $$;
