-- Generated by script/extract-doc-sql.js from doc/src/sgml/extend.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- extend.sgml:1043
CREATE TABLE my_config (key text, value text);

-- extend.sgml:1043
CREATE SEQUENCE my_config_seq;

-- extend.sgml:1043
SELECT pg_catalog.pg_extension_config_dump('my_config', '');

-- extend.sgml:1043
SELECT pg_catalog.pg_extension_config_dump('my_config_seq', '');

-- extend.sgml:1064
CREATE TABLE my_config (key text, value text, standard_entry boolean);

-- extend.sgml:1064
SELECT pg_catalog.pg_extension_config_dump('my_config', 'WHERE NOT standard_entry');
