-- Generated by script/extract-doc-sql.js from doc/src/sgml/file-fdw.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- file-fdw.sgml:272
CREATE EXTENSION file_fdw;

-- file-fdw.sgml:279
CREATE SERVER pglog FOREIGN DATA WRAPPER file_fdw;

-- file-fdw.sgml:289
CREATE FOREIGN TABLE pglog (
  log_time timestamp(3) with time zone,
  user_name text,
  database_name text,
  process_id integer,
  connection_from text,
  session_id text,
  session_line_num bigint,
  command_tag text,
  session_start_time timestamp with time zone,
  virtual_transaction_id text,
  transaction_id bigint,
  error_severity text,
  sql_state_code text,
  message text,
  detail text,
  hint text,
  internal_query text,
  internal_query_pos integer,
  context text,
  query text,
  query_pos integer,
  location text,
  application_name text,
  backend_type text,
  leader_pid integer,
  query_id bigint
) SERVER pglog
OPTIONS ( filename 'log/pglog.csv', format 'csv' );

-- file-fdw.sgml:334
CREATE FOREIGN TABLE films (
 code char(5) NOT NULL,
 title text NOT NULL,
 rating text OPTIONS (force_null 'true')
) SERVER film_server
OPTIONS ( filename 'films/db.csv', format 'csv' );
