-- Generated by script/extract-doc-sql.js from doc/src/sgml/fuzzystrmatch.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- fuzzystrmatch.sgml:73
SELECT soundex('hello world!');

-- fuzzystrmatch.sgml:73
SELECT soundex('Anne'), soundex('Ann'), difference('Anne', 'Ann');

-- fuzzystrmatch.sgml:73
SELECT soundex('Anne'), soundex('Andrew'), difference('Anne', 'Andrew');

-- fuzzystrmatch.sgml:73
SELECT soundex('Anne'), soundex('Margaret'), difference('Anne', 'Margaret');

-- fuzzystrmatch.sgml:73
CREATE TABLE s (nm text);

-- fuzzystrmatch.sgml:73
INSERT INTO s VALUES ('john');

-- fuzzystrmatch.sgml:73
INSERT INTO s VALUES ('joan');

-- fuzzystrmatch.sgml:73
INSERT INTO s VALUES ('wobbly');

-- fuzzystrmatch.sgml:73
INSERT INTO s VALUES ('jack');

-- fuzzystrmatch.sgml:73
SELECT * FROM s WHERE soundex(nm) = soundex('john');

-- fuzzystrmatch.sgml:73
SELECT * FROM s WHERE difference(s.nm, 'john') > 2;

-- fuzzystrmatch.sgml:156
SELECT daitch_mokotoff('George');

-- fuzzystrmatch.sgml:156
SELECT daitch_mokotoff('John');

-- fuzzystrmatch.sgml:156
SELECT daitch_mokotoff('Bierschbach');

-- fuzzystrmatch.sgml:156
SELECT daitch_mokotoff('Schwartzenegger');

-- fuzzystrmatch.sgml:185
CREATE INDEX ix_s_dm ON s USING gin (daitch_mokotoff(nm)) WITH (fastupdate = off);

-- fuzzystrmatch.sgml:185
INSERT INTO s (nm) VALUES
  ('Schwartzenegger'),
  ('John'),
  ('James'),
  ('Steinman'),
  ('Steinmetz');

-- fuzzystrmatch.sgml:185
SELECT * FROM s WHERE daitch_mokotoff(nm) && daitch_mokotoff('Swartzenegger');

-- fuzzystrmatch.sgml:185
SELECT * FROM s WHERE daitch_mokotoff(nm) && daitch_mokotoff('Jane');

-- fuzzystrmatch.sgml:185
SELECT * FROM s WHERE daitch_mokotoff(nm) && daitch_mokotoff('Jens');

-- fuzzystrmatch.sgml:207
CREATE FUNCTION soundex_tsvector(v_name text) RETURNS tsvector
BEGIN ATOMIC
  SELECT to_tsvector('simple',
                     string_agg(array_to_string(daitch_mokotoff(n), ' '), ' '))
  FROM regexp_split_to_table(v_name, '\s+') AS n;
END;

-- fuzzystrmatch.sgml:207
CREATE FUNCTION soundex_tsquery(v_name text) RETURNS tsquery
BEGIN ATOMIC
  SELECT string_agg('(' || array_to_string(daitch_mokotoff(n), '|') || ')', '&')::tsquery
  FROM regexp_split_to_table(v_name, '\s+') AS n;
END;

-- fuzzystrmatch.sgml:207
CREATE INDEX ix_s_txt ON s USING gin (soundex_tsvector(nm)) WITH (fastupdate = off);

-- fuzzystrmatch.sgml:207
INSERT INTO s (nm) VALUES
  ('John Doe'),
  ('Jane Roe'),
  ('Public John Q.'),
  ('George Best'),
  ('John Yamson');

-- fuzzystrmatch.sgml:207
SELECT * FROM s WHERE soundex_tsvector(nm) @@ soundex_tsquery('john');

-- fuzzystrmatch.sgml:207
SELECT * FROM s WHERE soundex_tsvector(nm) @@ soundex_tsquery('jane doe');

-- fuzzystrmatch.sgml:207
SELECT * FROM s WHERE soundex_tsvector(nm) @@ soundex_tsquery('john public');

-- fuzzystrmatch.sgml:207
SELECT * FROM s WHERE soundex_tsvector(nm) @@ soundex_tsquery('besst, giorgio');

-- fuzzystrmatch.sgml:207
SELECT * FROM s WHERE soundex_tsvector(nm) @@ soundex_tsquery('Jameson John');

-- fuzzystrmatch.sgml:290
SELECT levenshtein('GUMBO', 'GAMBOL');

-- fuzzystrmatch.sgml:290
SELECT levenshtein('GUMBO', 'GAMBOL', 2, 1, 1);

-- fuzzystrmatch.sgml:290
SELECT levenshtein_less_equal('extensive', 'exhaustive', 2);

-- fuzzystrmatch.sgml:290
SELECT levenshtein_less_equal('extensive', 'exhaustive', 4);

-- fuzzystrmatch.sgml:349
SELECT metaphone('GUMBO', 4);

-- fuzzystrmatch.sgml:390
SELECT dmetaphone('gumbo');
