-- Generated by script/extract-doc-sql.js from doc/src/sgml/high-availability.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- high-availability.sgml:993
SELECT * FROM pg_create_physical_replication_slot('node_a_slot');

-- high-availability.sgml:993
SELECT slot_name, slot_type, active FROM pg_replication_slots;

-- high-availability.sgml:1416
SELECT pg_current_wal_insert_lsn();
