-- Generated by script/extract-doc-sql.js from doc/src/sgml/hstore.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- hstore.sgml:51
SELECT 'a=>1,a=>2'::hstore;

-- hstore.sgml:712
CREATE TABLE mytable (h hstore);

-- hstore.sgml:712
INSERT INTO mytable VALUES ('a=>b, c=>d');

-- hstore.sgml:712
SELECT h['a'] FROM mytable;

-- hstore.sgml:712
UPDATE mytable SET h['c'] = 'new';

-- hstore.sgml:712
SELECT h FROM mytable;

-- hstore.sgml:746
CREATE INDEX hidx ON testhstore USING GIST (h);

-- hstore.sgml:746
CREATE INDEX hidx ON testhstore USING GIN (h);

-- hstore.sgml:764
CREATE INDEX hidx ON testhstore USING GIST (h gist_hstore_ops(siglen=32));

-- hstore.sgml:778
CREATE INDEX hidx ON testhstore USING BTREE (h);

-- hstore.sgml:778
CREATE INDEX hidx ON testhstore USING HASH (h);

-- hstore.sgml:790
UPDATE tab SET h['c'] = '3';

-- hstore.sgml:794
UPDATE tab SET h = h || hstore('c', '3');

-- hstore.sgml:799
UPDATE tab SET h = h || hstore(ARRAY['q', 'w'], ARRAY['11', '12']);

-- hstore.sgml:806
UPDATE tab SET h = delete(h, 'k1');

-- hstore.sgml:813
CREATE TABLE test (col1 integer, col2 text, col3 text);

-- hstore.sgml:813
INSERT INTO test VALUES (123, 'foo', 'bar');

-- hstore.sgml:813
SELECT hstore(t) FROM test AS t;

-- hstore.sgml:827
SELECT * FROM populate_record(null::test,
                              '"col1"=>"456", "col2"=>"zzz"');

-- hstore.sgml:841
SELECT (r).* FROM (SELECT t #= '"col3"=>"baz"' AS r FROM test t) s;

-- hstore.sgml:866
SELECT * FROM each('aaa=>bq, b=>NULL, ""=>1');

-- hstore.sgml:873
CREATE TABLE stat AS SELECT (each(h)).key, (each(h)).value FROM testhstore;

-- hstore.sgml:880
SELECT key, count(*) FROM
  (SELECT (each(h)).key FROM testhstore) AS stat
  GROUP BY key
  ORDER BY count DESC, key;

-- hstore.sgml:917
UPDATE tablename SET hstorecol = hstorecol || '';

-- hstore.sgml:924
ALTER TABLE tablename ALTER hstorecol TYPE hstore USING hstorecol || '';
