-- Generated by script/extract-doc-sql.js from doc/src/sgml/indices.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- indices.sgml:24
CREATE TABLE test1 (
    id integer,
    content varchar
);

-- indices.sgml:60
CREATE INDEX test1_id_index ON test1 (id);

-- indices.sgml:427
CREATE TABLE test2 (
  major int,
  minor int,
  name varchar
);

-- indices.sgml:442
CREATE INDEX test2_mm_idx ON test2 (major, minor);

-- indices.sgml:608
CREATE INDEX test2_info_nulls_low ON test2 (info NULLS FIRST);

-- indices.sgml:608
CREATE INDEX test3_desc_index ON test3 (id DESC NULLS LAST);

-- indices.sgml:790
SELECT * FROM test1 WHERE lower(col1) = 'value';

-- indices.sgml:796
CREATE INDEX test1_lower_col1_idx ON test1 (lower(col1));

-- indices.sgml:811
SELECT * FROM people WHERE (first_name || ' ' || last_name) = 'John Smith';

-- indices.sgml:815
CREATE INDEX people_names ON people ((first_name || ' ' || last_name));

-- indices.sgml:896
CREATE INDEX access_log_client_ip_ix ON access_log (client_ip)
WHERE NOT (client_ip > inet '192.168.100.0' AND
           client_ip < inet '192.168.100.255');

-- indices.sgml:905
SELECT *
FROM access_log
WHERE url = '/index.html' AND client_ip = inet '212.78.10.32';

-- indices.sgml:913
SELECT *
FROM access_log
WHERE url = '/index.html' AND client_ip = inet '192.168.100.23';

-- indices.sgml:950
CREATE INDEX orders_unbilled_index ON orders (order_nr)
    WHERE billed IS NOT TRUE;

-- indices.sgml:958
SELECT * FROM orders WHERE billed IS NOT TRUE AND order_nr < 10000;

-- indices.sgml:963
SELECT * FROM orders WHERE billed IS NOT TRUE AND amount > 5000.00;

-- indices.sgml:975
SELECT * FROM orders WHERE order_nr = 3501;

-- indices.sgml:1028
CREATE UNIQUE INDEX tests_success_constraint ON tests (subject, target)
    WHERE success;

-- indices.sgml:1089
CREATE INDEX mytable_cat_data ON mytable (category, data);

-- indices.sgml:1185
SELECT x, y FROM tab WHERE x = 'key';

-- indices.sgml:1185
SELECT x FROM tab WHERE x = 'key' AND y < 42;

-- indices.sgml:1190
SELECT x, z FROM tab WHERE x = 'key';

-- indices.sgml:1190
SELECT x FROM tab WHERE x = 'key' AND z < 42;

-- indices.sgml:1251
SELECT y FROM tab WHERE x = 'key';

-- indices.sgml:1256
CREATE INDEX tab_x_y ON tab(x) INCLUDE (y);

-- indices.sgml:1269
CREATE UNIQUE INDEX tab_x_y ON tab(x) INCLUDE (y);

-- indices.sgml:1300
CREATE INDEX tab_x_y ON tab(x, y);

-- indices.sgml:1330
SELECT f(x) FROM tab WHERE f(x) < 1;

-- indices.sgml:1344
CREATE INDEX tab_f_x ON tab (f(x)) INCLUDE (x);

-- indices.sgml:1365
SELECT target FROM tests WHERE subject = 'some-subject' AND success;

-- indices.sgml:1434
CREATE INDEX test_index ON test_table (col varchar_pattern_ops);

-- indices.sgml:1457
SELECT am.amname AS index_method,
       opc.opcname AS opclass_name,
       opc.opcintype::regtype AS indexed_type,
       opc.opcdefault AS is_default
    FROM pg_am am, pg_opclass opc
    WHERE opc.opcmethod = am.oid
    ORDER BY index_method, opclass_name;

-- indices.sgml:1481
SELECT am.amname AS index_method,
       opc.opcname AS opclass_name,
       opf.opfname AS opfamily_name,
       opc.opcintype::regtype AS indexed_type,
       opc.opcdefault AS is_default
    FROM pg_am am, pg_opclass opc, pg_opfamily opf
    WHERE opc.opcmethod = am.oid AND
          opc.opcfamily = opf.oid
    ORDER BY index_method, opclass_name;

-- indices.sgml:1497
SELECT am.amname AS index_method,
       opf.opfname AS opfamily_name,
       amop.amopopr::regoperator AS opfamily_operator
    FROM pg_am am, pg_opfamily opf, pg_amop amop
    WHERE opf.opfmethod = am.oid AND
          amop.amopfamily = opf.oid
    ORDER BY index_method, opfamily_name, opfamily_operator;

-- indices.sgml:1529
CREATE TABLE test1c (
    id integer,
    content varchar COLLATE "x"
);

-- indices.sgml:1529
CREATE INDEX test1c_content_index ON test1c (content);

-- indices.sgml:1550
CREATE INDEX test1c_content_y_index ON test1c (content COLLATE "y");
