-- Generated by script/extract-doc-sql.js from doc/src/sgml/intagg.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- intagg.sgml:60
CREATE TABLE many_to_many(id_left  INT REFERENCES left_table,
                          id_right INT REFERENCES right_table);

-- intagg.sgml:88
CREATE TABLE summary AS
  SELECT id_left, int_array_aggregate(id_right) AS rights
  FROM many_to_many
  GROUP BY id_left;
