-- Generated by script/extract-doc-sql.js from doc/src/sgml/isn.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- isn.sgml:366
SELECT isbn('978-0-393-04002-9');

-- isn.sgml:366
SELECT isbn13('0901690546');

-- isn.sgml:366
SELECT issn('1436-4522');

-- isn.sgml:366
SELECT upc(ean13('0220356483481'));

-- isn.sgml:366
SELECT ean13(upc('220356483481'));

-- isn.sgml:366
CREATE TABLE test (id isbn);

-- isn.sgml:366
INSERT INTO test VALUES('9780393040029');

-- isn.sgml:366
INSERT INTO test VALUES('220500896?');

-- isn.sgml:366
INSERT INTO test VALUES('978055215372?');

-- isn.sgml:366
SELECT issn('3251231?');

-- isn.sgml:366
SELECT ismn('979047213542?');

-- isn.sgml:366
SET isn.weak TO true;

-- isn.sgml:366
INSERT INTO test VALUES('978-0-11-000533-4');

-- isn.sgml:366
INSERT INTO test VALUES('9780141219307');

-- isn.sgml:366
INSERT INTO test VALUES('2-205-00876-X');

-- isn.sgml:366
SET isn.weak TO false;

-- isn.sgml:366
SELECT id FROM test WHERE NOT is_valid(id);

-- isn.sgml:366
UPDATE test SET id = make_valid(id) WHERE id = '2-205-00876-X!';

-- isn.sgml:366
SELECT * FROM test;

-- isn.sgml:366
SELECT isbn13(id) FROM test;
