-- Generated by script/extract-doc-sql.js from doc/src/sgml/json.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- json.sgml:179
SELECT '5'::json;

-- json.sgml:179
SELECT '[1, 2, "foo", null]'::json;

-- json.sgml:179
SELECT '{"bar": "baz", "balance": 7.77, "active": false}'::json;

-- json.sgml:179
SELECT '{"foo": [true, "bar"], "tags": {"a": 1, "b": null}}'::json;

-- json.sgml:201
SELECT '{"bar": "baz", "balance": 7.77, "active":false}'::json;

-- json.sgml:201
SELECT '{"bar": "baz", "balance": 7.77, "active":false}'::jsonb;

-- json.sgml:219
SELECT '{"reading": 1.230e-5}'::json, '{"reading": 1.230e-5}'::jsonb;

-- json.sgml:328
SELECT '["foo", "bar"]'::jsonb @> '"bar"'::jsonb;

-- json.sgml:328
SELECT '"bar"'::jsonb @> '["bar"]'::jsonb;  -- yields false

-- json.sgml:343
SELECT '["foo", "bar", "baz"]'::jsonb ? 'bar';

-- json.sgml:343
SELECT '{"foo": "bar"}'::jsonb ? 'foo';

-- json.sgml:343
SELECT '{"foo": "bar"}'::jsonb ? 'bar';  -- yields false

-- json.sgml:343
SELECT '{"foo": {"bar": "baz"}}'::jsonb ? 'bar'; -- yields false

-- json.sgml:343
SELECT '"foo"'::jsonb ? 'foo';

-- json.sgml:376
SELECT doc->'site_name' FROM websites
  WHERE doc @> '{"tags":[{"term":"paris"}, {"term":"food"}]}';

-- json.sgml:381
SELECT doc->'site_name' FROM websites
  WHERE doc->'tags' @> '[{"term":"paris"}, {"term":"food"}]';

-- json.sgml:425
CREATE INDEX idxgin ON api USING GIN (jdoc);

-- json.sgml:432
CREATE INDEX idxginp ON api USING GIN (jdoc jsonb_path_ops);

-- json.sgml:462
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc @> '{"company": "Magnafone"}';

-- json.sgml:469
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc -> 'tags' ? 'qui';

-- json.sgml:477
CREATE INDEX idxgintags ON api USING GIN ((jdoc -> 'tags'));

-- json.sgml:490
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc @> '{"tags": ["qui"]}';

-- json.sgml:508
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc @? '$.tags[*] ? (@ == "qui")';

-- json.sgml:511
SELECT jdoc->'guid', jdoc->'name' FROM api WHERE jdoc @@ '$.tags[*] == "qui"';

-- json.sgml:646
SELECT ('{"a": 1}'::jsonb)['a'];

-- json.sgml:646
SELECT ('{"a": {"b": {"c": 1}}}'::jsonb)['a']['b']['c'];

-- json.sgml:646
SELECT ('[1, "2", null]'::jsonb)[1];

-- json.sgml:646
UPDATE table_name SET jsonb_field['key'] = '1';

-- json.sgml:646
UPDATE table_name SET jsonb_field['a']['b']['c'] = '1';

-- json.sgml:646
SELECT * FROM table_name WHERE jsonb_field['key'] = '"value"';

-- json.sgml:678
UPDATE table_name SET jsonb_field['a'] = '1';

-- json.sgml:678
UPDATE table_name SET jsonb_field[0] = '1';

-- json.sgml:690
UPDATE table_name SET jsonb_field[2] = '2';

-- json.sgml:704
UPDATE table_name SET jsonb_field['a'][0]['b'] = '1';

-- json.sgml:704
UPDATE table_name SET jsonb_field[1]['a'] = '1';
