-- Generated by script/extract-doc-sql.js from doc/src/sgml/libpq.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- libpq.sgml:3581
SELECT * FROM mytable WHERE x = $1::bigint;

-- libpq.sgml:4491
SELECT 1 AS FOO, 2 AS "BAR";

-- libpq.sgml:6320
SELECT x FROM mytable WHERE id = 42 FOR UPDATE;

-- libpq.sgml:6320
UPDATE mytable SET x = 3 WHERE id = 42;

-- libpq.sgml:6329
UPDATE mytable SET x = x + 1 WHERE id = 42;
