-- Generated by script/extract-doc-sql.js from doc/src/sgml/lo.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- lo.sgml:76
CREATE TABLE image (title text, raster lo);

-- lo.sgml:76
CREATE TRIGGER t_raster BEFORE UPDATE OR DELETE ON image
    FOR EACH ROW EXECUTE FUNCTION lo_manage(raster);
