-- Generated by script/extract-doc-sql.js from doc/src/sgml/lobj.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- lobj.sgml:642
CREATE TABLE image (
    name            text,
    raster          oid
);

-- lobj.sgml:642
SELECT lo_creat(-1);       -- returns OID of new, empty large object

-- lobj.sgml:642
SELECT lo_create(43213);   -- attempts to create large object with OID 43213

-- lobj.sgml:642
SELECT lo_unlink(173454);  -- deletes large object with OID 173454

-- lobj.sgml:642
INSERT INTO image (name, raster)
    VALUES ('beautiful image', lo_import('/etc/motd'));

-- lobj.sgml:642
INSERT INTO image (name, raster)  -- same as above, but specify OID to use
    VALUES ('beautiful image', lo_import('/etc/motd', 68583));

-- lobj.sgml:642
SELECT lo_export(image.raster, '/tmp/motd') FROM image
    WHERE name = 'beautiful image';
