-- Generated by script/extract-doc-sql.js from doc/src/sgml/logical-replication.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- logical-replication.sgml:3572
CREATE PUBLICATION mypub FOR TABLE users, departments;

-- logical-replication.sgml:3579
CREATE SUBSCRIPTION mysub CONNECTION 'dbname=foo host=bar user=repuser' PUBLICATION mypub;
