-- Generated by script/extract-doc-sql.js from doc/src/sgml/logicaldecoding.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- logicaldecoding.sgml:56
SELECT * FROM pg_create_logical_replication_slot('regression_slot', 'test_decoding', false, true);

-- logicaldecoding.sgml:56
SELECT slot_name, plugin, slot_type, database, active, restart_lsn, confirmed_flush_lsn FROM pg_replication_slots;

-- logicaldecoding.sgml:56
SELECT * FROM pg_logical_slot_get_changes('regression_slot', NULL, NULL);

-- logicaldecoding.sgml:56
CREATE TABLE data(id serial PRIMARY KEY, data text);

-- logicaldecoding.sgml:56
INSERT INTO data(data) VALUES('3');

-- logicaldecoding.sgml:56
SELECT * FROM pg_logical_slot_peek_changes('regression_slot', NULL, NULL);

-- logicaldecoding.sgml:56
SELECT * FROM pg_logical_slot_peek_changes('regression_slot', NULL, NULL, 'include-timestamp', 'on');

-- logicaldecoding.sgml:56
SELECT pg_drop_replication_slot('regression_slot');

-- logicaldecoding.sgml:197
COMMIT PREPARED 'test_prepared1';

-- logicaldecoding.sgml:197
SELECT * from pg_logical_slot_get_changes('regression_slot', NULL, NULL);

-- logicaldecoding.sgml:197
ROLLBACK PREPARED 'test_prepared2';

-- logicaldecoding.sgml:870
ALTER TABLE user_catalog_table SET (user_catalog_table = true);

-- logicaldecoding.sgml:870
CREATE TABLE another_catalog_table(data text) WITH (user_catalog_table = true);
