-- Generated by script/extract-doc-sql.js from doc/src/sgml/ltree.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ltree.sgml:655
CREATE INDEX path_gist_idx ON test USING GIST (path);

-- ltree.sgml:661
CREATE INDEX path_gist_idx ON test USING GIST (path gist_ltree_ops(siglen=100));

-- ltree.sgml:681
CREATE INDEX path_gist_idx ON test USING GIST (array_path);

-- ltree.sgml:687
CREATE INDEX path_gist_idx ON test USING GIST (array_path gist__ltree_ops(siglen=100));

-- ltree.sgml:705
CREATE TABLE test (path ltree);

-- ltree.sgml:705
INSERT INTO test VALUES ('Top');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Science');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Science.Astronomy');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Science.Astronomy.Astrophysics');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Science.Astronomy.Cosmology');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Hobbies');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Hobbies.Amateurs_Astronomy');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Collections');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Collections.Pictures');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy.Stars');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy.Galaxies');

-- ltree.sgml:705
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy.Astronauts');

-- ltree.sgml:705
CREATE INDEX path_idx ON test USING BTREE (path);

-- ltree.sgml:705
CREATE INDEX path_hash_idx ON test USING HASH (path);

-- ltree.sgml:744
SELECT path FROM test WHERE path <@ 'Top.Science';

-- ltree.sgml:758
SELECT path FROM test WHERE path ~ '*.Astronomy.*';

-- ltree.sgml:758
SELECT path FROM test WHERE path ~ '*.!pictures@.Astronomy.*';

-- ltree.sgml:783
SELECT path FROM test WHERE path @ 'Astro*% & !pictures@';

-- ltree.sgml:783
SELECT path FROM test WHERE path @ 'Astro* & !pictures@';

-- ltree.sgml:805
SELECT subpath(path,0,2)||'Space'||subpath(path,2) FROM test WHERE path <@ 'Top.Science.Astronomy';

-- ltree.sgml:819
CREATE FUNCTION ins_label(ltree, int, text) RETURNS ltree
    AS 'SELECT subpath($1, 0, $2) || $3 || subpath($1, $2);'
    LANGUAGE SQL IMMUTABLE;

-- ltree.sgml:819
SELECT ins_label(path,2,'Space') FROM test WHERE path <@ 'Top.Science.Astronomy';
