-- Generated by script/extract-doc-sql.js from doc/src/sgml/maintenance.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- maintenance.sgml:625
SELECT c.oid::regclass AS table_name,
       greatest(age(c.relfrozenxid), age(t.relfrozenxid)) AS age
FROM pg_class c
LEFT JOIN pg_class t ON c.reltoastrelid = t.oid
WHERE c.relkind IN ('r', 'm');

-- maintenance.sgml:625
SELECT datname, age(datfrozenxid) FROM pg_database;

-- maintenance.sgml:842
SELECT *, pg_size_pretty(members_size) members_size_pretty
     FROM pg_catalog.pg_get_multixact_stats();
