-- Generated by script/extract-doc-sql.js from doc/src/sgml/manage-ag.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- manage-ag.sgml:330
ALTER DATABASE mydb SET geqo TO off;

-- manage-ag.sgml:432
CREATE TABLESPACE fastspace LOCATION '/ssd1/postgresql/data';

-- manage-ag.sgml:466
CREATE TABLE foo(i int) TABLESPACE space1;

-- manage-ag.sgml:473
SET default_tablespace = space1;

-- manage-ag.sgml:473
CREATE TABLE foo(i int);
