-- Generated by script/extract-doc-sql.js from doc/src/sgml/monitoring.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- monitoring.sgml:1173
SELECT pid, wait_event_type, wait_event FROM pg_stat_activity WHERE wait_event IS NOT NULL;

-- monitoring.sgml:5862
SELECT pg_stat_get_backend_pid(backendid) AS pid,
       pg_stat_get_backend_activity(backendid) AS query
FROM pg_stat_get_backend_idset() AS backendid;

-- monitoring.sgml:8642
SELECT pg_relation_filepath(oid), relpages FROM pg_class WHERE relname = 'customer';

-- monitoring.sgml:8659
SELECT relname, relpages
FROM pg_class,
     (SELECT reltoastrelid
      FROM pg_class
      WHERE relname = 'customer') AS ss
WHERE oid = ss.reltoastrelid OR
      oid = (SELECT indexrelid
             FROM pg_index
             WHERE indrelid = ss.reltoastrelid)
ORDER BY relname;

-- monitoring.sgml:8680
SELECT c2.relname, c2.relpages
FROM pg_class c, pg_class c2, pg_index i
WHERE c.relname = 'customer' AND
      c.oid = i.indrelid AND
      c2.oid = i.indexrelid
ORDER BY c2.relname;

-- monitoring.sgml:8697
SELECT relname, relpages
FROM pg_class
ORDER BY relpages DESC;
