-- Generated by script/extract-doc-sql.js from doc/src/sgml/mvcc.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- mvcc.sgml:435
UPDATE accounts SET balance = balance + 100.00 WHERE acctnum = 12345;

-- mvcc.sgml:435
UPDATE accounts SET balance = balance - 100.00 WHERE acctnum = 7534;

-- mvcc.sgml:458
UPDATE website SET hits = hits + 1;

-- mvcc.sgml:664
SELECT SUM(value) FROM mytab WHERE class = 1;

-- mvcc.sgml:670
SELECT SUM(value) FROM mytab WHERE class = 2;

-- mvcc.sgml:1473
UPDATE accounts SET balance = balance + 100.00 WHERE acctnum = 11111;

-- mvcc.sgml:1480
UPDATE accounts SET balance = balance + 100.00 WHERE acctnum = 22222;

-- mvcc.sgml:1480
UPDATE accounts SET balance = balance - 100.00 WHERE acctnum = 11111;

-- mvcc.sgml:1494
UPDATE accounts SET balance = balance - 100.00 WHERE acctnum = 22222;

-- mvcc.sgml:1606
SELECT pg_advisory_lock(id) FROM foo WHERE id = 12345; -- ok

-- mvcc.sgml:1606
SELECT pg_advisory_lock(id) FROM foo WHERE id > 12345 LIMIT 100; -- danger!

-- mvcc.sgml:1606
SELECT pg_advisory_lock(q.id) FROM
(
  SELECT id FROM foo WHERE id > 12345 LIMIT 100
) q; -- ok
