-- Generated by script/extract-doc-sql.js from doc/src/sgml/pageinspect.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pageinspect.sgml:74
SELECT * FROM page_header(get_raw_page('pg_class', 0));

-- pageinspect.sgml:111
SELECT page_checksum(get_raw_page('pg_class', 0), 0);

-- pageinspect.sgml:142
SELECT fsm_page_contents(get_raw_page('pg_class', 'fsm', 0));

-- pageinspect.sgml:182
SELECT * FROM heap_page_items(get_raw_page('pg_class', 0));

-- pageinspect.sgml:208
SELECT tuple_data_split('pg_class'::regclass, t_data, t_infomask, t_infomask2, t_bits) FROM heap_page_items(get_raw_page('pg_class', 0));

-- pageinspect.sgml:240
SELECT * FROM heap_page_item_attrs(get_raw_page('pg_class', 0), 'pg_class'::regclass);

-- pageinspect.sgml:262
SELECT t_ctid, raw_flags, combined_flags
         FROM heap_page_items(get_raw_page('pg_class', 0)),
           LATERAL heap_tuple_infomask_flags(t_infomask, t_infomask2)
         WHERE t_infomask IS NOT NULL OR t_infomask2 IS NOT NULL;

-- pageinspect.sgml:301
SELECT * FROM bt_metap('pg_cast_oid_index');

-- pageinspect.sgml:330
SELECT * FROM bt_page_stats('pg_cast_oid_index', 1);

-- pageinspect.sgml:366
SELECT * FROM bt_multi_page_stats('pg_proc_oid_index', 5, 2);

-- pageinspect.sgml:409
SELECT itemoffset, ctid, itemlen, nulls, vars, data, dead, htid, tids[0:2] AS some_tids
        FROM bt_page_items('tenk2_hundred', 5);

-- pageinspect.sgml:497
SELECT itemoffset, ctid, itemlen, nulls, vars, data, dead, htid, tids[0:2] AS some_tids
        FROM bt_page_items(get_raw_page('tenk2_hundred', 5));

-- pageinspect.sgml:541
SELECT brin_page_type(get_raw_page('brinidx', 0));

-- pageinspect.sgml:563
SELECT * FROM brin_metapage_info(get_raw_page('brinidx', 0));

-- pageinspect.sgml:586
SELECT * FROM brin_revmap_data(get_raw_page('brinidx', 2)) LIMIT 5;

-- pageinspect.sgml:612
SELECT * FROM brin_page_items(get_raw_page('brinidx', 5),
                                     'brinidx')
       ORDER BY blknum, attnum LIMIT 6;

-- pageinspect.sgml:650
SELECT * FROM gin_metapage_info(get_raw_page('gin_index', 0));

-- pageinspect.sgml:681
SELECT * FROM gin_page_opaque_info(get_raw_page('gin_index', 2));

-- pageinspect.sgml:704
SELECT first_tid, nbytes, tids[0:5] AS some_tids
        FROM gin_leafpage_items(get_raw_page('gin_test_idx', 2));

-- pageinspect.sgml:742
SELECT * FROM gist_page_opaque_info(get_raw_page('test_gist_idx', 2));

-- pageinspect.sgml:765
SELECT * FROM gist_page_items(get_raw_page('test_gist_idx', 0), 'test_gist_idx');

-- pageinspect.sgml:830
SELECT hash_page_type(get_raw_page('con_hash_index', 0));

-- pageinspect.sgml:853
SELECT * FROM hash_page_stats(get_raw_page('con_hash_index', 1));

-- pageinspect.sgml:883
SELECT * FROM hash_page_items(get_raw_page('con_hash_index', 1)) LIMIT 5;

-- pageinspect.sgml:910
SELECT * FROM hash_bitmap_info('con_hash_index', 2052);
