-- Generated by script/extract-doc-sql.js from doc/src/sgml/perform.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- perform.sgml:86
EXPLAIN SELECT * FROM tenk1;

-- perform.sgml:179
SELECT relpages, reltuples FROM pg_class WHERE relname = 'tenk1';

-- perform.sgml:194
EXPLAIN SELECT * FROM tenk1 WHERE unique1 < 7000;

-- perform.sgml:305
EXPLAIN SELECT * FROM tenk1 ORDER BY unique1;

-- perform.sgml:589
SET enable_seqscan = off;

-- perform.sgml:589
EXPLAIN SELECT * FROM unit;

-- perform.sgml:1288
SELECT relname, relkind, reltuples, relpages
FROM pg_class
WHERE relname LIKE 'tenk1%';

-- perform.sgml:1361
SELECT attname, inherited, n_distinct,
       array_to_string(most_common_vals, E'\n') as most_common_vals
FROM pg_stats
WHERE tablename = 'road';

-- perform.sgml:1539
CREATE STATISTICS stts (dependencies) ON city, zip FROM zipcodes;

-- perform.sgml:1539
ANALYZE zipcodes;

-- perform.sgml:1539
SELECT stxkeys AS k, jsonb_pretty(stxddependencies::text::jsonb) AS dep
  FROM pg_statistic_ext JOIN pg_statistic_ext_data ON (oid = stxoid)
  WHERE stxname = 'stts';

-- perform.sgml:1597
SELECT * FROM zipcodes WHERE city = 'San Francisco' AND zip = '94105';

-- perform.sgml:1603
SELECT * FROM zipcodes WHERE city = 'San Francisco' AND zip = '90210';

-- perform.sgml:1645
CREATE STATISTICS stts2 (ndistinct) ON city, state, zip FROM zipcodes;

-- perform.sgml:1645
SELECT stxkeys AS k, jsonb_pretty(stxdndistinct::text::jsonb) AS nd
  FROM pg_statistic_ext JOIN pg_statistic_ext_data on (oid = stxoid)
  WHERE stxname = 'stts2';

-- perform.sgml:1730
CREATE STATISTICS stts3 (mcv) ON city, state FROM zipcodes;

-- perform.sgml:1730
SELECT m.* FROM pg_statistic_ext join pg_statistic_ext_data on (oid = stxoid),
                pg_mcv_list_items(stxdmcv) m WHERE stxname = 'stts3';

-- perform.sgml:1788
SELECT * FROM a, b, c WHERE a.id = b.id AND b.ref = c.id;

-- perform.sgml:1828
SELECT * FROM a LEFT JOIN (b JOIN c ON (b.ref = c.id)) ON (a.id = b.id);

-- perform.sgml:1839
SELECT * FROM a LEFT JOIN b ON (a.bid = b.id) LEFT JOIN c ON (a.cid = c.id);

-- perform.sgml:1861
SELECT * FROM a CROSS JOIN b CROSS JOIN c WHERE a.id = b.id AND b.ref = c.id;

-- perform.sgml:1861
SELECT * FROM a JOIN (b JOIN c ON (b.ref = c.id)) ON (a.id = b.id);

-- perform.sgml:1904
SELECT *
FROM x, y,
    (SELECT * FROM a, b, c WHERE something) AS ss
WHERE somethingelse;

-- perform.sgml:1914
SELECT * FROM x, y, a, b, c WHERE something AND somethingelse;
