-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgbuffercache.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgbuffercache.sgml:679
SELECT n.nspname, c.relname, count(*) AS buffers
             FROM pg_buffercache b JOIN pg_class c
             ON b.relfilenode = pg_relation_filenode(c.oid) AND
                b.reldatabase IN (0, (SELECT oid FROM pg_database
                                      WHERE datname = current_database()))
             JOIN pg_namespace n ON n.oid = c.relnamespace
             GROUP BY n.nspname, c.relname
             ORDER BY 3 DESC
             LIMIT 10;

-- pgbuffercache.sgml:679
SELECT pages_per_buffer, COUNT(*) as buffer_count
             FROM (
                   SELECT bufferid, COUNT(*) as pages_per_buffer
                   FROM pg_buffercache_os_pages
                   GROUP BY bufferid
                  )
             GROUP BY pages_per_buffer
             ORDER BY pages_per_buffer;

-- pgbuffercache.sgml:679
SELECT n.nspname, c.relname, count(*) AS buffers_on_multiple_pages
             FROM pg_buffercache b JOIN pg_class c
             ON b.relfilenode = pg_relation_filenode(c.oid) AND
                b.reldatabase IN (0, (SELECT oid FROM pg_database
                                      WHERE datname = current_database()))
             JOIN pg_namespace n ON n.oid = c.relnamespace
             JOIN (SELECT bufferid FROM pg_buffercache_os_pages
                   GROUP BY bufferid HAVING count(*) > 1) m on m.bufferid = b.bufferid
             GROUP BY n.nspname, c.relname
             ORDER BY 3 DESC
             LIMIT 10;

-- pgbuffercache.sgml:679
SELECT * FROM pg_buffercache_summary();

-- pgbuffercache.sgml:679
SELECT * FROM pg_buffercache_usage_counts();
