-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgcrypto.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgcrypto.sgml:59
CREATE OR REPLACE FUNCTION sha1(bytea) RETURNS text AS $$
    SELECT encode(digest($1, 'sha1'), 'hex')
$$ LANGUAGE SQL STRICT IMMUTABLE;
