-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgfreespacemap.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgfreespacemap.sgml:77
SELECT * FROM pg_freespace('foo');

-- pgfreespacemap.sgml:77
SELECT * FROM pg_freespace('foo', 7);
