-- Generated by script/extract-doc-sql.js from doc/src/sgml/pglogicalinspect.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pglogicalinspect.sgml:40
SELECT * FROM pg_ls_logicalsnapdir();

-- pglogicalinspect.sgml:40
SELECT * FROM pg_get_logical_snapshot_meta('0-40796E18.snap');

-- pglogicalinspect.sgml:40
SELECT ss.name, meta.* FROM pg_ls_logicalsnapdir() AS ss,
pg_get_logical_snapshot_meta(ss.name) AS meta;

-- pglogicalinspect.sgml:81
SELECT * FROM pg_get_logical_snapshot_info('0-40796E18.snap');

-- pglogicalinspect.sgml:81
SELECT ss.name, info.* FROM pg_ls_logicalsnapdir() AS ss,
pg_get_logical_snapshot_info(ss.name) AS info;
