-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgplanadvice.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgplanadvice.sgml:49
EXPLAIN (COSTS OFF, PLAN_ADVICE)
        SELECT * FROM join_fact f JOIN join_dim d ON f.dim_id = d.id;

-- pgplanadvice.sgml:97
SET pg_plan_advice.advice = 'JOIN_ORDER(f d)';

-- pgplanadvice.sgml:97
EXPLAIN (COSTS OFF)
        SELECT * FROM join_fact f JOIN join_dim d ON f.dim_id = d.id;

-- pgplanadvice.sgml:166
SET pg_plan_advice.advice = 'JOIN_ORDER(x f d)';

-- pgplanadvice.sgml:557
SET pg_plan_advice.advice = 'hash_join(f g) join_order(f g) index_scan(f no_such_index)';

-- pgplanadvice.sgml:557
EXPLAIN (COSTS OFF)
    SELECT * FROM jo_fact f
    LEFT JOIN jo_dim1 d1 ON f.dim1_id = d1.id
    LEFT JOIN jo_dim2 d2 ON f.dim2_id = d2.id
    WHERE val1 = 1 AND val2 = 1;
