-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgrowlocks.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgrowlocks.sgml:119
SELECT * FROM accounts AS a, pgrowlocks('accounts') AS p
  WHERE p.locked_row = a.ctid;

-- pgrowlocks.sgml:131
SELECT * FROM pgrowlocks('t1');
