-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgstattuple.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgstattuple.sgml:45
SELECT * FROM pgstattuple('pg_catalog.pg_proc');

-- pgstattuple.sgml:173
SELECT * FROM pgstatindex('pg_cast_oid_index');

-- pgstattuple.sgml:319
SELECT * FROM pgstatginindex('test_gin_index');

-- pgstattuple.sgml:379
SELECT * FROM pgstathashindex('con_hash_index');

-- pgstattuple.sgml:507
SELECT * FROM pgstattuple_approx('pg_catalog.pg_proc'::regclass);
