-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgstatstatements.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgstatstatements.sgml:657
SELECT pg_stat_statements_reset();

-- pgstatstatements.sgml:657
SELECT * FROM test WHERE a IN (1, 2, 3, 4, 5, 6, 7);

-- pgstatstatements.sgml:657
SELECT * FROM test WHERE a IN (1, 2, 3, 4, 5, 6, 7, 8);

-- pgstatstatements.sgml:657
SELECT query, calls FROM pg_stat_statements
   WHERE query LIKE 'SELECT%';
