-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgsurgery.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgsurgery.sgml:36
SELECT * FROM t1 WHERE ctid = '(0, 1)';

-- pgsurgery.sgml:36
SELECT heap_force_kill('t1'::regclass, ARRAY['(0, 1)']::tid[]);

-- pgsurgery.sgml:68
vacuum t1;

-- pgsurgery.sgml:68
SELECT ctid FROM t1 WHERE xmin = 507;

-- pgsurgery.sgml:68
SELECT heap_force_freeze('t1'::regclass, ARRAY['(0, 3)']::tid[]);

-- pgsurgery.sgml:68
SELECT ctid FROM t1 WHERE xmin = 2;
