-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgtrgm.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgtrgm.sgml:430
CREATE TABLE test_trgm (t text);

-- pgtrgm.sgml:430
CREATE INDEX trgm_idx ON test_trgm USING GIST (t gist_trgm_ops);

-- pgtrgm.sgml:435
CREATE INDEX trgm_idx ON test_trgm USING GIN (t gin_trgm_ops);

-- pgtrgm.sgml:453
CREATE INDEX trgm_idx ON test_trgm USING GIST (t gist_trgm_ops(siglen=32));

-- pgtrgm.sgml:528
SELECT * FROM test_trgm WHERE t LIKE '%foo%bar';

-- pgtrgm.sgml:541
SELECT * FROM test_trgm WHERE t ~ '(foo|bar)';

-- pgtrgm.sgml:577
CREATE TABLE words AS SELECT word FROM
        ts_stat('SELECT to_tsvector(''simple'', bodytext) FROM documents');

-- pgtrgm.sgml:592
CREATE INDEX words_idx ON words USING GIN (word gin_trgm_ops);
