-- Generated by script/extract-doc-sql.js from doc/src/sgml/pgwalinspect.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- pgwalinspect.sgml:73
SELECT * FROM pg_get_wal_record_info('0/E419E28');

-- pgwalinspect.sgml:111
SELECT * FROM pg_get_wal_records_info('0/1E913618', '0/1E913740') LIMIT 1;

-- pgwalinspect.sgml:146
SELECT * FROM pg_get_wal_block_info('0/1230278', '0/12302B8');

-- pgwalinspect.sgml:251
SELECT * FROM pg_get_wal_stats('0/1E847D00', '0/1E84F500')
           WHERE count > 0 AND
                 "resource_manager/record_type" = 'Transaction'
           LIMIT 1;
