-- Generated by script/extract-doc-sql.js from doc/src/sgml/planstats.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- planstats.sgml:99
SELECT histogram_bounds FROM pg_stats
WHERE tablename='tenk1' AND attname='unique1';

-- planstats.sgml:138
EXPLAIN SELECT * FROM tenk1 WHERE stringu1 = 'CRAAAA';

-- planstats.sgml:188
EXPLAIN SELECT * FROM tenk1 WHERE stringu1 = 'xxx';

-- planstats.sgml:245
EXPLAIN SELECT * FROM tenk1 WHERE stringu1 < 'IAAAAA';

-- planstats.sgml:381
SELECT tablename, null_frac,n_distinct, most_common_vals FROM pg_stats
WHERE tablename IN ('tenk1', 'tenk2') AND attname='unique2';

-- planstats.sgml:465
CREATE TABLE t (a INT, b INT);

-- planstats.sgml:465
INSERT INTO t SELECT i % 100, i % 100 FROM generate_series(1, 10000) s(i);

-- planstats.sgml:465
ANALYZE t;

-- planstats.sgml:475
SELECT relpages, reltuples FROM pg_class WHERE relname = 't';

-- planstats.sgml:637
SELECT m.* FROM pg_statistic_ext JOIN pg_statistic_ext_data ON (oid = stxoid),
                pg_mcv_list_items(stxdmcv) m WHERE stxname = 'stts2';
