-- Generated by script/extract-doc-sql.js from doc/src/sgml/postgres-fdw.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- postgres-fdw.sgml:180
ALTER USER MAPPING FOR some_non_superuser SERVER loopback_nopw
OPTIONS (ADD password_required 'false');

-- postgres-fdw.sgml:922
SELECT * FROM postgres_fdw_get_connections(true);

-- postgres-fdw.sgml:1025
SELECT postgres_fdw_disconnect('loopback1');

-- postgres-fdw.sgml:1046
SELECT postgres_fdw_disconnect_all();

-- postgres-fdw.sgml:1108
CREATE SERVER subscription_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host 'foreign-host', dbname 'foreign_db');

-- postgres-fdw.sgml:1108
CREATE USER MAPPING FOR local_user SERVER subscription_server OPTIONS (user 'foreign_user', password 'password');

-- postgres-fdw.sgml:1108
CREATE SUBSCRIPTION my_subscription SERVER subscription_server PUBLICATION testpub;

-- postgres-fdw.sgml:1449
CREATE EXTENSION postgres_fdw;

-- postgres-fdw.sgml:1460
CREATE SERVER foreign_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host '192.83.123.89', port '5432', dbname 'foreign_db');

-- postgres-fdw.sgml:1472
CREATE USER MAPPING FOR local_user
        SERVER foreign_server
        OPTIONS (user 'foreign_user', password 'password');

-- postgres-fdw.sgml:1486
CREATE FOREIGN TABLE foreign_table (
        id integer NOT NULL,
        data text
)
        SERVER foreign_server
        OPTIONS (schema_name 'some_schema', table_name 'some_table');
