-- Generated by script/extract-doc-sql.js from doc/src/sgml/protocol.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- protocol.sgml:894
INSERT INTO mytable VALUES(1);

-- protocol.sgml:894
SELECT 1/0;

-- protocol.sgml:894
INSERT INTO mytable VALUES(2);

-- protocol.sgml:970
ROLLBACK;
