-- Generated by script/extract-doc-sql.js from doc/src/sgml/query.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- query.sgml:116
CREATE TABLE weather (
    city            varchar(80),
    temp_lo         int,           -- low temperature
    temp_hi         int,           -- high temperature
    prcp            real,          -- precipitation
    date            date
);

-- query.sgml:170
CREATE TABLE cities (
    name            varchar(80),
    location        point
);

-- query.sgml:206
INSERT INTO weather VALUES ('San Francisco', 46, 50, 0.25, '1994-11-27');

-- query.sgml:222
INSERT INTO cities VALUES ('San Francisco', '(-194.0, 53.0)');

-- query.sgml:231
INSERT INTO weather (city, temp_lo, temp_hi, prcp, date)
    VALUES ('San Francisco', 43, 57, 0.0, '1994-11-29');

-- query.sgml:237
INSERT INTO weather (date, city, temp_hi, temp_lo)
    VALUES ('1994-11-29', 'Hayward', 54, 37);

-- query.sgml:261
COPY weather FROM '/home/user/weather.txt';

-- query.sgml:299
SELECT * FROM weather;

-- query.sgml:311
SELECT city, temp_lo, temp_hi, prcp, date FROM weather;

-- query.sgml:330
SELECT city, (temp_hi+temp_lo)/2 AS temp_avg, date FROM weather;

-- query.sgml:356
SELECT * FROM weather
    WHERE city = 'San Francisco' AND prcp > 0.0;

-- query.sgml:375
SELECT * FROM weather
    ORDER BY city;

-- query.sgml:392
SELECT * FROM weather
    ORDER BY city, temp_lo;

-- query.sgml:405
SELECT DISTINCT city
    FROM weather;

-- query.sgml:433
SELECT DISTINCT city
    FROM weather
    ORDER BY city;

-- query.sgml:471
SELECT * FROM weather JOIN cities ON city = name;

-- query.sgml:507
SELECT city, temp_lo, temp_hi, prcp, date, location
    FROM weather JOIN cities ON city = name;

-- query.sgml:523
SELECT weather.city, weather.temp_lo, weather.temp_hi,
       weather.prcp, weather.date, cities.location
    FROM weather JOIN cities ON weather.city = cities.name;

-- query.sgml:538
SELECT *
    FROM weather, cities
    WHERE city = name;

-- query.sgml:569
SELECT *
    FROM weather LEFT OUTER JOIN cities ON weather.city = cities.name;

-- query.sgml:615
SELECT w1.city, w1.temp_lo AS low, w1.temp_hi AS high,
       w2.city, w2.temp_lo AS low, w2.temp_hi AS high
    FROM weather w1 JOIN weather w2
        ON w1.temp_lo < w2.temp_lo AND w1.temp_hi > w2.temp_hi;

-- query.sgml:634
SELECT *
    FROM weather w JOIN cities c ON w.city = c.name;

-- query.sgml:665
SELECT max(temp_lo) FROM weather;

-- query.sgml:697
SELECT city FROM weather
    WHERE temp_lo = (SELECT max(temp_lo) FROM weather);

-- query.sgml:722
SELECT city, count(*), max(temp_lo)
    FROM weather
    GROUP BY city;

-- query.sgml:741
SELECT city, count(*), max(temp_lo)
    FROM weather
    GROUP BY city
    HAVING max(temp_lo) < 40;

-- query.sgml:815
SELECT city, count(*) FILTER (WHERE temp_lo < 45), max(temp_lo)
    FROM weather
    GROUP BY city;

-- query.sgml:854
UPDATE weather
    SET temp_hi = temp_hi - 2,  temp_lo = temp_lo - 2
    WHERE date > '1994-11-28';

-- query.sgml:888
DELETE FROM weather WHERE city = 'Hayward';
