-- Generated by script/extract-doc-sql.js from doc/src/sgml/queries.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- queries.sgml:40
SELECT * FROM table1;

-- queries.sgml:57
SELECT a, b + c FROM table1;

-- queries.sgml:71
SELECT 3 * 4;

-- queries.sgml:76
SELECT random();

-- queries.sgml:572
SELECT * FROM some_very_long_table_name s JOIN another_fairly_long_name a ON s.id = a.num;

-- queries.sgml:582
SELECT * FROM my_table AS m WHERE my_table.a > 5;    -- wrong

-- queries.sgml:590
SELECT * FROM people AS mother JOIN people AS child ON mother.id = child.mother_id;

-- queries.sgml:747
CREATE TABLE foo (fooid int, foosubid int, fooname text);

-- queries.sgml:747
CREATE FUNCTION getfoo(int) RETURNS SETOF foo AS $$
    SELECT * FROM foo WHERE fooid = $1;
$$ LANGUAGE SQL;

-- queries.sgml:747
SELECT * FROM getfoo(1) AS t1;

-- queries.sgml:747
SELECT * FROM foo
    WHERE foosubid IN (
                        SELECT foosubid
                        FROM getfoo(foo.fooid) z
                        WHERE z.fooid = foo.fooid
                      );

-- queries.sgml:747
CREATE VIEW vw_getfoo AS SELECT * FROM getfoo(1);

-- queries.sgml:747
SELECT * FROM vw_getfoo;

-- queries.sgml:801
SELECT *
    FROM dblink('dbname=mydb', 'SELECT proname, prosrc FROM pg_proc')
      AS t1(proname name, prosrc text)
    WHERE proname LIKE 'bytea%';

-- queries.sgml:818
SELECT *
FROM ROWS FROM
    (
        json_to_recordset('[{"a":40,"b":"foo"},{"a":"100","b":"bar"}]')
            AS (a INTEGER, b TEXT),
        generate_series(1, 3)
    ) AS x (p, q, s)
ORDER BY p;

-- queries.sgml:888
SELECT * FROM foo, LATERAL (SELECT * FROM bar WHERE bar.id = foo.bar_id) ss;

-- queries.sgml:893
SELECT * FROM foo, bar WHERE bar.id = foo.bar_id;

-- queries.sgml:902
SELECT p1.id, p2.id, v1, v2
FROM polygons p1, polygons p2,
     LATERAL vertices(p1.poly) v1,
     LATERAL vertices(p2.poly) v2
WHERE (v1 <-> v2) < 10 AND p1.id != p2.id;

-- queries.sgml:910
SELECT p1.id, p2.id, v1, v2
FROM polygons p1 CROSS JOIN LATERAL vertices(p1.poly) v1,
     polygons p2 CROSS JOIN LATERAL vertices(p2.poly) v2
WHERE (v1 <-> v2) < 10 AND p1.id != p2.id;

-- queries.sgml:929
SELECT m.name
FROM manufacturers m LEFT JOIN LATERAL get_product_names(m.id) pname ON true
WHERE pname IS NULL;

-- queries.sgml:1120
SELECT product_id, p.name, (sum(s.units) * p.price) AS sales
    FROM products p LEFT JOIN sales s USING (product_id)
    GROUP BY product_id, p.name, p.price;

-- queries.sgml:1196
SELECT product_id, p.name, (sum(s.units) * (p.price - p.cost)) AS profit
    FROM products p LEFT JOIN sales s USING (product_id)
    WHERE s.date > CURRENT_DATE - INTERVAL '4 weeks'
    GROUP BY product_id, p.name, p.price, p.cost
    HAVING sum(p.price * s.units) > 5000;

-- queries.sgml:1830
SELECT a, b FROM table1 ORDER BY a + b, c;

-- queries.sgml:1873
SELECT a + b AS sum, c FROM table1 ORDER BY sum;

-- queries.sgml:1873
SELECT a, max(b) FROM table1 GROUP BY a ORDER BY 1;

-- queries.sgml:1880
SELECT a + b AS sum, c FROM table1 ORDER BY sum + c;          -- wrong

-- queries.sgml:1998
VALUES (1, 'one'), (2, 'two'), (3, 'three');

-- queries.sgml:2004
SELECT 1 AS column1, 'one' AS column2
UNION ALL
SELECT 2, 'two'
UNION ALL
SELECT 3, 'three';

-- queries.sgml:2018
SELECT * FROM (VALUES (1, 'one'), (2, 'two'), (3, 'three')) AS t (num,letter);

-- queries.sgml:2083
WITH regional_sales AS (
    SELECT region, SUM(amount) AS total_sales
    FROM orders
    GROUP BY region
), top_regions AS (
    SELECT region
    FROM regional_sales
    WHERE total_sales > (SELECT SUM(total_sales)/10 FROM regional_sales)
)
SELECT region,
       product,
       SUM(quantity) AS product_units,
       SUM(amount) AS product_sales
FROM orders
WHERE region IN (SELECT region FROM top_regions)
GROUP BY region, product;

-- queries.sgml:2129
WITH RECURSIVE t(n) AS (
    VALUES (1)
  UNION ALL
    SELECT n+1 FROM t WHERE n < 100
)
SELECT sum(n) FROM t;

-- queries.sgml:2237
WITH RECURSIVE search_tree(id, link, data) AS (
    SELECT t.id, t.link, t.data
    FROM tree t
  UNION ALL
    SELECT t.id, t.link, t.data
    FROM tree t, search_tree st
    WHERE t.id = st.link
)
SELECT * FROM search_tree;

-- queries.sgml:2369
WITH RECURSIVE search_graph(id, link, data, depth) AS (
    SELECT g.id, g.link, g.data, 0
    FROM graph g
  UNION ALL
    SELECT g.id, g.link, g.data, sg.depth + 1
    FROM graph g, search_graph sg
    WHERE g.id = sg.link
)
SELECT * FROM search_graph;

-- queries.sgml:2542
WITH w AS (
    SELECT * FROM big_table
)
SELECT * FROM w WHERE key = 123;

-- queries.sgml:2550
SELECT * FROM big_table WHERE key = 123;

-- queries.sgml:2556
WITH w AS (
    SELECT * FROM big_table
)
SELECT * FROM w AS w1 JOIN w AS w2 ON w1.key = w2.ref
WHERE w2.key = 123;

-- queries.sgml:2567
WITH w AS NOT MATERIALIZED (
    SELECT * FROM big_table
)
SELECT * FROM w AS w1 JOIN w AS w2 ON w1.key = w2.ref
WHERE w2.key = 123;

-- queries.sgml:2581
WITH w AS (
    SELECT key, very_expensive_function(val) AS f FROM some_table
)
SELECT * FROM w AS w1 JOIN w AS w2 ON w1.f = w2.f;

-- queries.sgml:2612
WITH moved_rows AS (
    DELETE FROM products
    WHERE
        "date" >= '2010-10-01' AND
        "date" < '2010-11-01'
    RETURNING *
)
INSERT INTO products_log
SELECT * FROM moved_rows;

-- queries.sgml:2654
WITH t AS (
    DELETE FROM foo
)
DELETE FROM bar;

-- queries.sgml:2671
WITH RECURSIVE included_parts(sub_part, part) AS (
    SELECT sub_part, part FROM parts WHERE part = 'our_product'
  UNION ALL
    SELECT p.sub_part, p.part
    FROM included_parts pr, parts p
    WHERE p.part = pr.sub_part
)
DELETE FROM parts
  WHERE part IN (SELECT part FROM included_parts);

-- queries.sgml:2707
WITH t AS (
    UPDATE products SET price = price * 1.05
    RETURNING *
)
SELECT * FROM products;

-- queries.sgml:2718
WITH t AS (
    UPDATE products SET price = price * 1.05
    RETURNING *
)
SELECT * FROM t;
