-- Generated by script/extract-doc-sql.js from doc/src/sgml/rangetypes.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- rangetypes.sgml:93
CREATE TABLE reservation (room int, during tsrange);

-- rangetypes.sgml:93
INSERT INTO reservation VALUES
    (1108, '[2010-01-01 14:30, 2010-01-01 15:30)');

-- rangetypes.sgml:93
SELECT int4range(10, 20) @> 3;

-- rangetypes.sgml:93
SELECT numrange(11.1, 22.2) && numrange(20.0, 30.0);

-- rangetypes.sgml:93
SELECT upper(int8range(15, 25));

-- rangetypes.sgml:93
SELECT int4range(10, 20) * int4range(15, 25);

-- rangetypes.sgml:93
SELECT isempty(numrange(1, 5));

-- rangetypes.sgml:238
SELECT '[3,7)'::int4range;

-- rangetypes.sgml:238
SELECT '(3,7)'::int4range;

-- rangetypes.sgml:238
SELECT '[4,4]'::int4range;

-- rangetypes.sgml:238
SELECT '[4,4)'::int4range;

-- rangetypes.sgml:265
SELECT '{}'::int4multirange;

-- rangetypes.sgml:265
SELECT '{[3,7)}'::int4multirange;

-- rangetypes.sgml:265
SELECT '{[3,7), [8,9)}'::int4multirange;

-- rangetypes.sgml:293
SELECT numrange(1.0, 14.0, '(]');

-- rangetypes.sgml:293
SELECT numrange(1.0, 14.0);

-- rangetypes.sgml:293
SELECT int8range(1, 14, '(]');

-- rangetypes.sgml:293
SELECT numrange(NULL, 2.2);

-- rangetypes.sgml:316
SELECT nummultirange();

-- rangetypes.sgml:316
SELECT nummultirange(numrange(1.0, 14.0));

-- rangetypes.sgml:316
SELECT nummultirange(numrange(1.0, 14.0), numrange(20.0, 25.0));

-- rangetypes.sgml:380
CREATE TYPE floatrange AS RANGE (
    subtype = float8,
    subtype_diff = float8mi
);

-- rangetypes.sgml:380
SELECT '[1.234, 5.678]'::floatrange;

-- rangetypes.sgml:448
CREATE FUNCTION time_subtype_diff(x time, y time) RETURNS float8 AS
'SELECT EXTRACT(EPOCH FROM (x - y))' LANGUAGE sql STRICT IMMUTABLE;

-- rangetypes.sgml:448
CREATE TYPE timerange AS RANGE (
    subtype = time,
    subtype_diff = time_subtype_diff
);

-- rangetypes.sgml:448
SELECT '[11:10, 23:00]'::timerange;

-- rangetypes.sgml:478
CREATE INDEX reservation_idx ON reservation USING GIST (during);

-- rangetypes.sgml:537
CREATE TABLE reservation (
    during tsrange,
    EXCLUDE USING GIST (during WITH &&)
);

-- rangetypes.sgml:547
INSERT INTO reservation VALUES
    ('[2010-01-01 11:30, 2010-01-01 15:00)');

-- rangetypes.sgml:547
INSERT INTO reservation VALUES
    ('[2010-01-01 14:45, 2010-01-01 15:45)');

-- rangetypes.sgml:568
CREATE EXTENSION btree_gist;

-- rangetypes.sgml:568
CREATE TABLE room_reservation (
    room text,
    during tsrange,
    EXCLUDE USING GIST (room WITH =, during WITH &&)
);

-- rangetypes.sgml:568
INSERT INTO room_reservation VALUES
    ('123A', '[2010-01-01 14:00, 2010-01-01 15:00)');

-- rangetypes.sgml:568
INSERT INTO room_reservation VALUES
    ('123A', '[2010-01-01 14:30, 2010-01-01 15:30)');

-- rangetypes.sgml:568
INSERT INTO room_reservation VALUES
    ('123B', '[2010-01-01 14:30, 2010-01-01 15:30)');
