-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_transform.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_transform.sgml:160
CREATE EXTENSION plpython3u;

-- ref-create_transform.sgml:176
CREATE TRANSFORM FOR hstore LANGUAGE plpython3u (
    FROM SQL WITH FUNCTION hstore_to_plpython(internal),
    TO SQL WITH FUNCTION plpython_to_hstore(internal)
);
