-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_schema.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_schema.sgml:149
CREATE SCHEMA AUTHORIZATION joe;

-- ref-create_schema.sgml:158
CREATE SCHEMA IF NOT EXISTS test AUTHORIZATION joe;

-- ref-create_schema.sgml:165
CREATE SCHEMA hollywood
    CREATE TABLE films (title text, release date, awards text[])
    CREATE VIEW winners AS
        SELECT title, release FROM films WHERE awards IS NOT NULL;

-- ref-create_schema.sgml:176
CREATE SCHEMA hollywood;

-- ref-create_schema.sgml:176
CREATE TABLE hollywood.films (title text, release date, awards text[]);

-- ref-create_schema.sgml:176
CREATE VIEW hollywood.winners AS
    SELECT title, release FROM hollywood.films WHERE awards IS NOT NULL;
