-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_operator.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_operator.sgml:109
DROP OPERATOR ^ (integer, integer);

-- ref-drop_operator.sgml:117
DROP OPERATOR ~ (none, bit);

-- ref-drop_operator.sgml:124
DROP OPERATOR ~ (none, bit), ^ (integer, integer);
