-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_system.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_system.sgml:131
ALTER SYSTEM SET wal_level = replica;

-- ref-alter_system.sgml:139
ALTER SYSTEM RESET wal_level;

-- ref-alter_system.sgml:146
ALTER SYSTEM SET shared_preload_libraries TO NULL;
