-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/set_session_auth.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-set_session_auth.sgml:84
SET SESSION AUTHORIZATION 'paul';
