-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_extension.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_extension.sgml:98
DROP EXTENSION hstore;
