-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_foreign_data_wrapper.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_foreign_data_wrapper.sgml:90
DROP FOREIGN DATA WRAPPER dbi;
