-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_table_as.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_table_as.sgml:276
CREATE TABLE films_recent AS
  SELECT * FROM films WHERE date_prod >= '2002-01-01';

-- ref-create_table_as.sgml:286
CREATE TABLE films2 AS
  TABLE films;

-- ref-create_table_as.sgml:297
PREPARE recentfilms(date) AS
  SELECT * FROM films WHERE date_prod > $1;

-- ref-create_table_as.sgml:297
CREATE TEMP TABLE films_recent ON COMMIT DROP AS
  EXECUTE recentfilms('2002-01-01');
