-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/cluster.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-cluster.sgml:133
CLUSTER employees USING employees_ind;

-- ref-cluster.sgml:141
CLUSTER employees;

-- ref-cluster.sgml:148
CLUSTER;
