-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_domain.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_domain.sgml:310
ALTER DOMAIN zipcode SET NOT NULL;

-- ref-alter_domain.sgml:314
ALTER DOMAIN zipcode DROP NOT NULL;

-- ref-alter_domain.sgml:321
ALTER DOMAIN zipcode ADD CONSTRAINT zipchk CHECK (char_length(VALUE) = 5);

-- ref-alter_domain.sgml:328
ALTER DOMAIN zipcode DROP CONSTRAINT zipchk;

-- ref-alter_domain.sgml:335
ALTER DOMAIN zipcode RENAME CONSTRAINT zipchk TO zip_check;

-- ref-alter_domain.sgml:342
ALTER DOMAIN zipcode SET SCHEMA customers;
