-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_foreign_table.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_foreign_table.sgml:520
ALTER FOREIGN TABLE distributors ALTER COLUMN street SET NOT NULL;

-- ref-alter_foreign_table.sgml:527
ALTER FOREIGN TABLE myschema.distributors OPTIONS (ADD opt1 'value', SET opt2 'value2', DROP opt3);
