-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_database.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_database.sgml:463
CREATE DATABASE lusiadas;

-- ref-create_database.sgml:472
CREATE DATABASE sales OWNER salesapp TABLESPACE salesspace;

-- ref-create_database.sgml:479
CREATE DATABASE music
    LOCALE 'sv_SE.utf8'
    TEMPLATE template0;

-- ref-create_database.sgml:492
CREATE DATABASE music2
    LOCALE 'sv_SE.iso885915'
    ENCODING LATIN9
    TEMPLATE template0;
