-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_view.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_view.sgml:271
CREATE VIEW vista AS SELECT 'Hello World';

-- ref-create_view.sgml:278
CREATE VIEW vista AS SELECT text 'Hello World' AS hello;

-- ref-create_view.sgml:488
CREATE VIEW comedies AS
    SELECT *
    FROM films
    WHERE kind = 'Comedy';

-- ref-create_view.sgml:503
CREATE VIEW universal_comedies AS
    SELECT *
    FROM comedies
    WHERE classification = 'U'
    WITH LOCAL CHECK OPTION;

-- ref-create_view.sgml:521
CREATE VIEW pg_comedies AS
    SELECT *
    FROM comedies
    WHERE classification = 'PG'
    WITH CASCADED CHECK OPTION;

-- ref-create_view.sgml:535
CREATE VIEW comedies AS
    SELECT f.*,
           country_code_to_name(f.country_code) AS country,
           (SELECT avg(r.rating)
            FROM user_ratings r
            WHERE r.film_id = f.id) AS avg_rating
    FROM films f
    WHERE f.kind = 'Comedy';

-- ref-create_view.sgml:553
CREATE RECURSIVE VIEW public.nums_1_100 (n) AS
    VALUES (1)
UNION ALL
    SELECT n+1 FROM nums_1_100 WHERE n < 100;
