-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_rule.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_rule.sgml:81
ALTER RULE notify_all ON emp RENAME TO notify_me;
