-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_user_mapping.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_user_mapping.sgml:107
CREATE USER MAPPING FOR bob SERVER foo OPTIONS (user 'bob', password 'secret');
