-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/prepare.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-prepare.sgml:218
PREPARE fooplan (int, text, bool, numeric) AS
    INSERT INTO foo VALUES($1, $2, $3, $4);

-- ref-prepare.sgml:218
EXECUTE fooplan(1, 'Hunter Valley', 't', 200.00);

-- ref-prepare.sgml:228
PREPARE usrrptplan (int) AS
    SELECT * FROM users u, logs l WHERE u.usrid=$1 AND u.usrid=l.usrid
    AND l.date = $2;

-- ref-prepare.sgml:228
EXECUTE usrrptplan(1, current_date);
