-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_tsdictionary.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_tsdictionary.sgml:115
CREATE TEXT SEARCH DICTIONARY my_russian (
    template = snowball,
    language = russian,
    stopwords = myrussian
);
