-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/prepare_transaction.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-prepare_transaction.sgml:155
PREPARE TRANSACTION 'foobar';
