-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_user_mapping.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_user_mapping.sgml:86
DROP USER MAPPING IF EXISTS FOR bob SERVER foo;
