-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_sequence.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_sequence.sgml:89
DROP SEQUENCE serial;
