-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_publication.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_publication.sgml:83
DROP PUBLICATION mypublication;
