-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/explain.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-explain.sgml:410
EXPLAIN SELECT * FROM foo;

-- ref-explain.sgml:422
EXPLAIN (FORMAT JSON) SELECT * FROM foo;

-- ref-explain.sgml:448
EXPLAIN SELECT * FROM foo WHERE i = 4;

-- ref-explain.sgml:461
EXPLAIN (FORMAT YAML) SELECT * FROM foo WHERE i='4';

-- ref-explain.sgml:484
EXPLAIN (COSTS FALSE) SELECT * FROM foo WHERE i = 4;

-- ref-explain.sgml:578
EXPLAIN (GENERIC_PLAN)
  SELECT sum(bar) FROM test
    WHERE id > $1::integer AND id < $2::integer
    GROUP BY foo;
