-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_collation.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_collation.sgml:178
ALTER COLLATION "de_DE" RENAME TO german;

-- ref-alter_collation.sgml:186
ALTER COLLATION "en_US" OWNER TO joe;
