-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_extension.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_extension.sgml:297
ALTER EXTENSION hstore UPDATE TO '2.0';

-- ref-alter_extension.sgml:305
ALTER EXTENSION hstore SET SCHEMA utils;

-- ref-alter_extension.sgml:312
ALTER EXTENSION hstore ADD FUNCTION populate_record(anyelement, hstore);
