-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/fetch.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-fetch.sgml:351
BEGIN WORK;

-- ref-fetch.sgml:351
DECLARE liahona SCROLL CURSOR FOR SELECT * FROM films;

-- ref-fetch.sgml:351
FETCH FORWARD 5 FROM liahona;

-- ref-fetch.sgml:351
FETCH PRIOR FROM liahona;

-- ref-fetch.sgml:351
COMMIT WORK;
