-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/select_into.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-select_into.sgml:126
SELECT * INTO films_recent FROM films WHERE date_prod >= '2002-01-01';
