-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_policy.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_policy.sgml:97
DROP POLICY p1 ON my_table;
