-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_tablespace.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_tablespace.sgml:149
CREATE TABLESPACE dbspace LOCATION '/data/dbs';

-- ref-create_tablespace.sgml:157
CREATE TABLESPACE indexspace OWNER genevieve LOCATION '/data/indexes';
