-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_access_method.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_access_method.sgml:89
DROP ACCESS METHOD heptree;
