-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/show.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-show.sgml:122
SHOW DateStyle;

-- ref-show.sgml:133
SHOW geqo;

-- ref-show.sgml:144
SHOW ALL;
