-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_table.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_table.sgml:104
DROP TABLE films, distributors;
