-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_table.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_table.sgml:2088
CREATE TABLE films (
    code        char(5) CONSTRAINT firstkey PRIMARY KEY,
    title       varchar(40) NOT NULL,
    did         integer NOT NULL,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute
);

-- ref-create_table.sgml:2088
CREATE TABLE distributors (
     did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     name   varchar(40) NOT NULL CHECK (name <> '')
);

-- ref-create_table.sgml:2108
CREATE TABLE array_int (
    vector  int[][]
);

-- ref-create_table.sgml:2120
CREATE TABLE films (
    code        char(5),
    title       varchar(40),
    did         integer,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute,
    CONSTRAINT production UNIQUE(date_prod)
);

-- ref-create_table.sgml:2136
CREATE TABLE distributors (
    did     integer CHECK (did > 100),
    name    varchar(40)
);

-- ref-create_table.sgml:2147
CREATE TABLE distributors (
    did     integer,
    name    varchar(40),
    CONSTRAINT con1 CHECK (did > 100 AND name <> '')
);

-- ref-create_table.sgml:2160
CREATE TABLE films (
    code        char(5),
    title       varchar(40),
    did         integer,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute,
    CONSTRAINT code_title PRIMARY KEY(code,title)
);

-- ref-create_table.sgml:2179
CREATE TABLE distributors (
    did     integer,
    name    varchar(40),
    PRIMARY KEY(did)
);

-- ref-create_table.sgml:2179
CREATE TABLE distributors (
    did     integer PRIMARY KEY,
    name    varchar(40)
);

-- ref-create_table.sgml:2201
CREATE TABLE distributors (
    name      varchar(40) DEFAULT 'Luso Films',
    did       integer DEFAULT nextval('distributors_serial'),
    modtime   timestamp DEFAULT current_timestamp
);

-- ref-create_table.sgml:2215
CREATE TABLE distributors (
    did     integer CONSTRAINT no_null NOT NULL,
    name    varchar(40) NOT NULL
);

-- ref-create_table.sgml:2226
CREATE TABLE distributors (
    did     integer,
    name    varchar(40) UNIQUE
);

-- ref-create_table.sgml:2235
CREATE TABLE distributors (
    did     integer,
    name    varchar(40),
    UNIQUE(name)
);

-- ref-create_table.sgml:2248
CREATE TABLE distributors (
    did     integer,
    name    varchar(40),
    UNIQUE(name) WITH (fillfactor=70)
)
WITH (fillfactor=70);

-- ref-create_table.sgml:2273
CREATE TABLE cinemas (
        id serial,
        name text,
        location text
) TABLESPACE diskvol1;

-- ref-create_table.sgml:2284
CREATE TYPE employee_type AS (name text, salary numeric);

-- ref-create_table.sgml:2284
CREATE TABLE employees OF employee_type (
    PRIMARY KEY (name),
    salary WITH OPTIONS DEFAULT 1000
);

-- ref-create_table.sgml:2295
CREATE TABLE measurement (
    logdate         date NOT NULL,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (logdate);

-- ref-create_table.sgml:2305
CREATE TABLE measurement_year_month (
    logdate         date NOT NULL,
    peaktemp        int,
    unitsales       int
) PARTITION BY RANGE (EXTRACT(YEAR FROM logdate), EXTRACT(MONTH FROM logdate));

-- ref-create_table.sgml:2315
CREATE TABLE cities (
    city_id      bigserial NOT NULL,
    name         text NOT NULL,
    population   bigint
) PARTITION BY LIST (left(lower(name), 1));

-- ref-create_table.sgml:2325
CREATE TABLE orders (
    order_id     bigint NOT NULL,
    cust_id      bigint NOT NULL,
    status       text
) PARTITION BY HASH (order_id);

-- ref-create_table.sgml:2335
CREATE TABLE measurement_y2016m07
    PARTITION OF measurement (
    unitsales DEFAULT 0
) FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');

-- ref-create_table.sgml:2345
CREATE TABLE measurement_ym_older
    PARTITION OF measurement_year_month
    FOR VALUES FROM (MINVALUE, MINVALUE) TO (2016, 11);

-- ref-create_table.sgml:2345
CREATE TABLE measurement_ym_y2016m11
    PARTITION OF measurement_year_month
    FOR VALUES FROM (2016, 11) TO (2016, 12);

-- ref-create_table.sgml:2345
CREATE TABLE measurement_ym_y2016m12
    PARTITION OF measurement_year_month
    FOR VALUES FROM (2016, 12) TO (2017, 01);

-- ref-create_table.sgml:2345
CREATE TABLE measurement_ym_y2017m01
    PARTITION OF measurement_year_month
    FOR VALUES FROM (2017, 01) TO (2017, 02);

-- ref-create_table.sgml:2365
CREATE TABLE cities_ab
    PARTITION OF cities (
    CONSTRAINT city_id_nonzero CHECK (city_id != 0)
) FOR VALUES IN ('a', 'b');

-- ref-create_table.sgml:2375
CREATE TABLE cities_ab
    PARTITION OF cities (
    CONSTRAINT city_id_nonzero CHECK (city_id != 0)
) FOR VALUES IN ('a', 'b') PARTITION BY RANGE (population);

-- ref-create_table.sgml:2375
CREATE TABLE cities_ab_10000_to_100000
    PARTITION OF cities_ab FOR VALUES FROM (10000) TO (100000);

-- ref-create_table.sgml:2387
CREATE TABLE orders_p1 PARTITION OF orders
    FOR VALUES WITH (MODULUS 4, REMAINDER 0);

-- ref-create_table.sgml:2387
CREATE TABLE orders_p2 PARTITION OF orders
    FOR VALUES WITH (MODULUS 4, REMAINDER 1);

-- ref-create_table.sgml:2387
CREATE TABLE orders_p3 PARTITION OF orders
    FOR VALUES WITH (MODULUS 4, REMAINDER 2);

-- ref-create_table.sgml:2387
CREATE TABLE orders_p4 PARTITION OF orders
    FOR VALUES WITH (MODULUS 4, REMAINDER 3);

-- ref-create_table.sgml:2400
CREATE TABLE cities_partdef
    PARTITION OF cities DEFAULT;
