-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/revoke.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-revoke.sgml:303
REVOKE INSERT ON films FROM PUBLIC;

-- ref-revoke.sgml:312
REVOKE ALL PRIVILEGES ON kinds FROM manuel;

-- ref-revoke.sgml:323
REVOKE admins FROM joe;
