-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_aggregate.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_aggregate.sgml:167
ALTER AGGREGATE myavg(integer) RENAME TO my_average;

-- ref-alter_aggregate.sgml:175
ALTER AGGREGATE myavg(integer) OWNER TO joe;

-- ref-alter_aggregate.sgml:184
ALTER AGGREGATE mypercentile(float8 ORDER BY integer) SET SCHEMA myschema;

-- ref-alter_aggregate.sgml:188
ALTER AGGREGATE mypercentile(float8, integer) SET SCHEMA myschema;
