-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_view.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_view.sgml:197
ALTER VIEW foo RENAME TO bar;

-- ref-alter_view.sgml:204
CREATE TABLE base_table (id int, ts timestamptz);

-- ref-alter_view.sgml:204
CREATE VIEW a_view AS SELECT * FROM base_table;

-- ref-alter_view.sgml:204
ALTER VIEW a_view ALTER COLUMN ts SET DEFAULT now();

-- ref-alter_view.sgml:204
INSERT INTO base_table(id) VALUES(1);  -- ts will receive a NULL

-- ref-alter_view.sgml:204
INSERT INTO a_view(id) VALUES(2);  -- ts will receive the current time
