-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_tsdictionary.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_tsdictionary.sgml:124
ALTER TEXT SEARCH DICTIONARY my_dict ( StopWords = newrussian );

-- ref-alter_tsdictionary.sgml:133
ALTER TEXT SEARCH DICTIONARY my_dict ( language = dutch, StopWords );

-- ref-alter_tsdictionary.sgml:141
ALTER TEXT SEARCH DICTIONARY my_dict ( dummy );
