-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_trigger.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_trigger.sgml:102
DROP TRIGGER if_dist_exists ON films;
