-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_statistics.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_statistics.sgml:203
CREATE TABLE t1 (
    a   int,
    b   int
);

-- ref-create_statistics.sgml:203
INSERT INTO t1 SELECT i/100, i/500
                 FROM generate_series(1,1000000) s(i);

-- ref-create_statistics.sgml:203
ANALYZE t1;

-- ref-create_statistics.sgml:203
EXPLAIN ANALYZE SELECT * FROM t1 WHERE (a = 1) AND (b = 0);

-- ref-create_statistics.sgml:203
CREATE STATISTICS s1 (dependencies) ON a, b FROM t1;

-- ref-create_statistics.sgml:237
CREATE TABLE t2 (
    a   int,
    b   int
);

-- ref-create_statistics.sgml:237
INSERT INTO t2 SELECT mod(i,100), mod(i,100)
                 FROM generate_series(1,1000000) s(i);

-- ref-create_statistics.sgml:237
CREATE STATISTICS s2 (mcv) ON a, b FROM t2;

-- ref-create_statistics.sgml:237
ANALYZE t2;

-- ref-create_statistics.sgml:237
EXPLAIN ANALYZE SELECT * FROM t2 WHERE (a = 1) AND (b = 1);

-- ref-create_statistics.sgml:237
EXPLAIN ANALYZE SELECT * FROM t2 WHERE (a = 1) AND (b = 2);

-- ref-create_statistics.sgml:272
CREATE TABLE t3 (
    a   timestamp
);

-- ref-create_statistics.sgml:272
INSERT INTO t3 SELECT i FROM generate_series('2020-01-01'::timestamp,
                                             '2020-12-31'::timestamp,
                                             '1 minute'::interval) s(i);

-- ref-create_statistics.sgml:272
ANALYZE t3;

-- ref-create_statistics.sgml:272
EXPLAIN ANALYZE SELECT * FROM t3
  WHERE date_trunc('month', a) = '2020-01-01'::timestamp;

-- ref-create_statistics.sgml:272
EXPLAIN ANALYZE SELECT * FROM t3
  WHERE date_trunc('day', a) BETWEEN '2020-01-01'::timestamp
                                 AND '2020-06-30'::timestamp;

-- ref-create_statistics.sgml:272
EXPLAIN ANALYZE SELECT date_trunc('month', a), date_trunc('day', a)
   FROM t3 GROUP BY 1, 2;

-- ref-create_statistics.sgml:272
CREATE STATISTICS s3 (ndistinct) ON date_trunc('month', a), date_trunc('day', a) FROM t3;
