-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_procedure.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_procedure.sgml:176
DROP PROCEDURE do_db_maintenance;

-- ref-drop_procedure.sgml:187
DROP PROCEDURE do_db_maintenance(IN target_schema text, OUT results text);

-- ref-drop_procedure.sgml:187
DROP PROCEDURE do_db_maintenance(IN text, OUT text);

-- ref-drop_procedure.sgml:187
DROP PROCEDURE do_db_maintenance(IN text);

-- ref-drop_procedure.sgml:187
DROP PROCEDURE do_db_maintenance(text);

-- ref-drop_procedure.sgml:187
DROP PROCEDURE do_db_maintenance(text, text);  -- potentially ambiguous
