-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_tsconfig.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_tsconfig.sgml:92
DROP TEXT SEARCH CONFIGURATION my_english;
