-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_aggregate.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_aggregate.sgml:259
SELECT agg(col) FROM tab;
