-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_foreign_data_wrapper.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_foreign_data_wrapper.sgml:152
CREATE FOREIGN DATA WRAPPER dummy;

-- ref-create_foreign_data_wrapper.sgml:160
CREATE FOREIGN DATA WRAPPER file HANDLER file_fdw_handler;

-- ref-create_foreign_data_wrapper.sgml:168
CREATE FOREIGN DATA WRAPPER mywrapper
    OPTIONS (debug 'true');
