-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_tsparser.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_tsparser.sgml:90
DROP TEXT SEARCH PARSER my_parser;
