-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/comment.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-comment.sgml:309
COMMENT ON TABLE mytable IS 'This is my table.';

-- ref-comment.sgml:315
COMMENT ON TABLE mytable IS NULL;

-- ref-comment.sgml:323
COMMENT ON ACCESS METHOD gin IS 'GIN index access method';

-- ref-comment.sgml:323
COMMENT ON AGGREGATE my_aggregate (double precision) IS 'Computes sample variance';

-- ref-comment.sgml:323
COMMENT ON CAST (text AS int4) IS 'Allow casts from text to int4';

-- ref-comment.sgml:323
COMMENT ON COLLATION "fr_CA" IS 'Canadian French';

-- ref-comment.sgml:323
COMMENT ON COLUMN my_table.my_column IS 'Employee ID number';

-- ref-comment.sgml:323
COMMENT ON CONVERSION my_conv IS 'Conversion to UTF8';

-- ref-comment.sgml:323
COMMENT ON CONSTRAINT bar_col_cons ON bar IS 'Constrains column col';

-- ref-comment.sgml:323
COMMENT ON CONSTRAINT dom_col_constr ON DOMAIN dom IS 'Constrains col of domain';

-- ref-comment.sgml:323
COMMENT ON DATABASE my_database IS 'Development Database';

-- ref-comment.sgml:323
COMMENT ON DOMAIN my_domain IS 'Email Address Domain';

-- ref-comment.sgml:323
COMMENT ON EVENT TRIGGER abort_ddl IS 'Aborts all DDL commands';

-- ref-comment.sgml:323
COMMENT ON EXTENSION hstore IS 'implements the hstore data type';

-- ref-comment.sgml:323
COMMENT ON FOREIGN DATA WRAPPER mywrapper IS 'my foreign data wrapper';

-- ref-comment.sgml:323
COMMENT ON FOREIGN TABLE my_foreign_table IS 'Employee Information in other database';

-- ref-comment.sgml:323
COMMENT ON FUNCTION my_function (timestamp) IS 'Returns Roman Numeral';

-- ref-comment.sgml:323
COMMENT ON INDEX my_index IS 'Enforces uniqueness on employee ID';

-- ref-comment.sgml:323
COMMENT ON LANGUAGE plpython IS 'Python support for stored procedures';

-- ref-comment.sgml:323
COMMENT ON LARGE OBJECT 346344 IS 'Planning document';

-- ref-comment.sgml:323
COMMENT ON MATERIALIZED VIEW my_matview IS 'Summary of order history';

-- ref-comment.sgml:323
COMMENT ON OPERATOR ^ (text, text) IS 'Performs intersection of two texts';

-- ref-comment.sgml:323
COMMENT ON OPERATOR - (NONE, integer) IS 'Unary minus';

-- ref-comment.sgml:323
COMMENT ON OPERATOR CLASS int4ops USING btree IS '4 byte integer operators for btrees';

-- ref-comment.sgml:323
COMMENT ON OPERATOR FAMILY integer_ops USING btree IS 'all integer operators for btrees';

-- ref-comment.sgml:323
COMMENT ON POLICY my_policy ON mytable IS 'Filter rows by users';

-- ref-comment.sgml:323
COMMENT ON PROCEDURE my_proc (integer, integer) IS 'Runs a report';

-- ref-comment.sgml:323
COMMENT ON PUBLICATION alltables IS 'Publishes all operations on all tables';

-- ref-comment.sgml:323
COMMENT ON ROLE my_role IS 'Administration group for finance tables';

-- ref-comment.sgml:323
COMMENT ON ROUTINE my_routine (integer, integer) IS 'Runs a routine (which is a function or procedure)';

-- ref-comment.sgml:323
COMMENT ON RULE my_rule ON my_table IS 'Logs updates of employee records';

-- ref-comment.sgml:323
COMMENT ON SCHEMA my_schema IS 'Departmental data';

-- ref-comment.sgml:323
COMMENT ON SEQUENCE my_sequence IS 'Used to generate primary keys';

-- ref-comment.sgml:323
COMMENT ON SERVER myserver IS 'my foreign server';

-- ref-comment.sgml:323
COMMENT ON STATISTICS my_statistics IS 'Improves planner row estimations';

-- ref-comment.sgml:323
COMMENT ON SUBSCRIPTION alltables IS 'Subscription for all operations on all tables';

-- ref-comment.sgml:323
COMMENT ON TABLE my_schema.my_table IS 'Employee Information';

-- ref-comment.sgml:323
COMMENT ON TABLESPACE my_tablespace IS 'Tablespace for indexes';

-- ref-comment.sgml:323
COMMENT ON TEXT SEARCH CONFIGURATION my_config IS 'Special word filtering';

-- ref-comment.sgml:323
COMMENT ON TEXT SEARCH DICTIONARY swedish IS 'Snowball stemmer for Swedish language';

-- ref-comment.sgml:323
COMMENT ON TEXT SEARCH PARSER my_parser IS 'Splits text into words';

-- ref-comment.sgml:323
COMMENT ON TEXT SEARCH TEMPLATE snowball IS 'Snowball stemmer';

-- ref-comment.sgml:323
COMMENT ON TRANSFORM FOR hstore LANGUAGE plpython3u IS 'Transform between hstore and Python dict';

-- ref-comment.sgml:323
COMMENT ON TRIGGER my_trigger ON my_table IS 'Used for RI';

-- ref-comment.sgml:323
COMMENT ON TYPE complex IS 'Complex number data type';

-- ref-comment.sgml:323
COMMENT ON VIEW my_view IS 'View of departmental costs';

-- ref-comment.sgml:323
COMMENT ON VIEW my_view IS NULL;
