-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/savepoint.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-savepoint.sgml:114
SELECT * FROM table1;               -- shows rows 1 and 2

-- ref-savepoint.sgml:114
SELECT * FROM table1;               -- shows only row 1
