-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_function.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_function.sgml:320
ALTER FUNCTION sqrt(integer) RENAME TO square_root;

-- ref-alter_function.sgml:328
ALTER FUNCTION sqrt(integer) OWNER TO joe;

-- ref-alter_function.sgml:336
ALTER FUNCTION sqrt(integer) SET SCHEMA maths;

-- ref-alter_function.sgml:345
ALTER FUNCTION sqrt(integer) DEPENDS ON EXTENSION mathlib;

-- ref-alter_function.sgml:352
ALTER FUNCTION check_password(text) SET search_path = admin, pg_temp;

-- ref-alter_function.sgml:359
ALTER FUNCTION check_password(text) RESET search_path;
