-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_user_mapping.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_user_mapping.sgml:93
ALTER USER MAPPING FOR bob SERVER foo OPTIONS (SET password 'public');
