-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_subscription.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_subscription.sgml:439
ALTER SUBSCRIPTION mysub SET PUBLICATION insert_only;

-- ref-alter_subscription.sgml:446
ALTER SUBSCRIPTION mysub DISABLE;
