-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/grant.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-grant.sgml:439
GRANT INSERT ON films TO PUBLIC;

-- ref-grant.sgml:448
GRANT ALL PRIVILEGES ON kinds TO manuel;

-- ref-grant.sgml:461
GRANT admins TO joe;
