-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_table.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_table.sgml:1644
ALTER TABLE distributors ADD COLUMN address varchar(30);

-- ref-alter_table.sgml:1653
ALTER TABLE measurements
  ADD COLUMN mtime timestamp with time zone DEFAULT now();

-- ref-alter_table.sgml:1664
ALTER TABLE transactions
  ADD COLUMN status varchar(30) DEFAULT 'old',
  ALTER COLUMN status SET DEFAULT 'current';

-- ref-alter_table.sgml:1677
ALTER TABLE distributors DROP COLUMN address RESTRICT;

-- ref-alter_table.sgml:1684
ALTER TABLE distributors
    ALTER COLUMN address TYPE varchar(80),
    ALTER COLUMN name TYPE varchar(100);

-- ref-alter_table.sgml:1694
ALTER TABLE foo
    ALTER COLUMN foo_timestamp SET DATA TYPE timestamp with time zone
    USING
        timestamp with time zone 'epoch' + foo_timestamp * interval '1 second';

-- ref-alter_table.sgml:1705
ALTER TABLE foo
    ALTER COLUMN foo_timestamp DROP DEFAULT,
    ALTER COLUMN foo_timestamp TYPE timestamp with time zone
    USING
        timestamp with time zone 'epoch' + foo_timestamp * interval '1 second',
    ALTER COLUMN foo_timestamp SET DEFAULT now();

-- ref-alter_table.sgml:1717
ALTER TABLE distributors RENAME COLUMN address TO city;

-- ref-alter_table.sgml:1724
ALTER TABLE distributors RENAME TO suppliers;

-- ref-alter_table.sgml:1731
ALTER TABLE distributors RENAME CONSTRAINT zipchk TO zip_check;

-- ref-alter_table.sgml:1738
ALTER TABLE distributors ALTER COLUMN street SET NOT NULL;

-- ref-alter_table.sgml:1742
ALTER TABLE distributors ALTER COLUMN street DROP NOT NULL;

-- ref-alter_table.sgml:1749
ALTER TABLE distributors ADD CONSTRAINT zipchk CHECK (char_length(zipcode) = 5);

-- ref-alter_table.sgml:1756
ALTER TABLE distributors ADD CONSTRAINT zipchk CHECK (char_length(zipcode) = 5) NO INHERIT;

-- ref-alter_table.sgml:1764
ALTER TABLE distributors DROP CONSTRAINT zipchk;

-- ref-alter_table.sgml:1771
ALTER TABLE ONLY distributors DROP CONSTRAINT zipchk;

-- ref-alter_table.sgml:1779
ALTER TABLE distributors ADD CONSTRAINT distfk FOREIGN KEY (address) REFERENCES addresses (address);

-- ref-alter_table.sgml:1786
ALTER TABLE distributors ADD CONSTRAINT distfk FOREIGN KEY (address) REFERENCES addresses (address) NOT VALID;

-- ref-alter_table.sgml:1786
ALTER TABLE distributors VALIDATE CONSTRAINT distfk;

-- ref-alter_table.sgml:1794
ALTER TABLE distributors ADD CONSTRAINT dist_id_zipcode_key UNIQUE (dist_id, zipcode);

-- ref-alter_table.sgml:1802
ALTER TABLE distributors ADD PRIMARY KEY (dist_id);

-- ref-alter_table.sgml:1809
ALTER TABLE distributors SET TABLESPACE fasttablespace;

-- ref-alter_table.sgml:1816
ALTER TABLE myschema.distributors SET SCHEMA yourschema;

-- ref-alter_table.sgml:1824
CREATE UNIQUE INDEX CONCURRENTLY dist_id_temp_idx ON distributors (dist_id);

-- ref-alter_table.sgml:1824
ALTER TABLE distributors DROP CONSTRAINT distributors_pkey,
    ADD CONSTRAINT distributors_pkey PRIMARY KEY USING INDEX dist_id_temp_idx;

-- ref-alter_table.sgml:1832
ALTER TABLE measurement
    ATTACH PARTITION measurement_y2016m07 FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');

-- ref-alter_table.sgml:1839
ALTER TABLE cities
    ATTACH PARTITION cities_ab FOR VALUES IN ('a', 'b');

-- ref-alter_table.sgml:1846
ALTER TABLE orders
    ATTACH PARTITION orders_p4 FOR VALUES WITH (MODULUS 4, REMAINDER 3);

-- ref-alter_table.sgml:1853
ALTER TABLE cities
    ATTACH PARTITION cities_partdef DEFAULT;

-- ref-alter_table.sgml:1860
ALTER TABLE measurement
    DETACH PARTITION measurement_y2015m12;
