-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/import_foreign_schema.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-import_foreign_schema.sgml:131
IMPORT FOREIGN SCHEMA foreign_films
    FROM SERVER film_server INTO films;

-- ref-import_foreign_schema.sgml:141
IMPORT FOREIGN SCHEMA foreign_films LIMIT TO (actors, directors)
    FROM SERVER film_server INTO films;
