-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_sequence.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_sequence.sgml:339
ALTER SEQUENCE serial RESTART WITH 105;
