-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_opfamily.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_opfamily.sgml:107
DROP OPERATOR FAMILY float_ops USING btree;
