-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/discard.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-discard.sgml:86
CLOSE ALL;

-- ref-discard.sgml:86
SET SESSION AUTHORIZATION DEFAULT;

-- ref-discard.sgml:86
RESET ALL;

-- ref-discard.sgml:86
DEALLOCATE ALL;

-- ref-discard.sgml:86
UNLISTEN *;

-- ref-discard.sgml:86
SELECT pg_advisory_unlock_all();

-- ref-discard.sgml:86
DISCARD PLANS;

-- ref-discard.sgml:86
DISCARD TEMP;

-- ref-discard.sgml:86
DISCARD SEQUENCES;
