-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/rollback_to.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-rollback_to.sgml:101
ROLLBACK TO SAVEPOINT my_savepoint;

-- ref-rollback_to.sgml:108
DECLARE foo CURSOR FOR SELECT 1 UNION SELECT 2;

-- ref-rollback_to.sgml:108
SAVEPOINT foo;

-- ref-rollback_to.sgml:108
FETCH 1 FROM foo;

-- ref-rollback_to.sgml:108
ROLLBACK TO SAVEPOINT foo;
