-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/copy.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-copy.sgml:249
COPY (SELECT j FROM (VALUES ('null'::json), (NULL::json)) v(j))
     TO stdout (FORMAT JSON);

-- ref-copy.sgml:1132
COPY country TO STDOUT (DELIMITER '|');

-- ref-copy.sgml:1140
COPY (SELECT * FROM (VALUES(1),(2)) val(id)) TO STDOUT  (FORMAT JSON, FORCE_ARRAY);

-- ref-copy.sgml:1155
COPY country FROM '/usr1/proj/bray/sql/country_data';

-- ref-copy.sgml:1162
COPY (SELECT * FROM country WHERE country_name LIKE 'A%') TO '/usr1/proj/bray/sql/a_list_countries.copy';

-- ref-copy.sgml:1170
COPY country TO PROGRAM 'gzip > /usr1/proj/bray/sql/country_data.gz';
