-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_index.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_index.sgml:903
CREATE UNIQUE INDEX title_idx ON films (title);

-- ref-create_index.sgml:912
CREATE UNIQUE INDEX title_idx ON films (title) INCLUDE (director, rating);

-- ref-create_index.sgml:919
CREATE INDEX title_idx ON films (title) WITH (deduplicate_items = off);

-- ref-create_index.sgml:927
CREATE INDEX ON films ((lower(title)));

-- ref-create_index.sgml:936
CREATE INDEX title_idx_german ON films (title COLLATE "de_DE");

-- ref-create_index.sgml:943
CREATE INDEX title_idx_nulls_low ON films (title NULLS FIRST);

-- ref-create_index.sgml:950
CREATE UNIQUE INDEX title_idx ON films (title) WITH (fillfactor = 70);

-- ref-create_index.sgml:957
CREATE INDEX gin_idx ON documents_table USING GIN (locations) WITH (fastupdate = off);

-- ref-create_index.sgml:966
CREATE INDEX code_idx ON films (code) TABLESPACE indexspace;

-- ref-create_index.sgml:975
CREATE INDEX pointloc
    ON points USING gist (box(location,location));

-- ref-create_index.sgml:975
SELECT * FROM points
    WHERE box(location,location) && '(0,0),(1,1)'::box;

-- ref-create_index.sgml:985
CREATE INDEX CONCURRENTLY sales_quantity_index ON sales_table (quantity);
