-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_conversion.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_conversion.sgml:81
DROP CONVERSION myname;
