-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_language.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_language.sgml:216
CREATE FUNCTION plsample_call_handler() RETURNS language_handler
    AS '$libdir/plsample'
    LANGUAGE C;

-- ref-create_language.sgml:216
CREATE LANGUAGE plsample
    HANDLER plsample_call_handler;

-- ref-create_language.sgml:225
CREATE EXTENSION plsample;
