-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/declare.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-declare.sgml:336
DECLARE liahona CURSOR FOR SELECT * FROM films;
