-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_materialized_view.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_materialized_view.sgml:92
DROP MATERIALIZED VIEW order_summary;
