-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/set.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-set.sgml:287
SET search_path TO my_schema, public;

-- ref-set.sgml:291
SET search_path TO 'my_schema, public';

-- ref-set.sgml:300
SET temp_tablespaces TO NULL;

-- ref-set.sgml:309
SET datestyle TO postgres, dmy;

-- ref-set.sgml:316
SET TIME ZONE 'America/Los_Angeles';

-- ref-set.sgml:323
SET TIME ZONE 'Europe/Rome';
