-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_tablespace.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_tablespace.sgml:111
ALTER TABLESPACE index_space RENAME TO fast_raid;

-- ref-alter_tablespace.sgml:118
ALTER TABLESPACE index_space OWNER TO mary;
