-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_conversion.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_conversion.sgml:98
ALTER CONVERSION iso_8859_1_to_utf8 RENAME TO latin1_to_unicode;

-- ref-alter_conversion.sgml:106
ALTER CONVERSION iso_8859_1_to_utf8 OWNER TO joe;
