-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_role.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_role.sgml:432
CREATE ROLE jonathan LOGIN;

-- ref-create_role.sgml:439
CREATE USER davide WITH PASSWORD 'jw8s0F4';

-- ref-create_role.sgml:451
CREATE ROLE miriam WITH LOGIN PASSWORD 'jw8s0F4' VALID UNTIL '2005-01-01';

-- ref-create_role.sgml:458
CREATE ROLE admin WITH CREATEDB CREATEROLE;
