-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_routine.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_routine.sgml:68
ALTER ROUTINE foo(integer) RENAME TO foobar;
