-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_type.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_type.sgml:424
ALTER TYPE electronic_mail RENAME TO email;

-- ref-alter_type.sgml:432
ALTER TYPE email OWNER TO joe;

-- ref-alter_type.sgml:440
ALTER TYPE email SET SCHEMA customers;

-- ref-alter_type.sgml:447
ALTER TYPE compfoo ADD ATTRIBUTE f3 int;

-- ref-alter_type.sgml:454
ALTER TYPE colors ADD VALUE 'orange' AFTER 'red';

-- ref-alter_type.sgml:461
ALTER TYPE colors RENAME VALUE 'purple' TO 'mauve';

-- ref-alter_type.sgml:468
ALTER TYPE mytype SET (
    SEND = mytypesend,
    RECEIVE = mytyperecv
);
