-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_procedure.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_procedure.sgml:218
ALTER PROCEDURE insert_data(integer, integer) RENAME TO insert_record;

-- ref-alter_procedure.sgml:226
ALTER PROCEDURE insert_data(integer, integer) OWNER TO joe;

-- ref-alter_procedure.sgml:235
ALTER PROCEDURE insert_data(integer, integer) SET SCHEMA accounting;

-- ref-alter_procedure.sgml:243
ALTER PROCEDURE insert_data(integer, integer) DEPENDS ON EXTENSION myext;

-- ref-alter_procedure.sgml:250
ALTER PROCEDURE check_password(text) SET search_path = admin, pg_temp;

-- ref-alter_procedure.sgml:257
ALTER PROCEDURE check_password(text) RESET search_path;
