-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_index.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_index.sgml:282
ALTER INDEX distributors RENAME TO suppliers;

-- ref-alter_index.sgml:289
ALTER INDEX distributors SET TABLESPACE fasttablespace;

-- ref-alter_index.sgml:297
ALTER INDEX distributors SET (fillfactor = 75);

-- ref-alter_index.sgml:297
REINDEX INDEX distributors;

-- ref-alter_index.sgml:304
CREATE INDEX coord_idx ON measured (x, y, (z + t));

-- ref-alter_index.sgml:304
ALTER INDEX coord_idx ALTER COLUMN 3 SET STATISTICS 1000;
