-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_server.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_server.sgml:94
DROP SERVER IF EXISTS foo;
