-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_collation.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_collation.sgml:247
CREATE COLLATION french (locale = 'fr_FR.utf8');

-- ref-create_collation.sgml:254
CREATE COLLATION german_phonebook (provider = icu, locale = 'de-u-co-phonebk');
