-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_extension.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_extension.sgml:221
CREATE EXTENSION hstore SCHEMA addons;

-- ref-create_extension.sgml:225
SET search_path = addons;

-- ref-create_extension.sgml:225
CREATE EXTENSION hstore;
