-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/pg_rewind.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-pg_rewind.sgml:375
CREATE USER rewind_user LOGIN;

-- ref-pg_rewind.sgml:375
GRANT EXECUTE ON FUNCTION pg_catalog.pg_ls_dir(text, boolean, boolean) TO rewind_user;

-- ref-pg_rewind.sgml:375
GRANT EXECUTE ON FUNCTION pg_catalog.pg_stat_file(text, boolean) TO rewind_user;

-- ref-pg_rewind.sgml:375
GRANT EXECUTE ON FUNCTION pg_catalog.pg_read_binary_file(text) TO rewind_user;

-- ref-pg_rewind.sgml:375
GRANT EXECUTE ON FUNCTION pg_catalog.pg_read_binary_file(text, bigint, bigint, boolean) TO rewind_user;
