-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_tsconfig.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_tsconfig.sgml:166
ALTER TEXT SEARCH CONFIGURATION my_config
  ALTER MAPPING REPLACE english WITH swedish;
