-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/set_transaction.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-set_transaction.sgml:239
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- ref-set_transaction.sgml:239
SELECT pg_export_snapshot();

-- ref-set_transaction.sgml:252
SET TRANSACTION SNAPSHOT '00000003-0000001B-1';
