-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_language.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_language.sgml:102
DROP LANGUAGE plsample;
