-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/notify.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-notify.sgml:203
NOTIFY virtual, 'This is the payload';

-- ref-notify.sgml:203
LISTEN foo;

-- ref-notify.sgml:203
SELECT pg_notify('fo' || 'o', 'pay' || 'load');
