-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/lock.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-lock.sgml:227
LOCK TABLE films IN SHARE MODE;

-- ref-lock.sgml:227
SELECT id FROM films
    WHERE name = 'Star Wars: Episode I - The Phantom Menace';

-- ref-lock.sgml:227
INSERT INTO films_user_comments VALUES
    (_id_, 'GREAT! I was waiting for it for so long!');

-- ref-lock.sgml:243
LOCK TABLE films IN SHARE ROW EXCLUSIVE MODE;

-- ref-lock.sgml:243
DELETE FROM films_user_comments WHERE id IN
    (SELECT id FROM films WHERE rating < 5);

-- ref-lock.sgml:243
DELETE FROM films WHERE rating < 5;
