-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_schema.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_schema.sgml:105
DROP SCHEMA mystuff CASCADE;
