-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_trigger.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_trigger.sgml:119
ALTER TRIGGER emp_stamp ON emp RENAME TO emp_track_chgs;

-- ref-alter_trigger.sgml:125
ALTER TRIGGER emp_stamp ON emp DEPENDS ON EXTENSION emplib;
