-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/commit_prepared.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-commit_prepared.sgml:80
COMMIT PREPARED 'foobar';
