-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/rollback_prepared.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-rollback_prepared.sgml:80
ROLLBACK PREPARED 'foobar';
