-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_function.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_function.sgml:136
DROP FUNCTION sqrt(integer);

-- ref-drop_function.sgml:142
DROP FUNCTION sqrt(integer), sqrt(bigint);

-- ref-drop_function.sgml:149
DROP FUNCTION update_employee_salaries;

-- ref-drop_function.sgml:153
DROP FUNCTION update_employee_salaries();
