-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_database.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_database.sgml:232
ALTER DATABASE test SET enable_indexscan TO off;
