-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/set_role.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-set_role.sgml:119
SELECT SESSION_USER, CURRENT_USER;

-- ref-set_role.sgml:119
SET ROLE 'paul';
