-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_group.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_group.sgml:109
ALTER GROUP staff ADD USER karl, john;

-- ref-alter_group.sgml:115
ALTER GROUP workers DROP USER beth;
