-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/reindex.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-reindex.sgml:525
REINDEX INDEX my_index;

-- ref-reindex.sgml:533
REINDEX TABLE my_table;

-- ref-reindex.sgml:554
REINDEX TABLE CONCURRENTLY my_broken_table;
