-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_collation.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_collation.sgml:90
DROP COLLATION german;
