-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_publication.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_publication.sgml:253
ALTER PUBLICATION noinsert SET (publish = 'update, delete');

-- ref-alter_publication.sgml:260
ALTER PUBLICATION mypublication ADD TABLE users (user_id, firstname), departments;

-- ref-alter_publication.sgml:266
ALTER PUBLICATION mypublication SET TABLE users (user_id, firstname, lastname), TABLE departments;

-- ref-alter_publication.sgml:272
ALTER PUBLICATION mypublication SET ALL TABLES EXCEPT (TABLE users, departments);

-- ref-alter_publication.sgml:279
ALTER PUBLICATION mypublication SET ALL TABLES;

-- ref-alter_publication.sgml:287
ALTER PUBLICATION sales_publication ADD TABLES IN SCHEMA marketing, sales;

-- ref-alter_publication.sgml:297
ALTER PUBLICATION production_publication ADD TABLE users, departments, TABLES IN SCHEMA production;
