-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_operator.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_operator.sgml:196
ALTER OPERATOR @@ (text, text) OWNER TO joe;

-- ref-alter_operator.sgml:205
ALTER OPERATOR && (int[], int[]) SET (RESTRICT = _int_contsel, JOIN = _int_contjoinsel);

-- ref-alter_operator.sgml:213
ALTER OPERATOR && (int[], int[]) SET (COMMUTATOR = &&);
