-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/release_savepoint.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-release_savepoint.sgml:87
INSERT INTO table1 VALUES (3);

-- ref-release_savepoint.sgml:87
INSERT INTO table1 VALUES (4);

-- ref-release_savepoint.sgml:87
RELEASE SAVEPOINT my_savepoint;

-- ref-release_savepoint.sgml:100
INSERT INTO table1 VALUES (1);

-- ref-release_savepoint.sgml:100
SAVEPOINT sp1;

-- ref-release_savepoint.sgml:100
INSERT INTO table1 VALUES (2);

-- ref-release_savepoint.sgml:100
SAVEPOINT sp2;

-- ref-release_savepoint.sgml:100
RELEASE SAVEPOINT sp2;

-- ref-release_savepoint.sgml:118
ROLLBACK TO SAVEPOINT sp1;
