-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_server.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_server.sgml:112
ALTER SERVER foo OPTIONS (host 'foo', dbname 'foodb');

-- ref-alter_server.sgml:120
ALTER SERVER foo VERSION '8.4' OPTIONS (SET host 'baz');
