-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/do.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-do.sgml:108
DO $$DECLARE r record;
BEGIN
    FOR r IN SELECT table_schema, table_name FROM information_schema.tables
             WHERE table_type = 'VIEW' AND table_schema = 'public'
    LOOP
        EXECUTE 'GRANT ALL ON ' || quote_ident(r.table_schema) || '.' || quote_ident(r.table_name) || ' TO webuser';
    END LOOP;
END$$;
