-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_rule.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_rule.sgml:254
CREATE RULE "_RETURN" AS
    ON SELECT TO t1
    DO INSTEAD
        SELECT * FROM t2;

-- ref-create_rule.sgml:254
CREATE RULE "_RETURN" AS
    ON SELECT TO t2
    DO INSTEAD
        SELECT * FROM t1;

-- ref-create_rule.sgml:254
SELECT * FROM t1;

-- ref-create_rule.sgml:275
CREATE RULE notify_me AS ON UPDATE TO mytable DO ALSO NOTIFY mytable;

-- ref-create_rule.sgml:275
UPDATE mytable SET name = 'foo' WHERE id = 42;
