-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_conversion.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_conversion.sgml:160
CREATE CONVERSION myconv FOR 'UTF8' TO 'LATIN1' FROM myfunc;
