-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_tstemplate.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_tstemplate.sgml:91
DROP TEXT SEARCH TEMPLATE thesaurus;
