-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_opclass.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_opclass.sgml:120
DROP OPERATOR CLASS widget_ops USING btree;
