-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_rule.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_rule.sgml:99
DROP RULE newrule ON mytable;
