-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/psql-ref.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-psql-ref.sgml:137
SELECT * FROM foo;

-- ref-psql-ref.sgml:2768
SELECT * FROM employee WHERE employee_id = 456;

-- ref-psql-ref.sgml:3793
SELECT * FROM pg_class;

-- ref-psql-ref.sgml:4034
SELECT 1; SELECT 2; SELECT 3;
