-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/move.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-move.sgml:86
MOVE FORWARD 5 IN liahona;

-- ref-move.sgml:86
FETCH 1 FROM liahona;
