-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/update.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-update.sgml:367
UPDATE films SET kind = 'Dramatic' WHERE kind = 'Drama';

-- ref-update.sgml:376
UPDATE weather SET temp_lo = temp_lo+1, temp_hi = temp_lo+15, prcp = DEFAULT
  WHERE city = 'San Francisco' AND date = '2003-07-03';

-- ref-update.sgml:386
UPDATE weather SET temp_lo = temp_lo+1, temp_hi = temp_lo+15, prcp = DEFAULT
  WHERE city = 'San Francisco' AND date = '2003-07-03'
  RETURNING temp_lo, temp_hi, prcp, old.prcp AS old_prcp;

-- ref-update.sgml:395
UPDATE weather SET (temp_lo, temp_hi, prcp) = (temp_lo+1, temp_lo+15, DEFAULT)
  WHERE city = 'San Francisco' AND date = '2003-07-03';

-- ref-update.sgml:405
UPDATE employees SET sales_count = sales_count + 1 FROM accounts
  WHERE accounts.name = 'Acme Corporation'
  AND employees.id = accounts.sales_person;

-- ref-update.sgml:415
UPDATE employees SET sales_count = sales_count + 1 WHERE id =
  (SELECT sales_person FROM accounts WHERE name = 'Acme Corporation');

-- ref-update.sgml:424
UPDATE accounts SET (contact_first_name, contact_last_name) =
    (SELECT first_name, last_name FROM employees
     WHERE employees.id = accounts.sales_person);

-- ref-update.sgml:430
UPDATE accounts SET contact_first_name = first_name,
                    contact_last_name = last_name
  FROM employees WHERE employees.id = accounts.sales_person;

-- ref-update.sgml:446
UPDATE summary s SET (sum_x, sum_y, avg_x, avg_y) =
    (SELECT sum(x), sum(y), avg(x), avg(y) FROM data d
     WHERE d.group_id = s.group_id);

-- ref-update.sgml:457
INSERT INTO wines VALUES('Chateau Lafite 2003', '24');

-- ref-update.sgml:457
ROLLBACK TO sp1;

-- ref-update.sgml:457
UPDATE wines SET stock = stock + 24 WHERE winename = 'Chateau Lafite 2003';

-- ref-update.sgml:475
UPDATE films SET kind = 'Dramatic' WHERE CURRENT OF c_films;

-- ref-update.sgml:493
WITH exceeded_max_retries AS (
  SELECT w.ctid FROM work_item AS w
    WHERE w.status = 'active' AND w.num_retries > 10
    ORDER BY w.retry_timestamp
    FOR UPDATE
    LIMIT 5000
)
UPDATE work_item SET status = 'failed'
  FROM exceeded_max_retries AS emr
  WHERE work_item.ctid = emr.ctid;
