-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_domain.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_domain.sgml:203
INSERT INTO tab (domcol) VALUES ((SELECT domcol FROM tab WHERE false));

-- ref-create_domain.sgml:257
CREATE DOMAIN us_postal_code AS TEXT
CHECK(
   VALUE ~ '^\d{5}$'
OR VALUE ~ '^\d{5}-\d{4}$'
);

-- ref-create_domain.sgml:257
CREATE TABLE us_snail_addy (
  address_id SERIAL PRIMARY KEY,
  street1 TEXT NOT NULL,
  street2 TEXT,
  street3 TEXT,
  city TEXT NOT NULL,
  postal us_postal_code NOT NULL
);
