-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_aggregate.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_aggregate.sgml:145
DROP AGGREGATE myavg(integer);

-- ref-drop_aggregate.sgml:154
DROP AGGREGATE myrank(VARIADIC "any" ORDER BY VARIADIC "any");

-- ref-drop_aggregate.sgml:161
DROP AGGREGATE myavg(integer), myavg(bigint);
