-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_foreign_data_wrapper.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_foreign_data_wrapper.sgml:175
ALTER FOREIGN DATA WRAPPER dbi OPTIONS (ADD foo '1', DROP bar);

-- ref-alter_foreign_data_wrapper.sgml:183
ALTER FOREIGN DATA WRAPPER dbi VALIDATOR bob.myvalidator;
