-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/pg_dump.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-pg_dump.sgml:1665
CREATE DATABASE foo WITH TEMPLATE template0;
