-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_role.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_role.sgml:287
ALTER ROLE davide WITH PASSWORD 'hu8jmn3';

-- ref-alter_role.sgml:295
ALTER ROLE davide WITH PASSWORD NULL;

-- ref-alter_role.sgml:304
ALTER ROLE chris VALID UNTIL 'May 4 12:00:00 2015 +1';

-- ref-alter_role.sgml:311
ALTER ROLE fred VALID UNTIL 'infinity';

-- ref-alter_role.sgml:319
ALTER ROLE miriam CREATEROLE CREATEDB;

-- ref-alter_role.sgml:328
ALTER ROLE worker_bee SET maintenance_work_mem = 100000;

-- ref-alter_role.sgml:337
ALTER ROLE fred IN DATABASE devel SET client_min_messages = DEBUG;
