-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/refresh_materialized_view.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-refresh_materialized_view.sgml:117
REFRESH MATERIALIZED VIEW order_summary;

-- ref-refresh_materialized_view.sgml:126
REFRESH MATERIALIZED VIEW annual_statistics_basis WITH NO DATA;
