-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/wait.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-wait.sgml:391
UPDATE movie SET genre = 'Dramatic' WHERE genre = 'Drama';

-- ref-wait.sgml:406
SELECT * FROM movie WHERE genre = 'Drama';
