-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/truncate.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-truncate.sgml:188
TRUNCATE bigtable, fattable;

-- ref-truncate.sgml:196
TRUNCATE bigtable, fattable RESTART IDENTITY;

-- ref-truncate.sgml:206
TRUNCATE othertable CASCADE;
