-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/alter_materialized_view.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-alter_materialized_view.sgml:164
ALTER MATERIALIZED VIEW foo RENAME TO bar;
