-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_access_method.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_access_method.sgml:98
CREATE ACCESS METHOD heptree TYPE INDEX HANDLER heptree_handler;
