-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_tablespace.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_tablespace.sgml:87
DROP TABLESPACE mystuff;
