-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_event_trigger.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_event_trigger.sgml:91
DROP EVENT TRIGGER snitch;
