-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_type.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_type.sgml:927
CREATE TYPE compfoo AS (f1 int, f2 text);

-- ref-create_type.sgml:927
CREATE FUNCTION getfoo() RETURNS SETOF compfoo AS $$
    SELECT fooid, fooname FROM foo
$$ LANGUAGE SQL;

-- ref-create_type.sgml:939
CREATE TYPE bug_status AS ENUM ('new', 'open', 'closed');

-- ref-create_type.sgml:939
CREATE TABLE bug (
    id serial,
    description text,
    status bug_status
);

-- ref-create_type.sgml:952
CREATE TYPE float8_range AS RANGE (subtype = float8, subtype_diff = float8mi);

-- ref-create_type.sgml:960
CREATE TYPE box;

-- ref-create_type.sgml:960
CREATE TYPE box (
    INTERNALLENGTH = 16,
    INPUT = my_box_in_function,
    OUTPUT = my_box_out_function
);

-- ref-create_type.sgml:960
CREATE TABLE myboxes (
    id integer,
    description box
);

-- ref-create_type.sgml:982
CREATE TYPE box (
    INTERNALLENGTH = 16,
    INPUT = my_box_in_function,
    OUTPUT = my_box_out_function,
    ELEMENT = float4
);

-- ref-create_type.sgml:997
CREATE TYPE bigobj (
    INPUT = lo_filein, OUTPUT = lo_fileout,
    INTERNALLENGTH = VARIABLE
);

-- ref-create_type.sgml:997
CREATE TABLE big_objs (
    id integer,
    obj bigobj
);
