-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/select.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-select.sgml:1214
SELECT DISTINCT ON (location) location, time, report
    FROM weather_reports
    ORDER BY location, time DESC;

-- ref-select.sgml:1421
SELECT name FROM distributors ORDER BY code;

-- ref-select.sgml:1680
SELECT * FROM (SELECT * FROM mytable FOR UPDATE) ss WHERE col1 = 5;

-- ref-select.sgml:1690
SELECT * FROM mytable WHERE key = 1 FOR UPDATE;

-- ref-select.sgml:1690
SAVEPOINT s;

-- ref-select.sgml:1690
ROLLBACK TO s;

-- ref-select.sgml:1714
SELECT * FROM (SELECT * FROM mytable FOR UPDATE) ss ORDER BY column1;

-- ref-select.sgml:1766
SELECT f.title, f.did, d.name, f.date_prod, f.kind
    FROM distributors d JOIN films f USING (did);

-- ref-select.sgml:1782
SELECT kind, sum(len) AS total FROM films GROUP BY kind;

-- ref-select.sgml:1800
SELECT kind, sum(len) AS total
    FROM films
    GROUP BY kind
    HAVING sum(len) < interval '5 hours';

-- ref-select.sgml:1818
SELECT * FROM distributors ORDER BY name;

-- ref-select.sgml:1818
SELECT * FROM distributors ORDER BY 2;

-- ref-select.sgml:1847
SELECT distributors.name
    FROM distributors
    WHERE distributors.name LIKE 'W%'
UNION
SELECT actors.name
    FROM actors
    WHERE actors.name LIKE 'W%';

-- ref-select.sgml:1879
CREATE FUNCTION distributors(int) RETURNS SETOF distributors AS $$
    SELECT * FROM distributors WHERE did = $1;
$$ LANGUAGE SQL;

-- ref-select.sgml:1879
SELECT * FROM distributors(111);

-- ref-select.sgml:1879
CREATE FUNCTION distributors_2(int) RETURNS SETOF record AS $$
    SELECT * FROM distributors WHERE did = $1;
$$ LANGUAGE SQL;

-- ref-select.sgml:1879
SELECT * FROM distributors_2(111) AS (f1 int, f2 text);

-- ref-select.sgml:1903
SELECT * FROM unnest(ARRAY['a','b','c','d','e','f']) WITH ORDINALITY;

-- ref-select.sgml:1920
WITH t AS (
    SELECT random() AS x FROM generate_series(1, 3)
  )
SELECT * FROM t
UNION ALL
SELECT * FROM t;

-- ref-select.sgml:1947
WITH RECURSIVE employee_recursive(distance, employee_name, manager_name) AS (
    SELECT 1, employee_name, manager_name
    FROM employee
    WHERE manager_name = 'Mary'
  UNION ALL
    SELECT er.distance + 1, e.employee_name, e.manager_name
    FROM employee_recursive er, employee e
    WHERE er.employee_name = e.manager_name
  )
SELECT distance, employee_name FROM employee_recursive;

-- ref-select.sgml:1973
SELECT m.name AS mname, pname
FROM manufacturers m, LATERAL get_product_names(m.id) pname;

-- ref-select.sgml:1982
SELECT m.name AS mname, pname
FROM manufacturers m LEFT JOIN LATERAL get_product_names(m.id) pname ON true;

-- ref-select.sgml:2004
SELECT 2+2;
