-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_tsdictionary.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_tsdictionary.sgml:92
DROP TEXT SEARCH DICTIONARY english;
