-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/drop_subscription.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-drop_subscription.sgml:126
DROP SUBSCRIPTION mysub;
