-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_cast.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_cast.sgml:45
SELECT CAST(42 AS float8);

-- ref-create_cast.sgml:92
INSERT INTO foo (f1) VALUES (42);

-- ref-create_cast.sgml:107
SELECT 2 + 4.0;

-- ref-create_cast.sgml:118
SELECT CAST ( 2 AS numeric ) + 4.0;

-- ref-create_cast.sgml:393
CREATE CAST (bigint AS int4) WITH FUNCTION int4(bigint) AS ASSIGNMENT;
