-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_publication.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_publication.sgml:472
CREATE PUBLICATION mypublication FOR TABLE users, departments;

-- ref-create_publication.sgml:479
CREATE PUBLICATION active_departments FOR TABLE departments WHERE (active IS TRUE);

-- ref-create_publication.sgml:486
CREATE PUBLICATION alltables FOR ALL TABLES;

-- ref-create_publication.sgml:494
CREATE PUBLICATION insert_only FOR TABLE mydata
    WITH (publish = 'insert');

-- ref-create_publication.sgml:505
CREATE PUBLICATION production_publication FOR TABLE users, departments, TABLES IN SCHEMA production;

-- ref-create_publication.sgml:514
CREATE PUBLICATION sales_publication FOR TABLES IN SCHEMA marketing, sales;

-- ref-create_publication.sgml:522
CREATE PUBLICATION users_filtered FOR TABLE users (user_id, firstname);

-- ref-create_publication.sgml:528
CREATE PUBLICATION all_sequences FOR ALL SEQUENCES;

-- ref-create_publication.sgml:536
CREATE PUBLICATION all_tables_sequences FOR ALL TABLES, ALL SEQUENCES;

-- ref-create_publication.sgml:544
CREATE PUBLICATION all_tables_except FOR ALL TABLES EXCEPT (TABLE users, departments);

-- ref-create_publication.sgml:553
CREATE PUBLICATION all_sequences_tables_except FOR ALL SEQUENCES, ALL TABLES EXCEPT (TABLE users, departments);
