-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/delete.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-delete.sgml:260
DELETE FROM films USING producers
  WHERE producer_id = producers.id AND producers.name = 'foo';

-- ref-delete.sgml:268
DELETE FROM films
  WHERE producer_id IN (SELECT id FROM producers WHERE name = 'foo');

-- ref-delete.sgml:282
DELETE FROM films WHERE kind <> 'Musical';

-- ref-delete.sgml:289
DELETE FROM films;

-- ref-delete.sgml:296
DELETE FROM tasks WHERE status = 'DONE' RETURNING *;

-- ref-delete.sgml:304
DELETE FROM tasks WHERE CURRENT OF c_tasks;

-- ref-delete.sgml:314
WITH delete_batch AS (
  SELECT l.ctid FROM user_logs AS l
    WHERE l.status = 'archived'
    ORDER BY l.creation_date
    FOR UPDATE
    LIMIT 10000
)
DELETE FROM user_logs AS dl
  USING delete_batch AS del
  WHERE dl.ctid = del.ctid;
