-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/create_sequence.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-create_sequence.sgml:339
CREATE SEQUENCE serial START 101;

-- ref-create_sequence.sgml:346
SELECT nextval('serial');

-- ref-create_sequence.sgml:368
INSERT INTO distributors VALUES (nextval('serial'), 'nothing');

-- ref-create_sequence.sgml:375
COPY distributors FROM 'input_file';

-- ref-create_sequence.sgml:375
SELECT setval('serial', max(id)) FROM distributors;
