-- Generated by script/extract-doc-sql.js from doc/src/sgml/ref/vacuum.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- ref-vacuum.sgml:506
VACUUM (VERBOSE, ANALYZE) onek;
