-- Generated by script/extract-doc-sql.js from doc/src/sgml/rowtypes.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- rowtypes.sgml:27
CREATE TYPE complex AS (
    r       double precision,
    i       double precision
);

-- rowtypes.sgml:27
CREATE TYPE inventory_item AS (
    name            text,
    supplier_id     integer,
    price           numeric
);

-- rowtypes.sgml:50
CREATE TABLE on_hand (
    item      inventory_item,
    count     integer
);

-- rowtypes.sgml:50
INSERT INTO on_hand VALUES (ROW('fuzzy dice', 42, 1.99), 1000);

-- rowtypes.sgml:61
CREATE FUNCTION price_extension(inventory_item, integer) RETURNS numeric
AS 'SELECT $1.price * $2' LANGUAGE SQL;

-- rowtypes.sgml:61
SELECT price_extension(item, 10) FROM on_hand;

-- rowtypes.sgml:74
CREATE TABLE inventory_item (
    name            text,
    supplier_id     integer REFERENCES suppliers,
    price           numeric CHECK (price > 0)
);

-- rowtypes.sgml:171
SELECT item.name FROM on_hand WHERE item.price > 9.99;

-- rowtypes.sgml:179
SELECT (item).name FROM on_hand WHERE (item).price > 9.99;

-- rowtypes.sgml:186
SELECT (on_hand.item).name FROM on_hand WHERE (on_hand.item).price > 9.99;

-- rowtypes.sgml:220
INSERT INTO mytab (complex_col) VALUES((1.1,2.2));

-- rowtypes.sgml:246
INSERT INTO mytab (complex_col.r, complex_col.i) VALUES(1.1, 2.2);

-- rowtypes.sgml:270
SELECT c FROM inventory_item c;

-- rowtypes.sgml:296
SELECT c.* FROM inventory_item c;

-- rowtypes.sgml:308
SELECT c.name, c.supplier_id, c.price FROM inventory_item c;

-- rowtypes.sgml:319
SELECT (myfunc(x)).* FROM some_table;

-- rowtypes.sgml:319
SELECT (myfunc(x)).a, (myfunc(x)).b, (myfunc(x)).c FROM some_table;

-- rowtypes.sgml:332
SELECT m.* FROM some_table, LATERAL myfunc(x) AS m;

-- rowtypes.sgml:361
SELECT somefunc(c.*) FROM inventory_item c;

-- rowtypes.sgml:361
SELECT somefunc(c) FROM inventory_item c;

-- rowtypes.sgml:381
SELECT * FROM inventory_item c ORDER BY c;

-- rowtypes.sgml:381
SELECT * FROM inventory_item c ORDER BY c.*;

-- rowtypes.sgml:381
SELECT * FROM inventory_item c ORDER BY ROW(c.*);

-- rowtypes.sgml:393
SELECT * FROM inventory_item c ORDER BY ROW(c.name, c.supplier_id, c.price);

-- rowtypes.sgml:393
SELECT * FROM inventory_item c ORDER BY (c.name, c.supplier_id, c.price);

-- rowtypes.sgml:409
SELECT c.name FROM inventory_item c WHERE c.price > 1000;

-- rowtypes.sgml:409
SELECT name(c) FROM inventory_item c WHERE price(c) > 1000;

-- rowtypes.sgml:418
SELECT c.somefunc FROM inventory_item c;
