-- Generated by script/extract-doc-sql.js from doc/src/sgml/rules.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- rules.sgml:289
CREATE VIEW myview AS SELECT * FROM mytab;

-- rules.sgml:355
CREATE TABLE shoe_data (
    shoename   text,          -- primary key
    sh_avail   integer,       -- available number of pairs
    slcolor    text,          -- preferred shoelace color
    slminlen   real,          -- minimum shoelace length
    slmaxlen   real,          -- maximum shoelace length
    slunit     text           -- length unit
);

-- rules.sgml:355
CREATE TABLE shoelace_data (
    sl_name    text,          -- primary key
    sl_avail   integer,       -- available number of pairs
    sl_color   text,          -- shoelace color
    sl_len     real,          -- shoelace length
    sl_unit    text           -- length unit
);

-- rules.sgml:355
CREATE TABLE unit (
    un_name    text,          -- primary key
    un_fact    real           -- factor to transform to cm
);

-- rules.sgml:385
CREATE VIEW shoe AS
    SELECT sh.shoename,
           sh.sh_avail,
           sh.slcolor,
           sh.slminlen,
           sh.slminlen * un.un_fact AS slminlen_cm,
           sh.slmaxlen,
           sh.slmaxlen * un.un_fact AS slmaxlen_cm,
           sh.slunit
      FROM shoe_data sh, unit un
     WHERE sh.slunit = un.un_name;

-- rules.sgml:385
CREATE VIEW shoelace AS
    SELECT s.sl_name,
           s.sl_avail,
           s.sl_color,
           s.sl_len,
           s.sl_unit,
           s.sl_len * u.un_fact AS sl_len_cm
      FROM shoelace_data s, unit u
     WHERE s.sl_unit = u.un_name;

-- rules.sgml:385
CREATE VIEW shoe_ready AS
    SELECT rsh.shoename,
           rsh.sh_avail,
           rsl.sl_name,
           rsl.sl_avail,
           least(rsh.sh_avail, rsl.sl_avail) AS total_avail
      FROM shoe rsh, shoelace rsl
     WHERE rsl.sl_color = rsh.slcolor
       AND rsl.sl_len_cm >= rsh.slminlen_cm
       AND rsl.sl_len_cm <= rsh.slmaxlen_cm;

-- rules.sgml:447
INSERT INTO unit VALUES ('cm', 1.0);

-- rules.sgml:447
INSERT INTO unit VALUES ('m', 100.0);

-- rules.sgml:447
INSERT INTO unit VALUES ('inch', 2.54);

-- rules.sgml:447
INSERT INTO shoe_data VALUES ('sh1', 2, 'black', 70.0, 90.0, 'cm');

-- rules.sgml:447
INSERT INTO shoe_data VALUES ('sh2', 0, 'black', 30.0, 40.0, 'inch');

-- rules.sgml:447
INSERT INTO shoe_data VALUES ('sh3', 4, 'brown', 50.0, 65.0, 'cm');

-- rules.sgml:447
INSERT INTO shoe_data VALUES ('sh4', 3, 'brown', 40.0, 50.0, 'inch');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl1', 5, 'black', 80.0, 'cm');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl2', 6, 'black', 100.0, 'cm');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl3', 0, 'black', 35.0 , 'inch');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl4', 8, 'black', 40.0 , 'inch');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl5', 4, 'brown', 1.0 , 'm');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl6', 0, 'brown', 0.9 , 'm');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl7', 7, 'brown', 60 , 'cm');

-- rules.sgml:447
INSERT INTO shoelace_data VALUES ('sl8', 1, 'brown', 40 , 'inch');

-- rules.sgml:447
SELECT * FROM shoelace;

-- rules.sgml:488
SELECT shoelace.sl_name, shoelace.sl_avail,
       shoelace.sl_color, shoelace.sl_len,
       shoelace.sl_unit, shoelace.sl_len_cm
  FROM shoelace shoelace;

-- rules.sgml:501
SELECT s.sl_name, s.sl_avail,
       s.sl_color, s.sl_len, s.sl_unit,
       s.sl_len * u.un_fact AS sl_len_cm
  FROM shoelace old, shoelace new,
       shoelace_data s, unit u
 WHERE s.sl_unit = u.un_name;

-- rules.sgml:517
SELECT shoelace.sl_name, shoelace.sl_avail,
       shoelace.sl_color, shoelace.sl_len,
       shoelace.sl_unit, shoelace.sl_len_cm
  FROM (SELECT s.sl_name,
               s.sl_avail,
               s.sl_color,
               s.sl_len,
               s.sl_unit,
               s.sl_len * u.un_fact AS sl_len_cm
          FROM shoelace_data s, unit u
         WHERE s.sl_unit = u.un_name) shoelace;

-- rules.sgml:558
SELECT * FROM shoe_ready WHERE total_avail >= 2;

-- rules.sgml:572
SELECT shoe_ready.shoename, shoe_ready.sh_avail,
       shoe_ready.sl_name, shoe_ready.sl_avail,
       shoe_ready.total_avail
  FROM shoe_ready shoe_ready
 WHERE shoe_ready.total_avail >= 2;

-- rules.sgml:584
SELECT shoe_ready.shoename, shoe_ready.sh_avail,
       shoe_ready.sl_name, shoe_ready.sl_avail,
       shoe_ready.total_avail
  FROM (SELECT rsh.shoename,
               rsh.sh_avail,
               rsl.sl_name,
               rsl.sl_avail,
               least(rsh.sh_avail, rsl.sl_avail) AS total_avail
          FROM shoe rsh, shoelace rsl
         WHERE rsl.sl_color = rsh.slcolor
           AND rsl.sl_len_cm >= rsh.slminlen_cm
           AND rsl.sl_len_cm <= rsh.slmaxlen_cm) shoe_ready
 WHERE shoe_ready.total_avail >= 2;

-- rules.sgml:604
SELECT shoe_ready.shoename, shoe_ready.sh_avail,
       shoe_ready.sl_name, shoe_ready.sl_avail,
       shoe_ready.total_avail
  FROM (SELECT rsh.shoename,
               rsh.sh_avail,
               rsl.sl_name,
               rsl.sl_avail,
               least(rsh.sh_avail, rsl.sl_avail) AS total_avail
          FROM (SELECT sh.shoename,
                       sh.sh_avail,
                       sh.slcolor,
                       sh.slminlen,
                       sh.slminlen * un.un_fact AS slminlen_cm,
                       sh.slmaxlen,
                       sh.slmaxlen * un.un_fact AS slmaxlen_cm,
                       sh.slunit
                  FROM shoe_data sh, unit un
                 WHERE sh.slunit = un.un_name) rsh,
               (SELECT s.sl_name,
                       s.sl_avail,
                       s.sl_color,
                       s.sl_len,
                       s.sl_unit,
                       s.sl_len * u.un_fact AS sl_len_cm
                  FROM shoelace_data s, unit u
                 WHERE s.sl_unit = u.un_name) rsl
         WHERE rsl.sl_color = rsh.slcolor
           AND rsl.sl_len_cm >= rsh.slminlen_cm
           AND rsl.sl_len_cm <= rsh.slmaxlen_cm) shoe_ready
 WHERE shoe_ready.total_avail >= 2;

-- rules.sgml:668
SELECT t2.b FROM t1, t2 WHERE t1.a = t2.a;

-- rules.sgml:668
UPDATE t1 SET b = t2.b FROM t2 WHERE t1.a = t2.a;

-- rules.sgml:712
UPDATE t1 SET a = t1.a, b = t2.b FROM t2 WHERE t1.a = t2.a;

-- rules.sgml:719
SELECT t1.a, t2.b FROM t1, t2 WHERE t1.a = t2.a;

-- rules.sgml:745
SELECT t1.a, t2.b, t1.ctid FROM t1, t2 WHERE t1.a = t2.a;

-- rules.sgml:919
CREATE MATERIALIZED VIEW mymatview AS SELECT * FROM mytab;

-- rules.sgml:925
CREATE TABLE mymatview AS SELECT * FROM mytab;

-- rules.sgml:934
REFRESH MATERIALIZED VIEW mymatview;

-- rules.sgml:953
CREATE TABLE invoice (
    invoice_no    integer        PRIMARY KEY,
    seller_no     integer,       -- ID of salesperson
    invoice_date  date,          -- date of sale
    invoice_amt   numeric(13,2)  -- amount of sale
);

-- rules.sgml:966
CREATE MATERIALIZED VIEW sales_summary AS
  SELECT
      seller_no,
      invoice_date,
      sum(invoice_amt)::numeric(13,2) AS sales_amt
    FROM invoice
    WHERE invoice_date < CURRENT_DATE
    GROUP BY
      seller_no,
      invoice_date;

-- rules.sgml:966
CREATE UNIQUE INDEX sales_summary_seller
  ON sales_summary (seller_no, invoice_date);

-- rules.sgml:986
REFRESH MATERIALIZED VIEW sales_summary;

-- rules.sgml:1006
CREATE SERVER local_file FOREIGN DATA WRAPPER file_fdw;

-- rules.sgml:1006
CREATE FOREIGN TABLE words (word text NOT NULL)
  SERVER local_file
  OPTIONS (filename '/usr/share/dict/words');

-- rules.sgml:1006
CREATE MATERIALIZED VIEW wrd AS SELECT * FROM words;

-- rules.sgml:1006
CREATE UNIQUE INDEX wrd_word ON wrd (word);

-- rules.sgml:1006
CREATE EXTENSION pg_trgm;

-- rules.sgml:1006
CREATE INDEX wrd_trgm ON wrd USING gist (word gist_trgm_ops);

-- rules.sgml:1006
VACUUM ANALYZE wrd;

-- rules.sgml:1021
SELECT count(*) FROM words WHERE word = 'caterpiler';

-- rules.sgml:1059
SELECT word FROM words ORDER BY word <-> 'caterpiler' LIMIT 10;

-- rules.sgml:1322
CREATE TABLE shoelace_log (
    sl_name    text,          -- shoelace changed
    sl_avail   integer,       -- new available value
    log_who    text,          -- who did it
    log_when   timestamp      -- when
);

-- rules.sgml:1322
CREATE RULE log_shoelace AS ON UPDATE TO shoelace_data
    WHERE NEW.sl_avail <> OLD.sl_avail
    DO INSERT INTO shoelace_log VALUES (
                                    NEW.sl_name,
                                    NEW.sl_avail,
                                    current_user,
                                    current_timestamp
                                );

-- rules.sgml:1344
UPDATE shoelace_data SET sl_avail = 6 WHERE sl_name = 'sl7';

-- rules.sgml:1350
SELECT * FROM shoelace_log;

-- rules.sgml:1364
UPDATE shoelace_data SET sl_avail = 6
  FROM shoelace_data shoelace_data
 WHERE shoelace_data.sl_name = 'sl7';

-- rules.sgml:1478
UPDATE shoelace_data SET sl_avail = 6
 WHERE sl_name = 'sl7';

-- rules.sgml:1498
UPDATE shoelace_data SET sl_color = 'green'
 WHERE sl_name = 'sl7';

-- rules.sgml:1525
UPDATE shoelace_data SET sl_avail = 0
 WHERE sl_color = 'black';

-- rules.sgml:1570
CREATE RULE shoe_ins_protect AS ON INSERT TO shoe
    DO INSTEAD NOTHING;

-- rules.sgml:1570
CREATE RULE shoe_upd_protect AS ON UPDATE TO shoe
    DO INSTEAD NOTHING;

-- rules.sgml:1570
CREATE RULE shoe_del_protect AS ON DELETE TO shoe
    DO INSTEAD NOTHING;

-- rules.sgml:1595
CREATE RULE shoelace_ins AS ON INSERT TO shoelace
    DO INSTEAD
    INSERT INTO shoelace_data VALUES (
           NEW.sl_name,
           NEW.sl_avail,
           NEW.sl_color,
           NEW.sl_len,
           NEW.sl_unit
    );

-- rules.sgml:1595
CREATE RULE shoelace_upd AS ON UPDATE TO shoelace
    DO INSTEAD
    UPDATE shoelace_data
       SET sl_name = NEW.sl_name,
           sl_avail = NEW.sl_avail,
           sl_color = NEW.sl_color,
           sl_len = NEW.sl_len,
           sl_unit = NEW.sl_unit
     WHERE sl_name = OLD.sl_name;

-- rules.sgml:1595
CREATE RULE shoelace_del AS ON DELETE TO shoelace
    DO INSTEAD
    DELETE FROM shoelace_data
     WHERE sl_name = OLD.sl_name;

-- rules.sgml:1630
CREATE RULE shoelace_ins AS ON INSERT TO shoelace
    DO INSTEAD
    INSERT INTO shoelace_data VALUES (
           NEW.sl_name,
           NEW.sl_avail,
           NEW.sl_color,
           NEW.sl_len,
           NEW.sl_unit
    )
    RETURNING
           shoelace_data.*,
           (SELECT shoelace_data.sl_len * u.un_fact
            FROM unit u WHERE shoelace_data.sl_unit = u.un_name);

-- rules.sgml:1676
CREATE TABLE shoelace_arrive (
    arr_name    text,
    arr_quant   integer
);

-- rules.sgml:1676
CREATE TABLE shoelace_ok (
    ok_name     text,
    ok_quant    integer
);

-- rules.sgml:1676
CREATE RULE shoelace_ok_ins AS ON INSERT TO shoelace_ok
    DO INSTEAD
    UPDATE shoelace
       SET sl_avail = sl_avail + NEW.ok_quant
     WHERE sl_name = NEW.ok_name;

-- rules.sgml:1697
SELECT * FROM shoelace_arrive;

-- rules.sgml:1728
INSERT INTO shoelace_ok SELECT * FROM shoelace_arrive;

-- rules.sgml:1734
SELECT * FROM shoelace ORDER BY sl_name;

-- rules.sgml:1767
INSERT INTO shoelace_ok
SELECT shoelace_arrive.arr_name, shoelace_arrive.arr_quant
  FROM shoelace_arrive shoelace_arrive, shoelace_ok shoelace_ok;

-- rules.sgml:1776
UPDATE shoelace
   SET sl_avail = shoelace.sl_avail + shoelace_arrive.arr_quant
  FROM shoelace_arrive shoelace_arrive, shoelace_ok shoelace_ok,
       shoelace_ok old, shoelace_ok new,
       shoelace shoelace
 WHERE shoelace.sl_name = shoelace_arrive.arr_name;

-- rules.sgml:1790
UPDATE shoelace_data
   SET sl_name = shoelace.sl_name,
       sl_avail = shoelace.sl_avail + shoelace_arrive.arr_quant,
       sl_color = shoelace.sl_color,
       sl_len = shoelace.sl_len,
       sl_unit = shoelace.sl_unit
  FROM shoelace_arrive shoelace_arrive, shoelace_ok shoelace_ok,
       shoelace_ok old, shoelace_ok new,
       shoelace shoelace, shoelace old,
       shoelace new, shoelace_data shoelace_data
 WHERE shoelace.sl_name = shoelace_arrive.arr_name
   AND shoelace_data.sl_name = shoelace.sl_name;

-- rules.sgml:1810
UPDATE shoelace_data
   SET sl_name = s.sl_name,
       sl_avail = s.sl_avail + shoelace_arrive.arr_quant,
       sl_color = s.sl_color,
       sl_len = s.sl_len,
       sl_unit = s.sl_unit
  FROM shoelace_arrive shoelace_arrive, shoelace_ok shoelace_ok,
       shoelace_ok old, shoelace_ok new,
       shoelace shoelace, shoelace old,
       shoelace new, shoelace_data shoelace_data,
       shoelace old, shoelace new,
       shoelace_data s, unit u
 WHERE s.sl_name = shoelace_arrive.arr_name
   AND shoelace_data.sl_name = s.sl_name;

-- rules.sgml:1857
INSERT INTO shoelace_log
SELECT s.sl_name,
       s.sl_avail + shoelace_arrive.arr_quant,
       current_user,
       current_timestamp
  FROM shoelace_arrive shoelace_arrive, shoelace_data shoelace_data,
       shoelace_data s
 WHERE s.sl_name = shoelace_arrive.arr_name
   AND shoelace_data.sl_name = s.sl_name
   AND s.sl_avail + shoelace_arrive.arr_quant <> s.sl_avail;

-- rules.sgml:1857
UPDATE shoelace_data
   SET sl_avail = shoelace_data.sl_avail + shoelace_arrive.arr_quant
  FROM shoelace_arrive shoelace_arrive,
       shoelace_data shoelace_data,
       shoelace_data s
 WHERE s.sl_name = shoelace_arrive.sl_name
   AND shoelace_data.sl_name = s.sl_name;

-- rules.sgml:1930
INSERT INTO shoelace VALUES ('sl9', 0, 'pink', 35.0, 'inch', 0.0);

-- rules.sgml:1930
INSERT INTO shoelace VALUES ('sl10', 1000, 'magenta', 40.0, 'inch', 0.0);

-- rules.sgml:1939
CREATE VIEW shoelace_mismatch AS
    SELECT * FROM shoelace WHERE NOT EXISTS
        (SELECT shoename FROM shoe WHERE slcolor = sl_color);

-- rules.sgml:1947
SELECT * FROM shoelace_mismatch;

-- rules.sgml:1963
CREATE VIEW shoelace_can_delete AS
    SELECT * FROM shoelace_mismatch WHERE sl_avail = 0;

-- rules.sgml:1970
DELETE FROM shoelace WHERE EXISTS
    (SELECT * FROM shoelace_can_delete
             WHERE sl_name = shoelace.sl_name);

-- rules.sgml:2055
CREATE TABLE phone_data (person text, phone text, private boolean);

-- rules.sgml:2055
CREATE VIEW phone_number AS
    SELECT person, CASE WHEN NOT private THEN phone END AS phone
    FROM phone_data;

-- rules.sgml:2055
GRANT SELECT ON phone_number TO assistant;

-- rules.sgml:2108
CREATE VIEW phone_number AS
    SELECT person, phone FROM phone_data WHERE phone NOT LIKE '412%';

-- rules.sgml:2120
CREATE FUNCTION tricky(text, text) RETURNS bool AS $$
BEGIN
    RAISE NOTICE '% => %', $1, $2;
    RETURN true;
END;
$$ LANGUAGE plpgsql COST 0.0000000000000000000001;

-- rules.sgml:2120
SELECT * FROM phone_number WHERE tricky(person, phone);

-- rules.sgml:2162
CREATE VIEW phone_number WITH (security_barrier) AS
    SELECT person, phone FROM phone_data WHERE phone NOT LIKE '412%';

-- rules.sgml:2319
CREATE TABLE computer (
    hostname        text,    -- indexed
    manufacturer    text     -- indexed
);

-- rules.sgml:2319
CREATE TABLE software (
    software        text,    -- indexed
    hostname        text     -- indexed
);

-- rules.sgml:2336
DELETE FROM software WHERE hostname = $1;

-- rules.sgml:2345
CREATE RULE computer_del AS ON DELETE TO computer
    DO DELETE FROM software WHERE hostname = OLD.hostname;

-- rules.sgml:2354
DELETE FROM computer WHERE hostname = 'mypc.local.net';

-- rules.sgml:2362
DELETE FROM software WHERE computer.hostname = 'mypc.local.net'
                       AND software.hostname = computer.hostname;

-- rules.sgml:2393
DELETE FROM software WHERE computer.hostname >= 'old' AND computer.hostname < 'ole'
                       AND software.hostname = computer.hostname;

-- rules.sgml:2409
DELETE FROM computer WHERE hostname ~ '^old';

-- rules.sgml:2441
DELETE FROM computer WHERE manufacturer = 'bim';

-- rules.sgml:2449
DELETE FROM software WHERE computer.manufacturer = 'bim'
                       AND software.hostname = computer.hostname;
