-- Generated by script/extract-doc-sql.js from doc/src/sgml/seg.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- seg.sgml:48
SELECT 6.50::float8 AS "pH";

-- seg.sgml:74
SELECT '6.25 .. 6.50'::seg AS "pH";

-- seg.sgml:379
SELECT '10(+-)1'::seg AS seg;
