-- Generated by script/extract-doc-sql.js from doc/src/sgml/sepgsql.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- sepgsql.sgml:554
CREATE TABLE customer (
               cid     int primary key,
               cname   text,
               credit  text
           );

-- sepgsql.sgml:554
CREATE FUNCTION show_credit(int) RETURNS text
             AS 'SELECT regexp_replace(credit, ''-[0-9]+$'', ''-xxxx'', ''g'')
                        FROM customer WHERE cid = $1'
           LANGUAGE sql;

-- sepgsql.sgml:578
SELECT * FROM customer;

-- sepgsql.sgml:615
SELECT sepgsql_getcon();

-- sepgsql.sgml:615
SELECT sepgsql_setcon('unconfined_u:unconfined_r:unconfined_t:s0-s0:c1.c4');

-- sepgsql.sgml:615
SELECT sepgsql_setcon('unconfined_u:unconfined_r:unconfined_t:s0-s0:c1.c1023');
