-- Generated by script/extract-doc-sql.js from doc/src/sgml/syntax.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- syntax.sgml:52
SELECT * FROM MY_TABLE;

-- syntax.sgml:52
UPDATE MY_TABLE SET A = 5;

-- syntax.sgml:52
INSERT INTO MY_TABLE VALUES (3, 'hi there');

-- syntax.sgml:152
uPDaTE my_TabLE SeT a = 5;

-- syntax.sgml:157
UPDATE my_table SET a = 5;

-- syntax.sgml:179
UPDATE "my_table" SET "a" = 5;

-- syntax.sgml:326
SELECT 'foobar';

-- syntax.sgml:1348
CREATE FUNCTION dept(text) RETURNS dept
    AS $$ SELECT * FROM dept WHERE name = $1 $$
    LANGUAGE SQL;

-- syntax.sgml:1626
WITH vals (v) AS ( VALUES (1),(3),(4),(3),(2) )
SELECT array_agg(v ORDER BY v DESC) FROM vals;

-- syntax.sgml:1635
WITH vals (k, v) AS ( VALUES ('key0','1'), ('key1','3'), ('key1','2') )
SELECT jsonb_object_agg(k, v ORDER BY v) FROM vals;

-- syntax.sgml:1648
SELECT string_agg(a, ',' ORDER BY a) FROM table;

-- syntax.sgml:1652
SELECT string_agg(a ORDER BY a, ',') FROM table;  -- incorrect

-- syntax.sgml:1665
WITH vals (v) AS ( VALUES (1),(3),(4),(3),(2) )
SELECT array_agg(DISTINCT v ORDER BY v DESC) FROM vals;

-- syntax.sgml:1717
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY income) FROM households;

-- syntax.sgml:1735
SELECT
    count(*) AS unfiltered,
    count(*) FILTER (WHERE i < 5) AS filtered
FROM generate_series(1,10) AS s(i);

-- syntax.sgml:2165
SELECT * FROM tbl WHERE a > 'foo' COLLATE "C";

-- syntax.sgml:2178
SELECT * FROM tbl WHERE a COLLATE "C" > 'foo';

-- syntax.sgml:2182
SELECT * FROM tbl WHERE (a > 'foo') COLLATE "C";

-- syntax.sgml:2216
SELECT name, (SELECT max(pop) FROM cities WHERE cities.state = states.name)
    FROM states;

-- syntax.sgml:2243
SELECT ARRAY[1,2,3+4];

-- syntax.sgml:2256
SELECT ARRAY[1,2,22.7]::integer[];

-- syntax.sgml:2274
SELECT ARRAY[ARRAY[1,2], ARRAY[3,4]];

-- syntax.sgml:2274
SELECT ARRAY[[1,2],[3,4]];

-- syntax.sgml:2298
CREATE TABLE arr(f1 int[], f2 int[]);

-- syntax.sgml:2298
INSERT INTO arr VALUES (ARRAY[[1,2],[3,4]], ARRAY[[5,6],[7,8]]);

-- syntax.sgml:2298
SELECT ARRAY[f1, f2, '{{9,10},{11,12}}'::int[]] FROM arr;

-- syntax.sgml:2315
SELECT ARRAY[]::integer[];

-- syntax.sgml:2329
SELECT ARRAY(SELECT oid FROM pg_proc WHERE proname LIKE 'bytea%');

-- syntax.sgml:2329
SELECT ARRAY(SELECT ARRAY[i, i*2] FROM generate_series(1,5) AS a(i));

-- syntax.sgml:2385
SELECT ROW(1,2.5,'this is a test');

-- syntax.sgml:2400
SELECT ROW(t.*, 42) FROM t;

-- syntax.sgml:2400
SELECT ROW(t.f1, t.f2, 42) FROM t;

-- syntax.sgml:2424
CREATE TABLE mytable(f1 int, f2 float, f3 text);

-- syntax.sgml:2424
CREATE FUNCTION getf1(mytable) RETURNS int AS 'SELECT $1.f1' LANGUAGE SQL;

-- syntax.sgml:2424
SELECT getf1(ROW(1,2.5,'this is a test'));

-- syntax.sgml:2424
CREATE TYPE myrowtype AS (f1 int, f2 text, f3 numeric);

-- syntax.sgml:2424
CREATE FUNCTION getf1(myrowtype) RETURNS int AS 'SELECT $1.f1' LANGUAGE SQL;

-- syntax.sgml:2424
SELECT getf1(ROW(1,2.5,'this is a test')::mytable);

-- syntax.sgml:2424
SELECT getf1(CAST(ROW(11,'this is a test',2.5) AS myrowtype));

-- syntax.sgml:2489
SELECT true OR somefunc();

-- syntax.sgml:2494
SELECT somefunc() OR true;

-- syntax.sgml:2537
SELECT CASE WHEN x > 0 THEN x ELSE 1/0 END FROM tab;

-- syntax.sgml:2564
SELECT CASE WHEN min(employees) > 0
            THEN avg(expenses / employees)
       END
    FROM departments;

-- syntax.sgml:2622
CREATE FUNCTION concat_lower_or_upper(a text, b text, uppercase boolean DEFAULT false)
RETURNS text
AS
$$
 SELECT CASE
        WHEN $3 THEN UPPER($1 || ' ' || $2)
        ELSE LOWER($1 || ' ' || $2)
        END;
$$
LANGUAGE SQL IMMUTABLE STRICT;

-- syntax.sgml:2656
SELECT concat_lower_or_upper('Hello', 'World', true);

-- syntax.sgml:2666
SELECT concat_lower_or_upper('Hello', 'World');

-- syntax.sgml:2692
SELECT concat_lower_or_upper(a => 'Hello', b => 'World');

-- syntax.sgml:2703
SELECT concat_lower_or_upper(a => 'Hello', b => 'World', uppercase => true);

-- syntax.sgml:2703
SELECT concat_lower_or_upper(a => 'Hello', uppercase => true, b => 'World');

-- syntax.sgml:2720
SELECT concat_lower_or_upper(a := 'Hello', uppercase := true, b := 'World');

-- syntax.sgml:2742
SELECT concat_lower_or_upper('Hello', 'World', uppercase => true);
