-- Generated by script/extract-doc-sql.js from doc/src/sgml/system-views.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- system-views.sgml:916
WITH memory_contexts AS (
    SELECT * FROM pg_backend_memory_contexts
)
SELECT sum(c1.total_bytes)
FROM memory_contexts c1, memory_contexts c2
WHERE c2.name = 'CacheMemoryContext'
AND c1.path[c2.level] = c2.path[c2.level];

-- system-views.sgml:2080
SELECT * FROM pg_locks pl LEFT JOIN pg_stat_activity psa
    ON pl.pid = psa.pid;

-- system-views.sgml:2092
SELECT * FROM pg_locks pl LEFT JOIN pg_prepared_xacts ppx
    ON pl.virtualtransaction = '-1/' || ppx.transaction;
