-- Generated by script/extract-doc-sql.js from doc/src/sgml/tableam.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- tableam.sgml:45
CREATE OR REPLACE FUNCTION my_tableam_handler(internal)
  RETURNS table_am_handler AS 'my_extension', 'my_tableam_handler'
  LANGUAGE C STRICT;

-- tableam.sgml:45
CREATE ACCESS METHOD myam TYPE TABLE HANDLER my_tableam_handler;
