-- Generated by script/extract-doc-sql.js from doc/src/sgml/tablefunc.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- tablefunc.sgml:150
SELECT * FROM normal_rand(1000, 5, 3);

-- tablefunc.sgml:283
CREATE TABLE ct(id SERIAL, rowid TEXT, attribute TEXT, value TEXT);

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test1','att1','val1');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test1','att2','val2');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test1','att3','val3');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test1','att4','val4');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test2','att1','val5');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test2','att2','val6');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test2','att3','val7');

-- tablefunc.sgml:283
INSERT INTO ct(rowid, attribute, value) VALUES('test2','att4','val8');

-- tablefunc.sgml:283
SELECT *
FROM crosstab(
  'SELECT rowid, attribute, value
   FROM ct
   WHERE attribute = ''att2'' OR attribute = ''att3''
   ORDER BY 1, 2')
AS ct(row_name text, category_1 text, category_2 text, category_3 text);

-- tablefunc.sgml:371
SELECT *
FROM crosstab3(
  'SELECT rowid, attribute, value
   FROM ct
   WHERE attribute = ''att2'' OR attribute = ''att3''
   ORDER BY 1, 2');

-- tablefunc.sgml:399
CREATE TYPE my_crosstab_float8_5_cols AS (
    my_row_name text,
    my_category_1 float8,
    my_category_2 float8,
    my_category_3 float8,
    my_category_4 float8,
    my_category_5 float8
);

-- tablefunc.sgml:399
CREATE OR REPLACE FUNCTION crosstab_float8_5_cols(text)
    RETURNS SETOF my_crosstab_float8_5_cols
    AS '$libdir/tablefunc','crosstab' LANGUAGE C STABLE STRICT;

-- tablefunc.sgml:420
CREATE OR REPLACE FUNCTION crosstab_float8_5_cols(
    IN text,
    OUT my_row_name text,
    OUT my_category_1 float8,
    OUT my_category_2 float8,
    OUT my_category_3 float8,
    OUT my_category_4 float8,
    OUT my_category_5 float8)
  RETURNS SETOF record
  AS '$libdir/tablefunc','crosstab' LANGUAGE C STABLE STRICT;

-- tablefunc.sgml:480
SELECT row_name, extra_col, cat, value FROM foo ORDER BY 1;

-- tablefunc.sgml:502
SELECT DISTINCT cat FROM foo ORDER BY 1;

-- tablefunc.sgml:574
CREATE TABLE sales (year int, month int, qty int);

-- tablefunc.sgml:574
INSERT INTO sales VALUES (2007,  1, 1000);

-- tablefunc.sgml:574
INSERT INTO sales VALUES (2007,  2, 1500);

-- tablefunc.sgml:574
INSERT INTO sales VALUES (2007,  7,  500);

-- tablefunc.sgml:574
INSERT INTO sales VALUES (2007, 11, 1500);

-- tablefunc.sgml:574
INSERT INTO sales VALUES (2007, 12, 2000);

-- tablefunc.sgml:574
INSERT INTO sales VALUES (2008,  1, 1000);

-- tablefunc.sgml:574
SELECT * FROM crosstab(
  'SELECT year, month, qty FROM sales ORDER BY 1',
  'SELECT m FROM generate_series(1, 12) m'
) AS (
  year int,
  "Jan" int,
  "Feb" int,
  "Mar" int,
  "Apr" int,
  "May" int,
  "Jun" int,
  "Jul" int,
  "Aug" int,
  "Sep" int,
  "Oct" int,
  "Nov" int,
  "Dec" int
);

-- tablefunc.sgml:608
CREATE TABLE cth(rowid text, rowdt timestamp, attribute text, val text);

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test1','01 March 2003','temperature','42');

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test1','01 March 2003','test_result','PASS');

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test1','01 March 2003','volts','2.6987');

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test2','02 March 2003','temperature','53');

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test2','02 March 2003','test_result','FAIL');

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test2','02 March 2003','test_startdate','01 March 2003');

-- tablefunc.sgml:608
INSERT INTO cth VALUES('test2','02 March 2003','volts','3.1234');

-- tablefunc.sgml:608
SELECT * FROM crosstab
(
  'SELECT rowid, rowdt, attribute, val FROM cth ORDER BY 1',
  'SELECT DISTINCT attribute FROM cth ORDER BY 1'
)
AS
(
       rowid text,
       rowdt timestamp,
       temperature int4,
       test_result text,
       test_startdate timestamp,
       volts float8
);

-- tablefunc.sgml:730
SELECT * FROM connectby('connectby_tree', 'keyid', 'parent_keyid', 'pos', 'row2', 0, '~')
    AS t(keyid text, parent_keyid text, level int, branch text, pos int);

-- tablefunc.sgml:786
CREATE TABLE connectby_tree(keyid text, parent_keyid text, pos int);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row1',NULL, 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row2','row1', 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row3','row1', 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row4','row2', 1);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row5','row2', 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row6','row4', 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row7','row3', 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row8','row6', 0);

-- tablefunc.sgml:786
INSERT INTO connectby_tree VALUES('row9','row5', 0);

-- tablefunc.sgml:786
SELECT * FROM connectby('connectby_tree', 'keyid', 'parent_keyid', 'row2', 0, '~')
 AS t(keyid text, parent_keyid text, level int, branch text);

-- tablefunc.sgml:786
SELECT * FROM connectby('connectby_tree', 'keyid', 'parent_keyid', 'row2', 0)
 AS t(keyid text, parent_keyid text, level int);

-- tablefunc.sgml:786
SELECT * FROM connectby('connectby_tree', 'keyid', 'parent_keyid', 'pos', 'row2', 0, '~')
 AS t(keyid text, parent_keyid text, level int, branch text, pos int);

-- tablefunc.sgml:786
SELECT * FROM connectby('connectby_tree', 'keyid', 'parent_keyid', 'pos', 'row2', 0)
 AS t(keyid text, parent_keyid text, level int, pos int);
