-- Generated by script/extract-doc-sql.js from doc/src/sgml/tcn.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- tcn.sgml:45
CREATE TABLE tcndata
  (
    a int NOT NULL,
    b date NOT NULL,
    c text,
    PRIMARY KEY (a, b)
  );

-- tcn.sgml:45
CREATE TRIGGER tcndata_tcn_trigger
  AFTER INSERT OR UPDATE OR DELETE ON tcndata
  FOR EACH ROW EXECUTE FUNCTION triggered_change_notification();

-- tcn.sgml:45
LISTEN tcn;

-- tcn.sgml:45
INSERT INTO tcndata VALUES (1, date '2012-12-22', 'one'),
                           (1, date '2012-12-23', 'another'),
                           (2, date '2012-12-23', 'two');

-- tcn.sgml:45
UPDATE tcndata SET c = 'uno' WHERE a = 1;

-- tcn.sgml:45
DELETE FROM tcndata WHERE a = 1 AND b = date '2012-12-22';
