-- Generated by script/extract-doc-sql.js from doc/src/sgml/test-decoding.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- test-decoding.sgml:26
SELECT * FROM pg_logical_slot_get_changes('test_slot', NULL, NULL, 'include-xids', '0');
