-- Generated by script/extract-doc-sql.js from doc/src/sgml/textsearch.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- textsearch.sgml:196
SELECT title || ' ' ||  author || ' ' ||  abstract || ' ' || body AS document
FROM messages
WHERE mid = 12;

-- textsearch.sgml:196
SELECT m.title || ' ' || m.author || ' ' || m.abstract || ' ' || d.body AS document
FROM messages m, docs d
WHERE m.mid = d.did AND m.mid = 12;

-- textsearch.sgml:249
SELECT 'a fat cat sat on a mat and ate a fat rat'::tsvector @@ 'cat & rat'::tsquery;

-- textsearch.sgml:249
SELECT 'fat & cow'::tsquery @@ 'a fat cat sat on a mat and ate a fat rat'::tsvector;

-- textsearch.sgml:276
SELECT to_tsvector('fat cats ate fat rats') @@ to_tsquery('fat & rat');

-- textsearch.sgml:285
SELECT 'fat cats ate fat rats'::tsvector @@ to_tsquery('fat & rat');

-- textsearch.sgml:336
SELECT to_tsvector('fatal error') @@ to_tsquery('fatal <-> error');

-- textsearch.sgml:336
SELECT to_tsvector('error is not fatal') @@ to_tsquery('fatal <-> error');

-- textsearch.sgml:358
SELECT phraseto_tsquery('cats ate rats');

-- textsearch.sgml:358
SELECT phraseto_tsquery('the cats ate the rats');

-- textsearch.sgml:510
SELECT title
FROM pgweb
WHERE to_tsvector('english', body) @@ to_tsquery('english', 'friend');

-- textsearch.sgml:526
SELECT title
FROM pgweb
WHERE to_tsvector(body) @@ to_tsquery('friend');

-- textsearch.sgml:541
SELECT title
FROM pgweb
WHERE to_tsvector(title || ' ' || body) @@ to_tsquery('create & table')
ORDER BY last_mod_date DESC
LIMIT 10;

-- textsearch.sgml:570
CREATE INDEX pgweb_idx ON pgweb USING GIN (to_tsvector('english', body));

-- textsearch.sgml:600
CREATE INDEX pgweb_idx ON pgweb USING GIN (to_tsvector(config_name, body));

-- textsearch.sgml:616
CREATE INDEX pgweb_idx ON pgweb USING GIN (to_tsvector('english', title || ' ' || body));

-- textsearch.sgml:630
ALTER TABLE pgweb
    ADD COLUMN textsearchable_index_col tsvector
               GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))) STORED;

-- textsearch.sgml:638
CREATE INDEX textsearch_idx ON pgweb USING GIN (textsearchable_index_col);

-- textsearch.sgml:644
SELECT title
FROM pgweb
WHERE textsearchable_index_col @@ to_tsquery('create & table')
ORDER BY last_mod_date DESC
LIMIT 10;

-- textsearch.sgml:709
SELECT to_tsvector('english', 'a fat  cat sat on a mat - it ate a fat rats');

-- textsearch.sgml:770
UPDATE tt SET ti =
    setweight(to_tsvector(coalesce(title,'')), 'A')    ||
    setweight(to_tsvector(coalesce(keyword,'')), 'B')  ||
    setweight(to_tsvector(coalesce(abstract,'')), 'C') ||
    setweight(to_tsvector(coalesce(body,'')), 'D');

-- textsearch.sgml:829
SELECT to_tsquery('english', 'The & Fat & Rats');

-- textsearch.sgml:840
SELECT to_tsquery('english', 'Fat | Rats:AB');

-- textsearch.sgml:849
SELECT to_tsquery('supern:*A & star:A*B');

-- textsearch.sgml:867
SELECT to_tsquery('''supernovae stars'' & !crab');

-- textsearch.sgml:898
SELECT plainto_tsquery('english', 'The Fat Rats');

-- textsearch.sgml:909
SELECT plainto_tsquery('english', 'The Fat & Rats:C');

-- textsearch.sgml:942
SELECT phraseto_tsquery('english', 'The Fat Rats');

-- textsearch.sgml:954
SELECT phraseto_tsquery('english', 'The Fat & Rats:C');

-- textsearch.sgml:1015
SELECT websearch_to_tsquery('english', 'The fat rats');

-- textsearch.sgml:1015
SELECT websearch_to_tsquery('english', '"supernovae stars" -crab');

-- textsearch.sgml:1015
SELECT websearch_to_tsquery('english', '"sad cat" or "fat rat"');

-- textsearch.sgml:1015
SELECT websearch_to_tsquery('english', 'signal -"segmentation fault"');

-- textsearch.sgml:1015
SELECT websearch_to_tsquery('english', '""" )( dummy \\ query <->');

-- textsearch.sgml:1216
SELECT title, ts_rank_cd(textsearch, query) AS rank
FROM apod, to_tsquery('neutrino|(dark & matter)') query
WHERE query @@ textsearch
ORDER BY rank DESC
LIMIT 10;

-- textsearch.sgml:1238
SELECT title, ts_rank_cd(textsearch, query, 32 /* rank/(rank+1) */ ) AS rank
FROM apod, to_tsquery('neutrino|(dark & matter)') query
WHERE  query @@ textsearch
ORDER BY rank DESC
LIMIT 10;

-- textsearch.sgml:1398
SELECT ts_headline('english',
  'The most common type of search
is to find all documents containing given query terms
and return them in order of their similarity to the
query.',
  to_tsquery('english', 'query & similarity'));

-- textsearch.sgml:1398
SELECT ts_headline('english',
  'Search terms may occur
many times in a document,
requiring ranking of the search matches to decide which
occurrences to display in the result.',
  to_tsquery('english', 'search & term'),
  'MaxFragments=10, MaxWords=7, MinWords=3, StartSel=<<, StopSel=>>');

-- textsearch.sgml:1642
SELECT to_tsquery('fat') <-> to_tsquery('cat | rat');

-- textsearch.sgml:1671
SELECT tsquery_phrase(to_tsquery('fat'), to_tsquery('cat'), 10);

-- textsearch.sgml:1700
SELECT numnode(plainto_tsquery('the any'));

-- textsearch.sgml:1700
SELECT numnode('foo & bar'::tsquery);

-- textsearch.sgml:1733
SELECT querytree(to_tsquery('defined'));

-- textsearch.sgml:1733
SELECT querytree(to_tsquery('!defined'));

-- textsearch.sgml:1792
SELECT ts_rewrite('a & b'::tsquery, 'a'::tsquery, 'c'::tsquery);

-- textsearch.sgml:1818
CREATE TABLE aliases (t tsquery PRIMARY KEY, s tsquery);

-- textsearch.sgml:1818
INSERT INTO aliases VALUES('a', 'c');

-- textsearch.sgml:1818
SELECT ts_rewrite('a & b'::tsquery, 'SELECT t,s FROM aliases');

-- textsearch.sgml:1843
CREATE TABLE aliases (t tsquery primary key, s tsquery);

-- textsearch.sgml:1843
INSERT INTO aliases VALUES(to_tsquery('supernovae'), to_tsquery('supernovae|sn'));

-- textsearch.sgml:1843
SELECT ts_rewrite(to_tsquery('supernovae & crab'), 'SELECT * FROM aliases');

-- textsearch.sgml:1855
UPDATE aliases
SET s = to_tsquery('supernovae|sn & !nebulae')
WHERE t = to_tsquery('supernovae');

-- textsearch.sgml:1874
SELECT ts_rewrite('a & b'::tsquery,
                  'SELECT t,s FROM aliases WHERE ''a & b''::tsquery @> t');

-- textsearch.sgml:1922
CREATE TABLE messages (
    title       text,
    body        text,
    tsv         tsvector
);

-- textsearch.sgml:1922
CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
ON messages FOR EACH ROW EXECUTE FUNCTION
tsvector_update_trigger(tsv, 'pg_catalog.english', title, body);

-- textsearch.sgml:1922
INSERT INTO messages VALUES('title here', 'the body text is here');

-- textsearch.sgml:1922
SELECT * FROM messages;

-- textsearch.sgml:1922
SELECT title, body FROM messages WHERE tsv @@ to_tsquery('title & body');

-- textsearch.sgml:1975
CREATE FUNCTION messages_trigger() RETURNS trigger AS $$
BEGIN
  new.tsv :=
     setweight(to_tsvector('pg_catalog.english', coalesce(new.title,'')), 'A') ||
     setweight(to_tsvector('pg_catalog.english', coalesce(new.body,'')), 'D');
  RETURN new;
END
$$ LANGUAGE plpgsql;

-- textsearch.sgml:1975
CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
    ON messages FOR EACH ROW EXECUTE FUNCTION messages_trigger();

-- textsearch.sgml:2052
SELECT * FROM ts_stat('SELECT vector FROM apod')
ORDER BY nentry DESC, ndoc DESC, word
LIMIT 10;

-- textsearch.sgml:2061
SELECT * FROM ts_stat('SELECT vector FROM apod', 'ab')
ORDER BY nentry DESC, ndoc DESC, word
LIMIT 10;

-- textsearch.sgml:2262
SELECT alias, description, token FROM ts_debug('foo-bar-beta1');

-- textsearch.sgml:2278
SELECT alias, description, token FROM ts_debug('http://example.com/stuff/index.html');

-- textsearch.sgml:2426
ALTER TEXT SEARCH CONFIGURATION astro_en
    ADD MAPPING FOR asciiword WITH astrosyn, english_ispell, english_stem;

-- textsearch.sgml:2451
SELECT to_tsvector('english', 'in the list of stop words');

-- textsearch.sgml:2461
SELECT ts_rank_cd (to_tsvector('english', 'in the list of stop words'), to_tsquery('list & stop'));

-- textsearch.sgml:2461
SELECT ts_rank_cd (to_tsvector('english', 'list stop words'), to_tsquery('list & stop'));

-- textsearch.sgml:2502
CREATE TEXT SEARCH DICTIONARY public.simple_dict (
    TEMPLATE = pg_catalog.simple,
    STOPWORDS = english
);

-- textsearch.sgml:2525
SELECT ts_lexize('public.simple_dict', 'YeS');

-- textsearch.sgml:2525
SELECT ts_lexize('public.simple_dict', 'The');

-- textsearch.sgml:2544
ALTER TEXT SEARCH DICTIONARY public.simple_dict ( Accept = false );

-- textsearch.sgml:2602
SELECT * FROM ts_debug('english', 'Paris');

-- textsearch.sgml:2602
CREATE TEXT SEARCH DICTIONARY my_synonym (
    TEMPLATE = synonym,
    SYNONYMS = my_synonyms
);

-- textsearch.sgml:2602
ALTER TEXT SEARCH CONFIGURATION english
    ALTER MAPPING FOR asciiword
    WITH my_synonym, english_stem;

-- textsearch.sgml:2664
CREATE TEXT SEARCH DICTIONARY syn (template=synonym, synonyms='synonym_sample');

-- textsearch.sgml:2664
SELECT ts_lexize('syn', 'indices');

-- textsearch.sgml:2664
CREATE TEXT SEARCH CONFIGURATION tst (copy=simple);

-- textsearch.sgml:2664
ALTER TEXT SEARCH CONFIGURATION tst ALTER MAPPING FOR asciiword WITH syn;

-- textsearch.sgml:2664
SELECT to_tsvector('tst', 'indices');

-- textsearch.sgml:2664
SELECT to_tsquery('tst', 'indices');

-- textsearch.sgml:2664
SELECT 'indexes are very useful'::tsvector;

-- textsearch.sgml:2664
SELECT 'indexes are very useful'::tsvector @@ to_tsquery('tst', 'indices');

-- textsearch.sgml:2790
CREATE TEXT SEARCH DICTIONARY thesaurus_simple (
    TEMPLATE = thesaurus,
    DictFile = mythesaurus,
    Dictionary = pg_catalog.english_stem
);

-- textsearch.sgml:2827
ALTER TEXT SEARCH CONFIGURATION russian
    ALTER MAPPING FOR asciiword, asciihword, hword_asciipart
    WITH thesaurus_simple;

-- textsearch.sgml:2851
CREATE TEXT SEARCH DICTIONARY thesaurus_astro (
    TEMPLATE = thesaurus,
    DictFile = thesaurus_astro,
    Dictionary = english_stem
);

-- textsearch.sgml:2851
ALTER TEXT SEARCH CONFIGURATION russian
    ALTER MAPPING FOR asciiword, asciihword, hword_asciipart
    WITH thesaurus_astro, english_stem;

-- textsearch.sgml:2869
SELECT plainto_tsquery('supernova star');

-- textsearch.sgml:2869
SELECT to_tsvector('supernova star');

-- textsearch.sgml:2884
SELECT to_tsquery('''supernova star''');

-- textsearch.sgml:2967
CREATE TEXT SEARCH DICTIONARY english_hunspell (
    TEMPLATE = ispell,
    DictFile = en_us,
    AffFile = en_us,
    Stopwords = english);

-- textsearch.sgml:3055
SELECT ts_lexize('norwegian_ispell', 'overbuljongterningpakkmesterassistent');

-- textsearch.sgml:3055
SELECT ts_lexize('norwegian_ispell', 'sjokoladefabrikk');

-- textsearch.sgml:3200
CREATE TEXT SEARCH DICTIONARY english_stem (
    TEMPLATE = snowball,
    Language = english,
    StopWords = english
);

-- textsearch.sgml:3255
CREATE TEXT SEARCH CONFIGURATION public.pg ( COPY = pg_catalog.english );

-- textsearch.sgml:3273
CREATE TEXT SEARCH DICTIONARY pg_dict (
    TEMPLATE = synonym,
    SYNONYMS = pg_dict
);

-- textsearch.sgml:3283
CREATE TEXT SEARCH DICTIONARY english_ispell (
    TEMPLATE = ispell,
    DictFile = english,
    AffFile = english,
    StopWords = english
);

-- textsearch.sgml:3295
ALTER TEXT SEARCH CONFIGURATION pg
    ALTER MAPPING FOR asciiword, asciihword, hword_asciipart,
                      word, hword, hword_part
    WITH pg_dict, english_ispell, english_stem;

-- textsearch.sgml:3305
ALTER TEXT SEARCH CONFIGURATION pg
    DROP MAPPING FOR email, url, url_path, sfloat, float;

-- textsearch.sgml:3314
SELECT * FROM ts_debug('public.pg', '
PostgreSQL, the highly scalable, SQL compliant, open source object-relational
database management system, is now undergoing beta testing of the next
version of our software.
');

-- textsearch.sgml:3327
SET default_text_search_config = 'public.pg';

-- textsearch.sgml:3327
SHOW default_text_search_config;

-- textsearch.sgml:3436
SELECT * FROM ts_debug('english', 'a fat  cat sat on a mat - it ate a fat rats');

-- textsearch.sgml:3473
CREATE TEXT SEARCH CONFIGURATION public.english ( COPY = pg_catalog.english );

-- textsearch.sgml:3473
ALTER TEXT SEARCH CONFIGURATION public.english
   ALTER MAPPING FOR asciiword WITH english_ispell, english_stem;

-- textsearch.sgml:3487
SELECT * FROM ts_debug('public.english', 'The Brightest supernovaes');

-- textsearch.sgml:3525
SELECT alias, token, dictionary, lexemes
FROM ts_debug('public.english', 'The Brightest supernovaes');

-- textsearch.sgml:3565
SELECT * FROM ts_parse('default', '123 - a number');

-- textsearch.sgml:3597
SELECT * FROM ts_token_type('default');

-- textsearch.sgml:3655
SELECT ts_lexize('english_stem', 'stars');

-- textsearch.sgml:3655
SELECT ts_lexize('english_stem', 'a');

-- textsearch.sgml:3674
SELECT ts_lexize('thesaurus_astro', 'supernovae stars') is null;

-- textsearch.sgml:3687
SELECT plainto_tsquery('supernovae stars');
