-- Generated by script/extract-doc-sql.js from doc/src/sgml/trigger.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- trigger.sgml:872
CREATE TABLE ttest (
    x integer
);

-- trigger.sgml:975
INSERT INTO ttest VALUES (NULL);

-- trigger.sgml:975
SELECT * FROM ttest;

-- trigger.sgml:975
INSERT INTO ttest VALUES (1);

-- trigger.sgml:975
INSERT INTO ttest SELECT x * 2 FROM ttest;

-- trigger.sgml:975
UPDATE ttest SET x = NULL WHERE x = 2;

-- trigger.sgml:975
DELETE FROM ttest;
