-- Generated by script/extract-doc-sql.js from doc/src/sgml/tsm-system-time.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- tsm-system-time.sgml:53
CREATE EXTENSION tsm_system_time;

-- tsm-system-time.sgml:60
SELECT * FROM my_table TABLESAMPLE SYSTEM_TIME(1000);
