-- Generated by script/extract-doc-sql.js from doc/src/sgml/tsm-system-rows.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- tsm-system-rows.sgml:51
CREATE EXTENSION tsm_system_rows;

-- tsm-system-rows.sgml:58
SELECT * FROM my_table TABLESAMPLE SYSTEM_ROWS(100);
