-- Generated by script/extract-doc-sql.js from doc/src/sgml/typeconv.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- typeconv.sgml:57
SELECT text 'Origin' AS "label", point '(0,0)' AS "value";

-- typeconv.sgml:367
SELECT |/ 40 AS "square root of 40";

-- typeconv.sgml:378
SELECT |/ CAST(40 AS double precision) AS "square root of 40";

-- typeconv.sgml:395
SELECT text 'abc' || 'def' AS "text and unknown";

-- typeconv.sgml:413
SELECT 'abc' || 'def' AS "unspecified";

-- typeconv.sgml:444
SELECT @ '-4.5' AS "abs";

-- typeconv.sgml:454
SELECT @ '-4.5e500' AS "abs";

-- typeconv.sgml:465
SELECT ~ '20' AS "negation";

-- typeconv.sgml:475
SELECT ~ CAST('20' AS int8) AS "negation";

-- typeconv.sgml:492
SELECT ARRAY[1, 2] <@ '{1,2,3}' AS "is subset";

-- typeconv.sgml:525
CREATE OPERATOR = (procedure=mytext_eq_text, leftarg=mytext, rightarg=text);

-- typeconv.sgml:525
CREATE TABLE mytable (val mytext);

-- typeconv.sgml:525
SELECT * FROM mytable WHERE val = 'foo';

-- typeconv.sgml:543
SELECT * FROM mytable WHERE val = text 'foo';

-- typeconv.sgml:773
SELECT round(4, 4);

-- typeconv.sgml:783
SELECT round(CAST (4 AS numeric), 4);

-- typeconv.sgml:792
SELECT round(4.0, 4);

-- typeconv.sgml:802
CREATE FUNCTION public.variadic_example(VARIADIC numeric[]) RETURNS int
  LANGUAGE sql AS 'SELECT 1';

-- typeconv.sgml:811
SELECT public.variadic_example(0),
       public.variadic_example(0.0),
       public.variadic_example(VARIADIC array[0.0]);

-- typeconv.sgml:824
CREATE FUNCTION public.variadic_example(numeric) RETURNS int
  LANGUAGE sql AS 'SELECT 2';

-- typeconv.sgml:824
CREATE FUNCTION public.variadic_example(int) RETURNS int
  LANGUAGE sql AS 'SELECT 3';

-- typeconv.sgml:859
SELECT substr('1234', 3);

-- typeconv.sgml:872
SELECT substr(varchar '1234', 3);

-- typeconv.sgml:882
SELECT substr(CAST (varchar '1234' AS text), 3);

-- typeconv.sgml:901
SELECT substr(1234, 3);

-- typeconv.sgml:910
SELECT substr(CAST (1234 AS text), 3);

-- typeconv.sgml:978
CREATE TABLE vv (v character(20));

-- typeconv.sgml:978
INSERT INTO vv SELECT 'abc' || 'def';

-- typeconv.sgml:978
SELECT v, octet_length(v) FROM vv;

-- typeconv.sgml:1133
SELECT text 'a' AS "text" UNION SELECT 'b';

-- typeconv.sgml:1150
SELECT 1.2 AS "numeric" UNION SELECT 1;

-- typeconv.sgml:1169
SELECT 1 AS "real" UNION SELECT CAST('2.2' AS REAL);

-- typeconv.sgml:1188
SELECT NULL UNION SELECT NULL UNION SELECT 1;

-- typeconv.sgml:1229
SELECT 'Hello World';
