-- Generated by script/extract-doc-sql.js from doc/src/sgml/unaccent.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- unaccent.sgml:137
ALTER TEXT SEARCH DICTIONARY unaccent (RULES='my_rules');
