-- Generated by script/extract-doc-sql.js from doc/src/sgml/user-manag.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- user-manag.sgml:318
ALTER ROLE myname SET enable_indexscan TO off;

-- user-manag.sgml:416
CREATE ROLE joe LOGIN;

-- user-manag.sgml:416
CREATE ROLE admin;

-- user-manag.sgml:416
CREATE ROLE wheel;

-- user-manag.sgml:416
CREATE ROLE island;

-- user-manag.sgml:416
GRANT admin TO joe WITH INHERIT TRUE;

-- user-manag.sgml:416
GRANT wheel TO admin WITH INHERIT FALSE;

-- user-manag.sgml:416
GRANT island TO joe WITH INHERIT TRUE, SET FALSE;

-- user-manag.sgml:440
SET ROLE wheel;

-- user-manag.sgml:447
SET ROLE joe;

-- user-manag.sgml:447
SET ROLE NONE;

-- user-manag.sgml:447
RESET ROLE;

-- user-manag.sgml:523
ALTER TABLE bobs_table OWNER TO alice;

-- user-manag.sgml:562
DROP OWNED BY doomed_role;

-- user-manag.sgml:562
DROP ROLE doomed_role;

-- user-manag.sgml:598
GRANT pg_signal_backend TO admin_user;
