-- Generated by script/extract-doc-sql.js from doc/src/sgml/uuid-ossp.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- uuid-ossp.sgml:97
SELECT uuid_generate_v3(uuid_ns_url(), 'http://www.postgresql.org');
