-- Generated by script/extract-doc-sql.js from doc/src/sgml/xfunc.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- xfunc.sgml:204
CREATE FUNCTION clean_emp() RETURNS void AS '
    DELETE FROM emp
        WHERE salary < 0;
' LANGUAGE SQL;

-- xfunc.sgml:204
SELECT clean_emp();

-- xfunc.sgml:222
CREATE PROCEDURE clean_emp() AS '
    DELETE FROM emp
        WHERE salary < 0;
' LANGUAGE SQL;

-- xfunc.sgml:222
CALL clean_emp();

-- xfunc.sgml:292
INSERT INTO mytable VALUES ($1);

-- xfunc.sgml:317
CREATE FUNCTION one() RETURNS integer AS $$
    SELECT 1 AS result;
$$ LANGUAGE SQL;

-- xfunc.sgml:317
CREATE FUNCTION one() RETURNS integer AS '
    SELECT 1 AS result;
' LANGUAGE SQL;

-- xfunc.sgml:317
SELECT one();

-- xfunc.sgml:346
CREATE FUNCTION add_em(x integer, y integer) RETURNS integer AS $$
    SELECT x + y;
$$ LANGUAGE SQL;

-- xfunc.sgml:346
SELECT add_em(1, 2) AS answer;

-- xfunc.sgml:363
CREATE FUNCTION add_em(integer, integer) RETURNS integer AS $$
    SELECT $1 + $2;
$$ LANGUAGE SQL;

-- xfunc.sgml:380
CREATE FUNCTION tf1 (accountno integer, debit numeric) RETURNS numeric AS $$
    UPDATE bank
        SET balance = balance - debit
        WHERE accountno = tf1.accountno;
    SELECT 1;
$$ LANGUAGE SQL;

-- xfunc.sgml:392
SELECT tf1(17, 100.0);

-- xfunc.sgml:411
CREATE FUNCTION tf1 (accountno integer, debit numeric) RETURNS numeric AS $$
    UPDATE bank
        SET balance = balance - debit
        WHERE accountno = tf1.accountno;
    SELECT balance FROM bank WHERE accountno = tf1.accountno;
$$ LANGUAGE SQL;

-- xfunc.sgml:423
CREATE FUNCTION tf1 (accountno integer, debit numeric) RETURNS numeric AS $$
    UPDATE bank
        SET balance = balance - debit
        WHERE accountno = tf1.accountno
    RETURNING balance;
$$ LANGUAGE SQL;

-- xfunc.sgml:444
CREATE FUNCTION add_em(integer, integer) RETURNS float8 AS $$
    SELECT $1 + $2;
$$ LANGUAGE SQL;

-- xfunc.sgml:469
CREATE TABLE emp (
    name        text,
    salary      numeric,
    age         integer,
    cubicle     point
);

-- xfunc.sgml:469
INSERT INTO emp VALUES ('Bill', 4200, 45, '(2,1)');

-- xfunc.sgml:469
CREATE FUNCTION double_salary(emp) RETURNS numeric AS $$
    SELECT $1.salary * 2 AS salary;
$$ LANGUAGE SQL;

-- xfunc.sgml:469
SELECT name, double_salary(emp.*) AS dream
    FROM emp
    WHERE emp.cubicle ~= point '(2,1)';

-- xfunc.sgml:501
SELECT name, double_salary(emp) AS dream
    FROM emp
    WHERE emp.cubicle ~= point '(2,1)';

-- xfunc.sgml:515
SELECT name, double_salary(ROW(name, salary*1.1, age, cubicle)) AS dream
    FROM emp;

-- xfunc.sgml:526
CREATE FUNCTION new_emp() RETURNS emp AS $$
    SELECT text 'None' AS name,
        1000.0 AS salary,
        25 AS age,
        point '(2,2)' AS cubicle;
$$ LANGUAGE SQL;

-- xfunc.sgml:573
CREATE FUNCTION new_emp() RETURNS emp AS $$
    SELECT ROW('None', 1000.0, 25, '(2,2)')::emp;
$$ LANGUAGE SQL;

-- xfunc.sgml:594
SELECT new_emp();

-- xfunc.sgml:604
SELECT * FROM new_emp();

-- xfunc.sgml:621
SELECT (new_emp()).name;

-- xfunc.sgml:643
SELECT name(new_emp());

-- xfunc.sgml:659
CREATE FUNCTION getname(emp) RETURNS text AS $$
    SELECT $1.name;
$$ LANGUAGE SQL;

-- xfunc.sgml:659
SELECT getname(new_emp());

-- xfunc.sgml:685
CREATE FUNCTION add_em (IN x int, IN y int, OUT sum int)
AS 'SELECT x + y'
LANGUAGE SQL;

-- xfunc.sgml:685
SELECT add_em(3,7);

-- xfunc.sgml:702
CREATE FUNCTION sum_n_product (x int, y int, OUT sum int, OUT product int)
AS 'SELECT x + y, x * y'
LANGUAGE SQL;

-- xfunc.sgml:702
SELECT * FROM sum_n_product(11,42);

-- xfunc.sgml:718
CREATE TYPE sum_prod AS (sum int, product int);

-- xfunc.sgml:718
CREATE FUNCTION sum_n_product (int, int) RETURNS sum_prod
AS 'SELECT $1 + $2, $1 * $2'
LANGUAGE SQL;

-- xfunc.sgml:742
DROP FUNCTION sum_n_product (x int, y int, OUT sum int, OUT product int);

-- xfunc.sgml:742
DROP FUNCTION sum_n_product (int, int);

-- xfunc.sgml:773
CREATE PROCEDURE tp1 (accountno integer, debit numeric, OUT new_balance numeric) AS $$
    UPDATE bank
        SET balance = balance - debit
        WHERE accountno = tp1.accountno
    RETURNING balance;
$$ LANGUAGE SQL;

-- xfunc.sgml:784
CALL tp1(17, 100.0, NULL);

-- xfunc.sgml:820
CREATE FUNCTION mleast(VARIADIC arr numeric[]) RETURNS numeric AS $$
    SELECT min($1[i]) FROM generate_subscripts($1, 1) g(i);
$$ LANGUAGE SQL;

-- xfunc.sgml:820
SELECT mleast(10, -1, 5, 4.4);

-- xfunc.sgml:836
SELECT mleast(ARRAY[10, -1, 5, 4.4]);    -- doesn't work

-- xfunc.sgml:855
SELECT mleast(VARIADIC ARRAY[10, -1, 5, 4.4]);

-- xfunc.sgml:869
SELECT mleast(VARIADIC ARRAY[]::numeric[]);

-- xfunc.sgml:886
SELECT mleast(VARIADIC arr => ARRAY[10, -1, 5, 4.4]);

-- xfunc.sgml:892
SELECT mleast(arr => 10);

-- xfunc.sgml:892
SELECT mleast(arr => ARRAY[10, -1, 5, 4.4]);

-- xfunc.sgml:923
CREATE FUNCTION foo(a int, b int DEFAULT 2, c int DEFAULT 3)
RETURNS int
LANGUAGE SQL
AS $$
    SELECT $1 + $2 + $3;
$$;

-- xfunc.sgml:923
SELECT foo(10, 20, 30);

-- xfunc.sgml:923
SELECT foo(10, 20);

-- xfunc.sgml:923
SELECT foo(10);

-- xfunc.sgml:923
SELECT foo();  -- fails since there is no default for the first argument

-- xfunc.sgml:972
INSERT INTO foo VALUES (1, 1, 'Joe');

-- xfunc.sgml:972
INSERT INTO foo VALUES (1, 2, 'Ed');

-- xfunc.sgml:972
INSERT INTO foo VALUES (2, 1, 'Mary');

-- xfunc.sgml:972
CREATE FUNCTION getfoo(int) RETURNS foo AS $$
    SELECT * FROM foo WHERE fooid = $1;
$$ LANGUAGE SQL;

-- xfunc.sgml:972
SELECT *, upper(fooname) FROM getfoo(1) AS t1;

-- xfunc.sgml:1043
CREATE TABLE tab (y int, z int);

-- xfunc.sgml:1043
INSERT INTO tab VALUES (1, 2), (3, 4), (5, 6), (7, 8);

-- xfunc.sgml:1043
CREATE FUNCTION sum_n_product_with_tab (x int, OUT sum int, OUT product int)
RETURNS SETOF record
AS $$
    SELECT $1 + tab.y, $1 * tab.y FROM tab;
$$ LANGUAGE SQL;

-- xfunc.sgml:1043
SELECT * FROM sum_n_product_with_tab(10);

-- xfunc.sgml:1078
SELECT * FROM nodes;

-- xfunc.sgml:1078
CREATE FUNCTION listchildren(text) RETURNS SETOF text AS $$
    SELECT name FROM nodes WHERE parent = $1
$$ LANGUAGE SQL STABLE;

-- xfunc.sgml:1078
SELECT * FROM listchildren('Top');

-- xfunc.sgml:1078
SELECT name, child FROM nodes, LATERAL listchildren(name) AS child;

-- xfunc.sgml:1126
SELECT listchildren('Top');

-- xfunc.sgml:1126
SELECT name, listchildren(name) FROM nodes;

-- xfunc.sgml:1159
SELECT x, generate_series(1,5) AS g FROM tab;

-- xfunc.sgml:1163
SELECT x, g FROM tab, LATERAL generate_series(1,5) AS g;

-- xfunc.sgml:1197
SELECT srf1(srf2(x), srf3(y)), srf4(srf5(z)) FROM tab;

-- xfunc.sgml:1211
SELECT x, CASE WHEN x > 0 THEN generate_series(1, 5) ELSE 0 END FROM tab;

-- xfunc.sgml:1255
SELECT x, CASE WHEN y > 0 THEN generate_series(1, z) ELSE 5 END FROM tab;

-- xfunc.sgml:1259
CREATE FUNCTION case_generate_series(cond bool, start int, fin int, els int)
  RETURNS SETOF int AS $$
BEGIN
  IF cond THEN
    RETURN QUERY SELECT generate_series(start, fin);
  ELSE
    RETURN QUERY SELECT els;
  END IF;
END$$ LANGUAGE plpgsql;

-- xfunc.sgml:1259
SELECT x, case_generate_series(y > 0, 1, z, 5) FROM tab;

-- xfunc.sgml:1301
CREATE FUNCTION sum_n_product_with_tab (x int)
RETURNS TABLE(sum int, product int) AS $$
    SELECT $1 + tab.y, $1 * tab.y FROM tab;
$$ LANGUAGE SQL;

-- xfunc.sgml:1323
CREATE FUNCTION make_array(anyelement, anyelement) RETURNS anyarray AS $$
    SELECT ARRAY[$1, $2];
$$ LANGUAGE SQL;

-- xfunc.sgml:1323
SELECT make_array(1, 2) AS intarray, make_array('a'::text, 'b') AS textarray;

-- xfunc.sgml:1354
SELECT make_array(1, 2.5) AS numericarray;

-- xfunc.sgml:1361
CREATE FUNCTION make_array2(anycompatible, anycompatible)
RETURNS anycompatiblearray AS $$
    SELECT ARRAY[$1, $2];
$$ LANGUAGE SQL;

-- xfunc.sgml:1361
SELECT make_array2(1, 2.5) AS numericarray;

-- xfunc.sgml:1376
SELECT make_array2('a', 'b') AS textarray;

-- xfunc.sgml:1388
CREATE FUNCTION is_greater(anyelement, anyelement) RETURNS boolean AS $$
    SELECT $1 > $2;
$$ LANGUAGE SQL;

-- xfunc.sgml:1388
SELECT is_greater(1, 2);

-- xfunc.sgml:1388
CREATE FUNCTION invalid_func() RETURNS anyelement AS $$
    SELECT 1;
$$ LANGUAGE SQL;

-- xfunc.sgml:1410
CREATE FUNCTION dup (f1 anyelement, OUT f2 anyelement, OUT f3 anyarray)
AS 'SELECT $1, ARRAY[$1, $1]' LANGUAGE SQL;

-- xfunc.sgml:1410
SELECT * FROM dup(22);

-- xfunc.sgml:1425
CREATE FUNCTION anyleast (VARIADIC anyarray) RETURNS anyelement AS $$
    SELECT min($1[i]) FROM generate_subscripts($1, 1) g(i);
$$ LANGUAGE SQL;

-- xfunc.sgml:1425
SELECT anyleast(10, -1, 5, 4);

-- xfunc.sgml:1425
SELECT anyleast('abc'::text, 'def');

-- xfunc.sgml:1425
CREATE FUNCTION concat_values(text, VARIADIC anyarray) RETURNS text AS $$
    SELECT array_to_string($2, $1);
$$ LANGUAGE SQL;

-- xfunc.sgml:1425
SELECT concat_values('|', 1, 4, 2);

-- xfunc.sgml:1473
SELECT anyleast('abc'::text, 'ABC');

-- xfunc.sgml:1480
SELECT anyleast('abc'::text, 'ABC' COLLATE "C");

-- xfunc.sgml:1488
CREATE FUNCTION anyleast (VARIADIC anyarray) RETURNS anyelement AS $$
    SELECT min($1[i] COLLATE "en_US") FROM generate_subscripts($1, 1) g(i);
$$ LANGUAGE SQL;

-- xfunc.sgml:1795
CREATE FUNCTION square_root(double precision) RETURNS double precision
    AS 'dsqrt'
    LANGUAGE internal
    STRICT;

-- xfunc.sgml:2943
SELECT name, c_overpaid(emp, 1500) AS overpaid
    FROM emp
    WHERE name = 'Bill' OR name = 'Sam';

-- xfunc.sgml:3877
SELECT wait_event_type, wait_event FROM pg_stat_activity
     WHERE backend_type ~ 'worker_spi';
