-- Generated by script/extract-doc-sql.js from doc/src/sgml/xindex.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- xindex.sgml:1280
SELECT * FROM mytable ORDER BY somecol USING ~<~;

-- xindex.sgml:1300
SELECT sum(x) OVER (ORDER BY x RANGE BETWEEN 5 PRECEDING AND 10 FOLLOWING)
  FROM mytable;

-- xindex.sgml:1404
SELECT * FROM table WHERE integer_column < 4;
