-- Generated by script/extract-doc-sql.js from doc/src/sgml/xplang.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- xplang.sgml:179
CREATE FUNCTION plperl_call_handler() RETURNS language_handler AS
    '$libdir/plperl' LANGUAGE C;

-- xplang.sgml:189
CREATE FUNCTION plperl_inline_handler(internal) RETURNS void AS
    '$libdir/plperl' LANGUAGE C STRICT;

-- xplang.sgml:189
CREATE FUNCTION plperl_validator(oid) RETURNS void AS
    '$libdir/plperl' LANGUAGE C STRICT;

-- xplang.sgml:200
CREATE TRUSTED LANGUAGE plperl
    HANDLER plperl_call_handler
    INLINE plperl_inline_handler
    VALIDATOR plperl_validator;
