-- Generated by script/extract-doc-sql.js from doc/src/sgml/xtypes.sgml
-- Do not edit; see CONTRIBUTING.md, "The documentation SQL corpus".

-- xtypes.sgml:172
CREATE TYPE complex;

-- xtypes.sgml:204
CREATE TYPE complex (
   internallength = 16,
   input = complex_in,
   output = complex_out,
   receive = complex_recv,
   send = complex_send,
   alignment = double
);
